// File: /d/noden/house/pass5.c
// Generated by Roommaker Mon Dec  4 21:00:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阴暗走廊");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一条阴暗的走廊中，北边是走廊的尽头，你从这里可以看到一座
通往一楼的楼梯。这里的地板有些潮湿，你仔细一看，上面竟然有几个湿淋淋的
小孩子脚印(footprints)，南边是一间黑黝黝的起居室，隐隐约约传来一阵女人
轻柔的歌声，像是在唱著摇篮曲哄孩子睡觉....
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"footprints" : @LONG_TEXT
这些脚印相当小，而且似乎是刚刚走过才留下的，不过这并不是最奇怪的，你
发现脚印的方向是从西边走向东边，而你的西边和东边都是墙壁....
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/house/pass4", 
		"south" : "/d/noden/house/living_room" ]) );
	ob->reset();
}
