// File: /d/noden/house/pass4.c
// Generated by Roommaker Mon Dec  4 20:59:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊尽头");
	ob->set_long( @LONG_DESCRIPTION
你现在站在一条阴暗走廊的尽头，这里是古屋的二楼，一道木制的楼梯往下通
往一楼，北边的墙上有一个圆形的窗户(window)，你似乎听到南边有女人在唱歌的
声音，不过你的理智告诉你这样的鬼屋里不会有女人在唱歌，你壮著胆子准备面对
任何奇形怪状的鬼怪。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"window" : @LONG_TEXT
从窗子向外望去，一片青翠茂密的森林，几个孩子在屋後的空地上嘻嘻哈哈地
玩著游戏....慢著，孩子？....你很快地转过头，不再去关心窗外的景色。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"down" : "/d/noden/house/pass3", 
		"south" : "/d/noden/house/pass5", 
		"west" : "/d/noden/house/bedroom" ]) );
	ob->reset();
}
