// File: /d/noden/house/pass3.c
// Generated by Roommaker Mon Dec  4 20:59:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊尽头");
	ob->set_long( @LONG_DESCRIPTION
你现在站在一条阴暗走廊的尽头，北边是一扇圆形的窗户(window)，一道木制
楼梯通往古屋的二楼，两边的墙上各有一个铜制的烛台，上面的蜡烛是点著的，不
知道是什麽人留下来的？
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"window" : @LONG_TEXT
你往窗外望去，一片一望无际的碧蓝色大海，和屋内阴森森的气氛简直有天壤之别
....慢著，你记得进来的时候，北边应该是一片森林....，你感到一股凉意从脚底
升起....
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"up" : "/d/noden/house/pass4", 
		"south" : "/d/noden/house/pass2", 
		"west" : "/d/noden/house/kitchen" ]) );
	ob->reset();
}
