// File: /d/noden/house/attic.c
// Generated by Roommaker Thu Dec 23 08:06:37 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("阁楼");
	set_long( @LONG_DESCRIPTION
你现在正站在一间小小的阁楼里，南边是一个三角形的窗户(window)，这里的地上
零零散散地丢了满地的玩具(toys)，看起来像是小孩子住的地方，不过很奇怪的是，你
看不到这个房间有任何出口，只有地上一个地方用木板(board)钉起来的洞。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"board" : @LONG_TEXT
这些木板钉得十分仓促，有些板子上钉了十几根钉子，有些却还没有钉牢，似乎
钉这些木板的人受到了什麽惊吓。
LONG_TEXT
, 
		"toys" : "这些玩具有玩具兵、小木偶、小木剑....你猜住在这里的大概是位小男孩。\n", 
		"window" : @LONG_TEXT
你从窗户看出去，只见灰蒙蒙地一片雾气，不知道外面是什麽地方，窗户并没有
关著，如果你试著爬(climb)出去的话，也许可以离开这个诡异的地方。
LONG_TEXT
 ]) );
	set( "objects", ([ 
		"boy" : "/d/noden/house/monster/boy" ]) );
	reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#25");
	add_action("do_climb", "climb");
}

int do_climb(string arg)
{
	if( !arg || arg!="window" ) return 0;
   write( "你爬过窗户，往一片灰蒙蒙的雾中跳下去....。\n" );
	this_player()->move_player( "/d/noden/house/grave1", "SNEAK" );
    tell_room( this_object(),
       this_player()->query("c_cap_name")+ "爬出窗户，消失在一片灰蒙蒙的雾中。\n",
		this_player() );
	return 1;
}
