// File: /d/noden/house/bedroom.c
// Generated by Roommaker Wed Dec 22 22:05:20 1993

#include <mudlib.h>

inherit ROOM;
int diary;

void create()
{
	::create();
   set_short("主卧室");
	set_long( @LONG_DESCRIPTION
你现在来到这栋古屋的主卧室，房间中央一张木制的大床(bed)，床边有一面巨大
的镜子(mirror)，北边似乎原来有一扇窗户，但是屋子的主人用砖块把窗户封死了
，你觉得这里的气氛和其他地方有点不同，但是到底哪里不同一时也说不上来。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"bed" : @LONG_TEXT
这是一张看起来颇大的双人床，床单上绣著一朵朵红色的花....啊....是许多
血迹！
LONG_TEXT
, 
		"mirror" : "你注视这镜子中自己的影子一会儿，并没有看到任何预期中的可怕景象。\n" ]) );
	set( "exits", ([ 
		"east" : "/d/noden/house/pass4" ]) );
	set( "objects", ([
		"harold" : "/d/noden/house/monster/ghost_harold" ]) );
	set( "search_desc", ([
		"bed" : "@@search_bed" ]) );
	reset();
}

void reset()
{
        ::reset();
        diary = 1;
}

string search_bed()
{
	object obj;

   if( !diary ) return "你找了又找，并没有发现任何东西。\n";
	obj = new( "/d/noden/house/obj/diary" );
	obj->move( this_object() );
	diary = 0;
   return  "你在床底下发现了一本老旧的日记！\n";
}
