// File: /d/noden/house/cellar1.c
// Generated by Roommaker Sat Dec 25 21:46:11 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
   set_short("地下室");
	set_long( @LONG_DESCRIPTION
你现在来到一个阴暗的地下室，潮湿的空气中似乎还带著一丝丝酒味，也许这
里是屋子主人储藏酒类的地窖，角落里一个几乎腐蚀断裂的木梯通往一楼的客厅。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"south" : "/d/noden/house/cellar2", 
		"up" : "/d/noden/house/hall" ]) );
	create_door( "south", "north", ([
		"keyword" : ({ "wooden door", "door" }),
		"name" : "wooden door",
		"c_name" : "木门",
		"c_desc" : "一扇很普通的木门",
		"status" : "locked",
		"lock" : "GHOST_HAROLD_CELLAR"
	]) );
	reset();
}
