// File: /d/noden/house/cellar2.c
// Generated by Roommaker Sat Dec 25 21:51:33 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
   set_short("酒窖");
	set_long( @LONG_DESCRIPTION
你现在正位於一间阴暗的酒窖中，这间酒窖堆满了许多酒桶(barrels)和一箱箱
的酒瓶(bottles)，所有的酒类都按照年份分门别类堆放在架子上，这里原来的主人
必定是位酒类的专家，这里没有任何窗户，可是不知道从哪里来的风一阵阵地吹得
你感觉凉飕飕的....
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"bottles" : @LONG_TEXT
这些酒瓶大部分都是空的，有些酒瓶里面装著的好像不是酒，是因为几十年
来的湿气所积的水。
LONG_TEXT
, 
		"barrels" : @LONG_TEXT
这些酒桶都用泥土封住，以免地下室的湿气影响酒的品质，算一算这里的酒桶
一共有将近三十个，里面到底还有没有酒从外面看不出来....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/cellar1" ]) );
	set( "objects", ([
           "bravar" : "/d/noden/house/monster/bravar" ]) );
	create_door( "north", "south", ([
		"keyword" : ({ "wooden door", "door" }),
		"name" : "wooden door",
		"c_name" : "木门",
		"c_desc" : "一扇很普通的木门",
		"status" : "locked",
		"lock" : "GHOST_HAROLD_CELLAR"
	]) );
	reset();
}
