// File: /d/noden/house/grave.c
// Generated by Roommaker Wed Dec 22 22:11:10 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("墓园");
	set_long( @LONG_DESCRIPTION
你现在站在一大堆「一望无际」的墓碑(tombstone)中间，四周全是一片灰蒙蒙
的雾，一股莫名的恐惧袭上你的心头，这里是什麽地方？死後的世界？你听到一阵
低沈的祈祷(pray)声从四面八方传来，不过也许是幻觉....
LONG_DESCRIPTION
	);
	set( "light", 1 );
	set( "item_func", ([
		"tombstone" : "look_tombstone" ]) );
	set( "objects", ([
		"variel": "/d/noden/house/monster/ghost_variel" ]) );
	set( "exits", ([
		"north": "/d/noden/house/grave1",
		"south": "/d/noden/house/grave1",
		"east": "/d/noden/house/grave1",
		"west": "/d/noden/house/grave1" ]) );
	reset();
}

void init()
{
	add_action( "do_pray", "pray" );
	add_action( "do_bury", "bury" );
}

void look_tombstone()
{
	write( "上面写著: "+this_player()->query("c_cap_name") + " 171 年死因不明，葬於此地。\n");
}

int do_pray()
{
	write( 
		"你闭上眼睛开始祈祷....祈祷些什麽呢？....\n");
	tell_room( this_object(), 
		this_player()->query("c_cap_name") + "闭上眼睛开始祈祷....\n",
		this_player() );
	if( random(10)<5 ) {
		// Move silently
		this_player()->move( "/d/noden/house/hall" );
	}
	return 1;
}

int do_bury(string arg)
{
	object obj, ghost;

	if( !arg || arg=="" || !(obj= present( arg, this_player() )) )
		return notify_fail( "埋葬什麽？\n" );
	if( !obj->id("corpse") )
		return notify_fail( 
			"埋葬这种东西对这里的死者有失尊敬 ....\n");

	write("你挖了一个洞穴，把尸体埋在里面 ....\n");

	tell_room( this_object(), 
		this_player()->query("c_cap_name") + "挖了一个洞穴，然後把一具尸体埋在里面。\n",
		this_player() );
	if( obj->id("corpse of Devil boy") ) {
		if ( !this_player()->query_temp("devil_killer")) 
		{ 
		write( @NOT_YET
当你刚把尸体埋好，一个奇怪的声音从地底传了出来：「哈哈哈 ～～你的力量
还压制不住我，休想把我送回地狱去 !!」。一道漆黑的轻烟缓缓的从地底升起
慢慢的飘散在灰蒙蒙的雾中。你的直觉告诉你：事情并没有结束。
NOT_YET
		      );
		obj->remove();
		return 1;
		}
		if( (int)this_player()->query_quest_level("cursed_house") < 1 ) {
			this_player()->finish_quest( "cursed_house", 1 );
			write( "[你完成了 Cursed_house 任务，得到 10,000 点经验]\n");
			this_player()->gain_experience(10000);
		}
		if( ghost= present("ghost of Variel", this_object() ) )
			ghost->quest_finished( this_player() );
	}
	obj->remove();
	return 1;
}
