// File: /d/noden/house/hall.c
// Generated by Roommaker Thu Dec 23 14:40:19 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("大厅");
	set_long( @LONG_DESCRIPTION
你现在站在一间破旧的大厅，发霉的地毯和破烂不堪的家具是这个大厅仅剩下
的东西，北边靠墙的地方有一座古老的挂钟(clock)，挂钟旁是一个火炉(fireplace)
，东倒西歪的椅子和散落地面的石块显示这里曾经遭遇一场可怕的破坏，是什麽东西
造成这里凌乱不堪的景象？
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"clock" : "这座挂钟正指著十一点四十六分，不过很显然的，它已经停了几十年了。\n", 
		"fireplace" : @LONG_TEXT
这个火炉上面积满了灰尘，不过你发现里面有几根烧过的木炭，竟然还是温热的
！难道这个地方还有人住吗？
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass1", 
		"out" : "/d/noden/16,13.noden" ]) );
	set( "objects", ([ 
		"bill" : "/d/noden/house/monster/ghost_bill" ]) );
   set( "search_desc", ([
                 "fireplace" : "@@search_fireplace" ]) );
	reset();
}

string search_fireplace()
{
   add( "exits", ([
        "down" : "/d/noden/house/cellar1" ]) );
	set( "exit_suppress", ({ "down" }) );
     return "你仔细搜索火炉, 竟然发现一个往下的通道!\n";
}

void reset()
{
   delete( "exits/down" );
   ::reset();
}
