// File: /d/noden/house/kitchen.c
// Generated by Roommaker Wed Dec 22 23:04:53 1993

#include <mudlib.h>

inherit ROOM;
int cookie;

void create()
{
	::create();
   set_short("厨房");
	set_long( @LONG_DESCRIPTION
从这里的布置看起来，你大概可以猜出这里是一间厨房，一些老旧不堪的橱柜
(cupboard)和厨房用具散置在房间中，墙角有一个金属桶子(can)在黑暗中反射著
从你这边照过去的光线，往东可以回到走廊上。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"cupboard" : @LONG_TEXT
这些橱柜有些已经积满了灰尘，有些却擦拭得一尘不染，其中一个橱柜甚至还
残留著食物的香味....
LONG_TEXT
, 
		"can" : @LONG_TEXT
这大概是垃圾桶吧....你一边这样想著，一边掀开盖子，一股几乎令人窒息的
尸臭味冒了出来，你立刻将盖子盖回去。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"east" : "/d/noden/house/pass3" ]) );
	set( "objects", ([ 
		"ham" : "/d/noden/house/monster/ham" ]) );
   set( "search_desc", ([
            "cupboard" :  "@@search_cupboard" ]) );
	reset();
}

void reset()
{
        ::reset();
        cookie = 1;
}

string search_cupboard()
{
        object obj;

   if( !cookie ) return
            "你找了又找，并没有发现任何东西。\n";
   obj = new( "/d/noden/house/obj/cookie" );
   obj->move( this_object() );
   cookie = 0;
   return "你仔细搜索橱柜, 发现了一片饼乾！\n";
}
