// File: /d/noden/house/living_room.c
// Generated by Roommaker Thu Dec 23 07:45:55 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("起居室");
	set_long( @LONG_DESCRIPTION
你现在位於古屋二楼的起居室，这里的家具和其他地方比起来，似乎比较新也
比较完整，一个砖砌的壁炉(fireplace)和几张长长的沙发(sofa)构成这个房间的主
要装潢，你脚下所站的地方铺著一张淡紫色的地毯(carpet)，上面画著许多诡异的
同心圆，女人唱著摇篮曲的声音在你身边回汤著，但是这里一个人也没有....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"sofa" : @LONG_TEXT
形式很旧的沙发，上面积满了厚厚的灰尘，沙发上似乎有一些血迹，很难想像
这里曾经发生过什麽样的惨剧。
LONG_TEXT
, 
		"carpet" : @LONG_TEXT
这张地毯是圆形的，上面画著一、二、....共十三个同心圆(circle)，你光是看著这
张地毯就觉得一阵头晕....
LONG_TEXT
, 
		"fireplace" : @LONG_TEXT
这个壁炉里面打扫得很乾净，如果是二流的侦探小说，在这样的壁炉里面一定会
有一个密道....
LONG_TEXT
, 
		"circle" : @LONG_TEXT
你看著这些同心圆，忽然有个声音在你耳边说道: 进去吧(enter)吧，孩子！
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass5" ]) );
	reset();
}


void init()
{
	add_action( "do_enter", "enter" );
}

int do_enter(string arg)
{
	if( !arg || arg!= "circle" ) return 0;
   write(
		"你一脚踏进同心圆的中心，立刻感到一阵昏昏欲睡的感觉，像是有人在\n"
            "你的耳边唱著摇篮曲....\n" );
    tell_room( this_object(), 
        this_player()->query("c_cap_name") + "的身影突然变得模糊，然後消失了....\n",
		this_player() );
	this_player()->move_player( "/d/noden/house/attic", "SNEAK" );
	return 1;
}
