// File: /d/noden/house/pass2.c
// Generated by Roommaker Wed Dec 22 15:47:19 1993

#include <mudlib.h>

inherit ROOM;
int face = 1;

void create()
{
	::create();
   set_short("阴暗走廊");
	set_long( @LONG_DESCRIPTION
你现在走在一条阴暗的走廊上，北边不远处有一座木梯往上到二楼，两边的墙壁
上都有好几道深深的抓痕(scratch)，走廊往南通往这栋建筑的大厅。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"scratch" : @LONG_TEXT
这些抓痕共五条一组，似乎是人类用手抓出来的，但是人类可能有这麽大的力气
在坚硬的砖墙上抓出这样的痕迹吗？你开始想起一些属於原始恐惧的古老传说，
狼人？吸血鬼？.....你开始觉得毛骨悚然....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass3", 
		"south" : "/d/noden/house/pass1" ]) );
	set( "pre_exit_func", ([
		"north" : "loop_exit" ]) );
	set( "search_desc", ([
		"here" : "@@search_here" ]) );
	reset();
}

int loop_exit()
{
	if( face || present( "face", this_object() ) ) {
            write(
			"你向前走了几步，一股奇怪的感觉告诉你: 地板在动！\n"
                    "莫名的恐惧使你停了下来。\n" );
		return 1;
	} else return 0;
}

string search_here()
{
	object obj;

    if( !face || present("face", this_object()) ) return
            "你找了又找，并没有发现任何东西。\n";
	obj = new( "/d/noden/house/monster/face" );
	obj->move( this_object() );
	face = 0;
   return "你仔细搜索这里的墙壁，猛然看到一张女人的脸从墙壁伸出来！\n";
}
