// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"
inherit ROOM;

void create()
{
	::create();
	set_short("喷泉");
	set_long( @C_LONG_DESCRIPTION
这里是一个乾枯\的喷泉，除了石头以外这里空无一物。
C_LONG_DESCRIPTION
	);
	set( "light", 0 );
	set( "exits", ([
	    "out" : Lcave"cave30"
	]) );
	set("layuter_dig",1);
	reset();
}
void init()
{
 add_action("do_search","search");
 this_player()->set_explore("eastland#22");
}
void reset()
{
	::reset();
	set("beer_control",1);
}

int do_search(string arg)
{
	object obj;
        if (!arg) arg="here";
	if( arg!="here")
	  return notify_fail(
	    "你在这里中找来找去，但并没有找到任何奇特的东西。\n"
	  );
        else {
          if ((string)this_player()->query("class")=="scholar") {
 write("你发现喷泉北边的土似乎有点松动，於是就试著去挖挖看.............，\n"); 
 write("挖著挖著...............突然一团黑影从土□窜了出来..............，\n");
 write("你的面前一团黑影正不断的在游移著，你听到一个声音从黑影中传了出来：\n");
 write("我被困在□面好久了...谢谢你帮我离开...以後假如须要帮助，在所不辞。\n");
 write("你看到那团黑影渐渐消散了。\n");
          this_player()->set("demand/dark",2);
          } 
          else
            write( "这喷泉北边的土似乎点松动。\n");
   	  return 1;
	}
}
