// File: /open/polo/noden/farwind/bazz4.c
// Generated by Roommaker Mon Nov  6 06:27:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微风路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在微风路上。广场位於你的西方不远处，微风路向东
一路延伸下去，北边的建筑物目前正在出租。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/cemetery", 
		"west" : "/d/noden/farwind/bazz3" ]) );
	ob->reset();
}
