// File: /open/polo/noden/farwind/cellar3.c
// Generated by Roommaker Mon Nov  6 06:28:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
这个地洞十分窄小，墙壁上有一条条的抓痕。往西边的通路地势稍微高了一点
，东南方传来一阵阵腐臭的味道。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/noden/farwind/cellar2.c", 
		"southeast" : "/d/noden/farwind/cellar4.c" ]) );
	ob->reset();
}
