// File: /d/noden/farwind/cellar6.c
// Generated by Roommaker Sun Nov 19 20:22:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
你很惊讶地发现地洞中会有这样的一个地方，墙壁上挂著一盏油灯(lamp)，
桌子、椅子、床铺应有尽有，这里的主人身材似乎不是很高，因为大部分的家具
都很小，你注意到地洞的一角有一个木箱(chest)。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/farwind/cellar5.c" ]) );
	ob->set( "item_desc", ([ 
		"lamp" : "这盏油灯虽然看起来十分粗糙，但是它点亮了这整个房间。\n", 
		"chest" : @LONG_TEXT
 一个相当精致的木箱子，虽然很脏，但仍然看得出来是装贵重物品
的箱子。你走近一看，里面是空的。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"giant rat" : "/d/noden/farwind/monster/giant_rat" ]) );
	ob->reset();
}
