// File: /open/polo/noden/farwind/cellar2.c
// Generated by Roommaker Mon Nov  6 06:28:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
这个地洞十分窄小，墙壁上有一条条的抓痕，似乎是某种有巨大
爪子的生物所抓出来的。一股腐臭的味道从地洞的东边传来。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/cellar3.c", 
		"up" : "/d/noden/farwind/cellar1.c" ]) );
	ob->set( "objects", ([ 
		"rat 4" : "/d/noden/farwind/monster/rat" ]) );
	ob->reset();
}
