// File: /open/polo/noden/farwind/ebazz.c
// Generated by Roommaker Mon Nov  6 06:28:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微风路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在微风路上。广场位於你的东方不远处，微风路向西
一路延伸下去, 北边的建筑物是本镇的教堂, 南边是一间结婚礼服用
品店。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/square", 
		"south" : "/d/noden/farwind/wedding_store", 
		"west" : "/d/noden/farwind/wbazz", 
		"north" : "/d/noden/farwind/church" ]) );
	ob->reset();
}
