// File: /open/polo/noden/farwind/nmain.c
// Generated by Roommaker Mon Nov  6 06:29:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("远风镇大街");
	ob->set_long( @LONG_DESCRIPTION
这里是远风镇大街的尽头，从这里往北出远风镇是一条乡村小路，衔接镇外
北方的田野，在你的东边是远风镇的银行。西边的建筑是法院，不过入口并不在
这边。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/bank", 
		"north" : "/d/noden/14,5.noden", 
		"south" : "/d/noden/farwind/square" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/obj/vendor" ]) );
	ob->reset();
}
