// File: /open/polo/noden/farwind/path1.c
// Generated by Roommaker Mon Nov  6 06:29:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小路");
	ob->set_long( @LONG_DESCRIPTION
这是一条乡村中常见的小路，远风镇在冒险者公会成立之前，最多
的路就是像这样的小路。在你的北边不远处是远风镇的西门，东边一栋
房子看起来像是有钱人的住宅，门口还有一座小喷泉(fountain)，里面
不知道住著哪位大人物。从这里往南是河边的一块空地，往西似乎有一
条石阶往下通往河床边上。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/farwind/clearing", 
		"north" : "/d/noden/farwind/w_gate", 
		"west" : "/d/noden/farwind/steps" ]) );
	ob->set( "item_desc", ([ 
		"fountain" : @LONG_TEXT
这个喷泉造型相当优美，一个小天使的雕像站在池子中央，手中的瓶子不断涌出清 凉的泉水，你发现水池中有一点一点亮晶晶的东西，莫非这喷泉是许愿池？
LONG_TEXT
 ]) );
	ob->reset();
}
