// File: /d/noden/farwind/smain2.c
// Generated by Roommaker Sun Nov 19 20:19:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("远风镇大街");
	ob->set_long( @LONG_DESCRIPTION
你现在走在远风镇的大街上。北边不远处是远风镇的中心广场，在你
的东侧有一间铁匠铺，西边则是邮局。往南走你可以离开远风镇，进入诺
顿王国的野外区域。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/smithy", 
		"west" : "/d/noden/farwind/post_office", 
		"north" : "/d/noden/farwind/smain", 
		"south" : "/d/noden/14,7.noden" ]) );
	ob->reset();
}
