// File: /open/polo/noden/farwind/smain.c
// Generated by Roommaker Mon Nov  6 06:29:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("远风镇大街");
	ob->set_long( @LONG_DESCRIPTION
你现在走在远风镇的大街上。北边是远风镇的中心广场，在你的东侧有
一间商店，西边的建筑则是鼎鼎大名的冒险者公会。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "doors", ([ 
		"west" : ([ 
			"name" : "oak door", 
			"linked" : "east", 
			"keyword" : ({ 
				"oak door", 
				"door" }), 
			"c_desc" : "一扇结实厚重的橡木门", 
			"status" : "open", 
			"c_name" : "橡木门" ]) ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/shop", 
		"north" : "/d/noden/farwind/square", 
		"west" : "/d/adventurer/hall/adv_guild", 
		"south" : "/d/noden/farwind/smain2" ]) );
	ob->set( "item_desc", ([ 
		"west door" : "一扇结实厚重的橡木门，它现在是开著的。\n" ]) );
	ob->reset();
}
