// File: /open/polo/noden/farwind/tunnel1.c
// Generated by Roommaker Mon Nov  6 06:29:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞通道");
	ob->set_long( @LONG_DESCRIPTION
这里是一条阴暗狭窄的通道, 空气中弥漫著一股腐败食物的臭味, 你
隐隐约约地听到南边的地洞传来滴水的声音。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/noden/farwind/tunnel2.c", 
		"north" : "/d/noden/farwind/cellar4.c" ]) );
	ob->reset();
}
