// File: /open/polo/noden/farwind/wbazz.c
// Generated by Roommaker Mon Nov  6 06:30:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微风路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在微风路上。往东走你可以到达远风镇的广场，在你
的北边是一家新开的药材店，南边的墙上似乎写了一些字(writing)
，往西走是远风镇的西门。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/ebazz", 
		"west" : "/d/noden/farwind/w_gate", 
		"north" : "/d/noden/farwind/apoth" ]) );
	ob->set( "item_desc", ([ 
		"writing" : "「住在这间屋子里的人是大混蛋，生的儿子没屁眼！」\n" ]) );
	ob->reset();
}
