// File: /d/noden/bluesand/alley1.c
// Generated by Roommaker Mon Dec  4 22:07:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小巷");
	ob->set_long( @LONG_DESCRIPTION
这里是一条小巷子，左右的房屋虽然简陋，但是都颇为整洁，在这里
有一块告示板(board)，上面贴了几则启事。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/port_r0.c", 
		"south" : "/d/noden/bluesand/alley2.c" ]) );
	ob->reset();
}
