// File: /d/noden/bluesand/beach.c
// Generated by Roommaker Mon Dec  4 22:08:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白沙滩");
	ob->set_long( @LONG_DESCRIPTION
这里是一片白色的沙滩，洁白的海沙中夹杂著一点点蓝色的小石子，你走近
一看，发现它们都是透明的！也许这些石子是珍贵的宝石也不一定。沙滩向西方
继续延伸，东边是一些建筑物，一望无际的大海就在你的北方。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/beach1", 
		"south" : "/d/noden/bluesand/port_r1" ]) );
	ob->set( "objects", ([ 
		"crab#1" : "/d/noden/bluesand/monster/crab", 
		"crab#2" : "/d/noden/bluesand/monster/crab" ]) );
	ob->reset();
}
