// File: /d/noden/bluesand/office.c
// Generated by Roommaker Mon Dec  4 22:09:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("办公室");
	ob->set_long( @LONG_DESCRIPTION
这里是蓝沙港警备队长的办公室，洁净的窗户映著窗外蓝白夹杂的沙滩，使你
不得不羡慕起他们的工作环境，往北是一条建有许多仓库的街道，警备队常常在这
里巡逻，以免小偷肆虐。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/street2" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"captain" : "/d/noden/bluesand/monster/captain" ]) );
	ob->reset();
}
