// File: /d/noden/bluesand/port_r0.c
// Generated by Roommaker Mon Dec  4 22:09:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("港湾路");
	ob->set_long( @LONG_DESCRIPTION
你现在走在蓝沙港主要的街道，港湾路上。蓝沙港是个很新的港
口城市，由於和东方大国的贸易，你可以看到不少带有东方色彩的建
筑物。往东你可以远远望见蓝沙港的码头，北边是一家商店，如果你
往西走，就可以离开蓝沙港。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/port_r1.c", 
		"west" : "/d/noden/16,10.noden", 
		"north" : "/d/noden/bluesand/shop.c", 
		"south" : "/d/noden/bluesand/alley1.c" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
