// File: /d/noden/bluesand/port_r2.c
// Generated by Roommaker Mon Dec  4 22:10:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("港湾路");
	ob->set_long( @LONG_DESCRIPTION
你现在走在蓝沙港主要的街道，港湾路上。在你的北边是一片白中带
著淡蓝色细点的沙滩，东边是蓝沙港的码头，往南走通往一条宽敞却不热
闹的街道。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/jetty", 
		"south" : "/d/noden/bluesand/street1.c", 
		"west" : "/d/noden/bluesand/port_r1.c", 
		"north" : "/d/noden/bluesand/beach1" ]) );
	ob->reset();
}
