// File: /d/noden/bluesand/pub.c
// Generated by Roommaker Mon Dec  4 22:10:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("水手酒吧");
	ob->set_long( @LONG_DESCRIPTION
这里是蓝沙港名闻遐迩的水手酒吧，据说来到蓝沙港的人如果没有到
水手酒吧喝一杯「血玛莉」，就不算来过蓝沙港。这里的酒类种类之多足
以傲视整个诺顿王国，你可以「翻一翻」柜台上的酒单(menu)就知道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"menu" : "酒单上写著: 未成年不宜。\n" ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/port_r1.c" ]) );
	ob->set( "objects", ([ 
		"sailor 2" : "/d/noden/bluesand/monster/sailor", 
		"patrick" : "/d/noden/bluesand/monster/patrick" ]) );
	ob->reset();
}
