// File: /d/noden/bluesand/ship.c
// Generated by Roommaker Mon Dec  6 21:56:37 1993
// translation done 2-24-94 -Elon.

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("比亚蓝号");
	set_long( @LONG_DESCRIPTION
你现在站在一艘老旧的船上，破旧的船体和处处可见的蛀虫孔洞显示这
艘船早已不适合再航行於波涛汹涌的海上了，你发现只要稍微动一动，船身
就会发出嘎嘎的声音，码头就在你的西边不远处，趁著船还没有解体之前赶
快游(swim)回去吧。
LONG_DESCRIPTION
	);

	set( "objects", ([ "zombie": "/d/noden/bluesand/monster/zombie" ]) );
	reset();
}

void init()
{
	if( this_player() && present("zombie", this_object()) )
        this_player()->set_explore("noden#12");
	add_action( "do_swim", "swim" );
}

int do_swim(string arg)
{
	if( arg && arg!="back" )
            return notify_fail( "你想游到哪里去？\n" );
    write( "你循原来上船的地方游回码头。\n" );
	this_player()->move_player("/d/noden/bluesand/jetty", "SNEAK" );
    tell_room( "/d/noden/bluesand/jetty",
            this_player()->query("c_cap_name") + "湿漉漉地从海中爬上码头。\n",
		this_player() );
	return 1;
}
