// File: /d/noden/bluesand/shop.c
// Generated by Roommaker Wed Nov 17 14:37:26 1993
 
#include <mudlib.h>
#include <money.h>
 
inherit SHOP;
 
void create()
{
	::create();
   set_short("商店");
	set_long( @LONG_DESCRIPTION
这里是蓝沙港的商店，由於贸易的发达，蓝沙港常常充满各种珍奇宝物
与各式商品，因此你可以用最低廉的价格买到其他地方难得一见的货物，你
看到墙上贴了一张纸(paper)，上面写著: 「货真价实、童叟无欺」。
LONG_DESCRIPTION
);
 
	set( "exits", ([
		"south" : "/d/noden/bluesand/port_r0.c"
	]) );
	set( "c_item_desc", ([
		"paper" :
			"「货真价实、童叟无欺」....旁边一行小字: 货物售出，盖不退货。\n",
	]) );
	set( "light", 1 );
	set( "objects", ([
		"trashcan": "/obj/trashcan",
		"shopkeeper": "/d/noden/bluesand/monster/shopkeeper" ]) );
	reset();
	replace_program(SHOP);
}
