// File: /d/noden/moyada/mainrd7.c
// Generated by Roommaker Mon Dec  4 20:22:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你现在站在摩亚达城的主要道路，它大多以破碎的砖石所铺制而成
。往北就是城中心的著名的圆形广场与「银色之塔」。你可以看到一栋
很高且散发银色光芒的圆形建筑物。西边有一片沙地。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/moyada/rndplza.c", 
		"west" : "/d/noden/moyada/sand_square.c", 
		"south" : "/d/noden/moyada/mainrd3.c" ]) );
	ob->set( "objects", ([ 
		"ant worker" : "/d/noden/moyada/monster/ant_worker", 
		"ant killer" : "/d/noden/moyada/monster/ant_killer" ]) );
	ob->reset();
}
