// File: /d/noden/moyada/mainrd4.c
// Generated by Roommaker Mon Dec  4 20:22:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("死胡同");
	ob->set_long( @LONG_DESCRIPTION
你现在站在摩亚达城的主要道路的尽头，地面多以破碎的砖石所铺制
而成。往西是城中心的圆形广场与「银色之塔」。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/moyada/mainrd8.c" ]) );
	ob->set( "objects", ([ 
		"worker#1" : "/d/noden/moyada/monster/worker" ]) );
	ob->reset();
}
