// File: /d/noden/moyada/mainrd3.c
// Generated by Roommaker Mon Dec  4 20:21:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("死胡同");
	ob->set_long( @LONG_DESCRIPTION
你现在站在摩亚达城的主要道路的尽头，地面乃是以破碎的砖石所
铺制而成。往北是城中心的圆形广场与「银色之塔」。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/moyada/mainrd7.c" ]) );
	ob->reset();
}
