// File: /d/noden/moyada/mainrd6.c
// Generated by Roommaker Mon Dec  4 20:22:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你现在站在摩亚达城的主要道路，它大多以破碎的砖石所铺制而成
。往东就是城中心的著名的圆形广场与「银色之塔」。你可以看到一栋
很高且散发银色光芒的圆形建筑物。北边有一栋古老的建筑，生锈的铁
门半掩著，破裂的窗户和高大的藤蔓，散发一股阴森的气息，像极了电
影中的鬼屋，你的本能告诉你最好别进去。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/moyada/rndplza.c", 
		"north" : "/d/noden/moyada/old_house/entrance.c", 
		"west" : "/d/noden/moyada/mainrd2.c" ]) );
	ob->set( "objects", ([ 
		"balbal#2" : "/d/noden/moyada/monster/balbal", 
		"balbal#1" : "/d/noden/moyada/monster/balbal" ]) );
	ob->reset();
}
