// File: /d/eastland/liang_shan/bed6.c
// Generated by Roommaker Tue Nov 21 16:02:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("军官休息室");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊典型的军官休息室，隐藏在四棵巨大的松树後面，
由窗内看去，则是一片水洗般的青翠，触目皆是绿意盎然的树木，有
如一个大盆景础b你面前，空气中有著高山的冷冽，但却使人倍感舒
畅。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/yard2" ]) );
	ob->reset();
}
