// File: /d/eastland/liang_shan/bed1.c
// Generated by Roommaker Tue Nov 21 15:59:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("支援部队预备室");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的支援部队预备室，由於这里距城墙非常近，若有敌人来袭
可迅速投入战场，现在这里驻扎的是鲁智深的步兵第一队。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/path3" ]) );
	ob->set( "objects", ([ 
		"wu" : "/d/eastland/liang_shan/monster/monk", 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit" ]) );
	ob->reset();
}
