// File: /d/eastland/liang_shan/bed7.c
// Generated by Roommaker Tue Nov 21 15:59:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城墙守备指挥室");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的城墙守备指挥室，在这里，城墙指挥官下达所有的作战指
令，目前的指挥官是花荣。房间中间放著一张会议桌，是守备评议开会时
所使用的，墙上有一张城墙的守备兵力图。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/eastland/liang_shan/wall7" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"hua" : "/d/eastland/liang_shan/monster/hua" ]) );
	ob->reset();
}
