// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 16:01:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵营");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的部队休息室，如果强盗们没有排到侦察或防御的任务时，
这里就是他们过夜休息的地方，如果没有特殊事情的话，部队的指挥官也
会在这里休息，直到换防或轮休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 16:01:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵营");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的部队休息室，如果强盗们没有排到侦察或防御的任务时，
这里就是他们过夜休息的地方，如果没有特殊事情的话，部队的指挥官也
会在这里休息，直到换防或轮休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 22:11:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵营");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的部队休息室，如果强盗们没有排到侦察或防御的任务时，
这里就是他们过夜休息的地方，如果没有特殊事情的话，部队的指挥官也
会在这里休息，直到换防或轮休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
