// File: /d/eastland/liang_shan/cave2.c
// Generated by Roommaker Tue Nov 21 16:02:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
洞穴的四周插满了火把，照的四周一片明亮，许\多山贼在洞穴里钻来钻去，只有
少数人注意到你的进入而投以怀疑的目光。你似乎听到了一股潺潺的水流声。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/eastland/liang_shan/cave1", 
		"northdown" : "/d/eastland/liang_shan/cave3" ]) );
	ob->reset();
}
