// File: /d/eastland/liang_shan/cave3.c
// Generated by Roommaker Tue Nov 21 16:02:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
曲折的洞穴，到了这里忽然开展，这山腹中竟然是空的，巨大的穹顶，离地至少
数十丈，方圆不知几百丈，一个人站在这头呼喊，等他闭上嘴时声音才传得到另一头
。西边的山壁上，有一条向上的小通路，东边有一条通道，似乎能够离开这些洞穴，
刚刚听到的水声，你发现是由东面传来的。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/eastland/liang_shan/cave2", 
		"east" : "/d/eastland/liang_shan/water_castle", 
		"westup" : "/d/eastland/liang_shan/cave4" ]) );
	ob->set( "objects", ([ 
		"chi" : "/d/eastland/liang_shan/monster/seven" ]) );
	ob->reset();
}
