// File: /d/eastland/liang_shan/cave1.c
// Generated by Roommaker Tue Nov 21 16:03:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你进入了城墙上的洞穴，洞穴的四周插满了火把，照的四周一片明亮，许\多山贼
在洞穴里钻来钻去，只有少数人注意到你的进入而投以怀疑的目光。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northdown" : "/d/eastland/liang_shan/cave2", 
		"out" : "/d/eastland/liang_shan/wall5" ]) );
	ob->reset();
}
