// File: /d/eastland/liang_shan/down_hall.c
// Generated by Roommaker Tue Nov 21 16:04:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("忠义厅楼下");
	ob->set_long( @LONG_DESCRIPTION
这是一间小小的房间，四壁都是坚硬的石壁，东北方似乎有个小门。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/eastland/liang_shan/hall", 
		"northeast" : "/d/eastland/liang_shan/jail2" ]) );
	ob->reset();
}
