// File: /d/eastland/liang_shan/drug.c
// Generated by Roommaker Tue Nov 21 15:58:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("药店");
	ob->set_long( @LONG_DESCRIPTION
你一走进这家药铺，一股强烈的药味差点让你窒息，这里是梁山唯一一家药
铺兼医院，是神医安道全所开设的，这里所卖的药材与价钱以及医疗的费用全都
写在一张挂在壁上的价格表(list)上，往东走可回到天王大道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"list" : @LONG_TEXT
--------------------------------------------------
贩卖药材:                    贩卖价格:           
    金创药(plaster):              6 金币         
    云南白药(white plaster):     15 金币         
    天香断续膏(spicy plaster):   25 金币         
    天山雪莲(snow_lily):        450 金币         
                                                 
服务项目:                    所需价格:         
    基本医疗(heal):             3 金币/HP      
    快速止血(clot):            15 金币/次      
    中和毒性(cure):            25 金币/次      
    体质改善(sick):            30 金币/次      
    包扎伤口(bandage):          6 金币/次      
                                               
                              若医师不在请稍待片刻
--------------------------------------------------
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/path1" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/eastland/liang_shan/monster/doctor" ]) );
	ob->reset();
}
