// File: /d/eastland/liang_shan/dryroom.c
// Generated by Roommaker Tue Nov 21 16:00:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("晒衣场");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊的晒衣场，在洗衣房洗乾净的衣服，全部送到这边
处理．轻风吹来，翻飞的衣物，让你觉得头晕目眩．一个少年正在此
忙碌的工作．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/washroom" ]) );
	ob->set( "objects", ([ 
		"da" : "/d/eastland/liang_shan/monster/washer" ]) );
	ob->reset();
}
