// File: /d/eastland/liang_shan/path6.c
// Generated by Roommaker Tue Nov 21 16:02:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("回廊");
	ob->set_long( @LONG_DESCRIPTION
你穿过了聚义厅，来到了一条小小的回廊，回廊建筑的很精巧，也很壮
丽，朱红的阑干，一尘不染的地板，回廊外的假山流水，茂林修竹，你不禁
暗暗赞叹设计者的匠心与保养的辛劳，往北通往一片树林，往东往西都
可通至庭院。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/yard1", 
		"west" : "/d/eastland/liang_shan/yard2", 
		"north" : "/d/eastland/liang_shan/path7", 
		"south" : "/d/eastland/liang_shan/chuyi_hall" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
