// File: /d/eastland/liang_shan/path4.c
// Generated by Roommaker Tue Nov 21 16:01:18 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走道");
	ob->set_long( @LONG_DESCRIPTION
这是一条小小的街道，虽然没有天王大道那麽宽大，但它联接了寨墙和
大演武场，提供了快速支援防卫的功能．北边有一个类似碉堡的建筑，南方
有一个小门，传来阵阵菜肴的香气，使你觉得饥肠辘辘．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"eastup" : "/d/eastland/liang_shan/wall5", 
		"north" : "/d/eastland/liang_shan/bed4", 
		"south" : "/d/eastland/liang_shan/kitchen", 
		"west" : "/d/eastland/liang_shan/plaza3" ]) );
	ob->set( "objects", ([ 
		"captain" : "/d/eastland/liang_shan/monster/captain" ]) );
	ob->reset();
}
