// File: /d/eastland/liang_shan/path1.c
// Generated by Roommaker Tue Nov 21 15:57:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("天王大道");
	ob->set_long( @LONG_DESCRIPTION
这山寨内竟有一条街道，一条以整齐的青石板铺成的，不折不扣的街
道．据说是为了纪念第一代老大: 托塔天王晁盖而命名．街道两旁，有各
色各样的店铺，每一间店铺的生意都好的很，只不过店铺的门外，都没有
招牌．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/horseroom", 
		"west" : "/d/eastland/liang_shan/drug", 
		"north" : "/d/eastland/liang_shan/path2", 
		"south" : "/d/eastland/liang_shan/gate1" ]) );
	ob->reset();
}
