// File: /d/eastland/liang_shan/path7.c
// Generated by Roommaker Tue Nov 21 16:03:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林间小径");
	ob->set_long( @LONG_DESCRIPTION
你来到了一条寂静的林间小径，空气中夹带著山区特有的料峭气息，
往下俯瞰，可以看到梁山泊在树影中若隐若现，人间的喧闹，已隔的好远
好远，唯一的声响，恐怕只有流窜在松林间的些许微风，和脚步踏在落叶
松针上的轻响。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/path8", 
		"south" : "/d/eastland/liang_shan/path6" ]) );
	ob->set( "objects", ([ 
		"squirrel2" : "/d/eastland/monster/squirrel", 
		"squirrel1" : "/d/eastland/monster/squirrel" ]) );
	ob->reset();
}
