// File: /d/eastland/liang_shan/plaza2.c
// Generated by Roommaker Tue Nov 21 16:00:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大演武场");
	ob->set_long( @LONG_DESCRIPTION
这里是山寨内著名的大演武场，平时陉l头林冲都在此操练部下．训
练格斗或阵法．场边放著各式的兵刃，发出森森的寒光．如果你想加入山
寨，最快的方法就是在此显显身手．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/plaza3", 
		"west" : "/d/eastland/liang_shan/flag" ]) );
	ob->reset();
}
