// File: /d/eastland/liang_shan/room1.c
// Generated by Roommaker Wed Nov 22 16:46:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小书房");
	ob->set_long( @LONG_DESCRIPTION
这是一间小小的书房，窗明几静，朴素典雅，一张古意盎然的红木书桌，
吸引了你的目光，上面摆著一座小小的香炉，几本善本书整齐的堆放在桌上
，可见主人相当的爱惜书本。一个男子正坐在桌前，神情肃穆，若有所思。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/liang_shan/yard3" ]) );
	ob->reset();
}
