// File: /d/eastland/liang_shan/wall5.c
// Generated by Roommaker Tue Nov 21 16:01:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("栅上小路");
	ob->set_long( @LONG_DESCRIPTION
这里是梁山泊大寨上的小路，是为了防御攻击而建造的．但近几年
来，已没有人敢来侵犯了．站在这里，远方的风景一览无遗．木栅在这
里连接到山壁上，小路也只通到此处．北边山壁上有一个洞，隐隐传出
人声．除此之外，你注意到从寨内有条小路可通往此地．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"westdown" : "/d/eastland/liang_shan/path4", 
		"cave" : "/d/eastland/liang_shan/cave1", 
		"south" : "/d/eastland/liang_shan/wall4" ]) );
	ob->set( "objects", ([ 
		"shei2" : "/d/eastland/liang_shan/monster/shei2" ]) );
	ob->reset();
}
