// File: /d/eastland/liang_shan/water_castle.c
// Generated by Roommaker Tue Nov 21 16:03:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("水寨");
	ob->set_long( @LONG_DESCRIPTION
这是一个小小的碉堡，里面驻扎著梁山泊的水军。这碉堡地势非常险要
三面环山，一面临水，碉堡内有秘道可通往山壁内。临水的一面停满了大大
小小的战船，随时都可以开入湖中作战。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/lake/beach1", 
		"west" : "/d/eastland/liang_shan/cave3" ]) );
	ob->set( "objects", ([ 
		"wu" : "/d/eastland/liang_shan/monster/five", 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"zhan" : "/d/eastland/liang_shan/monster/zhan2" ]) );
	ob->reset();
}
