// File: /d/eastland/goomay/bath_shop.c
// Generated by Roommaker Thu Nov 23 18:34:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("热海澡堂");
	ob->set_long( @LONG_DESCRIPTION
你走进一家大澡堂，前面有两个门，分别是男女浴池。能够在一天的疲劳
奔波後好好的洗个澡，找个老师傅按摩按摩，这真是人生的一大享受。一个年
老的婆婆正倚在门前的凳子上看著你，要进去当然要先付钱喽，还有 ! 可别
「不小心」走错门了。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/row15" ]) );
	ob->set( "objects", ([ 
		"woman1" : "/d/eastland/goomay/monster/mama" ]) );
	ob->reset();
}
