// File: /d/eastland/goomay/col23.c
// Generated by Roommaker Thu Nov 23 18:40:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石板大道");
	ob->set_long( @LONG_DESCRIPTION
你走在古梅镇平坦的青石大道上，光洁的青石板显示著这个城镇的活力，
伴随在你身边的是小贩的吆喝声、马车的辚辚声还有偶而疾驰而过的骏马，那
是一些想要成名的武林人物，古梅镇的西风尘沙中，不知埋葬了多少年轻人的
梦想。街道向南北方延伸而去，东方是世德堂药铺，西方是集古斋。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/plaster_shop", 
		"west" : "/d/eastland/goomay/old_stuff", 
		"south" : "/d/eastland/goomay/col22", 
		"north" : "/d/eastland/goomay/col24" ]) );
	ob->reset();
}
