// File: /d/eastland/goomay/doshu_temple.c
// Generated by Roommaker Thu Nov 23 18:38:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("至阳观");
	ob->set_long( @LONG_DESCRIPTION
你走进一座道观，这道观人潮拥挤，显得香火十分鼎盛，正堂上供奉著降伏
龟蛇二妖的真武大帝，整座堂上雕梁画栋金碧辉煌，富贵气十足。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/doshu_temple2", 
		"south" : "/d/eastland/goomay/row11" ]) );
	ob->set( "objects", ([ 
		"little doshu2" : "/d/eastland/goomay/monster/little_doshu", 
		"little doshu" : "/d/eastland/goomay/monster/little_doshu" ]) );
	ob->reset();
}
