// File: /d/eastland/goomay/entrance.c
// Generated by Roommaker Thu Nov 23 18:45:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矿坑入口");
	ob->set_long( @LONG_DESCRIPTION
在你面前矗立著一座矿坑，赭红色的矿石屑随著矿车的轨迹
散落在地面上，形成一片片红色的波纹，向西方一座小山似的矿
石堆漾去，矿坑前来往的矿车不断，坑口还钉了块木牌(sign)。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay_mine/m_enter", 
		"south" : "/d/eastland/goomay/ruin5" ]) );
	ob->set( "forsy_appear", 0 );
	ob->set( "item_desc", ([ 
		"sign" : @LONG_TEXT
你看了看木牌，原来是一面告示，上面写著：

    此地为私人产业，非得允许\\\擅入者以盗贼论处 !! 
    任意毁损产业伤害工作人员者，依法送官究办 !!

					段铁
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/eastland/goomay/monster/mine_guard", 
		"guard1" : "/d/eastland/goomay/monster/mine_guard" ]) );
	ob->reset();
}
