// File: /d/eastland/goomay/ghost_house.c
// Generated by Roommaker Thu Nov 23 18:48:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("空屋");
	ob->set_long( @LONG_DESCRIPTION
走进这幢空荡荡的屋子里，一阵似有若无的寒气向你直逼过来。摆\设
得错落有致的家具虽然久被尘封，但是从他们的造型和质料上你仍可以想
见原屋主的品味气度，不知道发生了什麽奇怪的事，使得屋主匆忙离去，
甚至连小偷也绝足不来。你心中升起一阵不祥的预感。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col26" ]) );
	ob->set( "objects", ([ 
		"rat2" : "/d/noden/farwind/monster/rat", 
		"rat1" : "/d/noden/farwind/monster/rat" ]) );
	ob->reset();
}
