// File: /d/eastland/goomay/hunter_house.c
// Generated by Roommaker Thu Nov 23 18:45:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("破落的小屋");
	ob->set_long( @LONG_DESCRIPTION
这是一间破破烂烂的小屋，屋中到处都是油垢和垃圾，墙上挂了一些动物
的毛皮等杂物，几根结实的木棒摆\在门边，旁边还堆了些捕兽机具，或许\这间
屋子的主人是猎人也说不定。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/ruin4" ]) );
	ob->set( "objects", ([ 
		"fishman" : "/d/eastland/goomay/monster/hunter" ]) );
	ob->reset();
}
