// File: /d/eastland/goomay/kwi_yi2.c
// Generated by Roommaker Thu Nov 23 18:35:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("快意堂内堂");
	ob->set_long( @LONG_DESCRIPTION
你走进快意堂的内堂，随著你的脚步那些轰闹的吆喝声渐渐远去，相
反的，一路上酒瓶酒□却越来越多，而且个个来历不凡，贵州茅台酒、羊
城五粮液、吐鲁番的葡萄酒等等..种类真是不可胜数。可以想见这里的老
大一定是个好酒品酒的专家。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/goomay/kwi_yi" ]) );
	ob->set( "objects", ([ 
		"master" : "/d/eastland/goomay/monster/master_jau" ]) );
	ob->reset();
}
