// File: /d/eastland/goomay/mgate.c
// Generated by Roommaker Thu Nov 23 18:32:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古梅镇镇口");
	ob->set_long( @LONG_DESCRIPTION
这里原来是位於翰烟山下的一个小镇，本来只有三十来户的人家散布在一片方圆
不到五里的台地上，但是自从二十馀年前，飞仙一剑叶孤城与陆小凤在禁城的一场斗
智斗力的精彩决战後，每年十月皇上都要在此地举办武斗大会，渐渐的，本镇也成为
武林各帮派的兵家必争之地。现在古梅镇的繁华已经跟京城相差不远了。北方是古梅
镇的青石板大街，东边有一家酒楼，西边是一家客栈，南方通向东方大陆的旷野。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/wine_shop", 
		"west" : "/d/eastland/goomay/guess_house", 
		"south" : "/d/eastland/2,4.east", 
		"north" : "/d/eastland/goomay/col21" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"guard2" : "/d/eastland/goomay/monster/cityguard", 
		"guard1" : "/d/eastland/goomay/monster/cityguard" ]) );
	ob->reset();
}
