// File: /d/eastland/goomay/plaster_shop.c
// Generated by Roommaker Thu Nov 23 18:40:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("世德堂药铺");
	ob->set_long( @LONG_DESCRIPTION
你走进一家铺子，迎面而来的是一阵阵馥郁的药草香，正堂上悬著一块
乌木匾额，上面大书 "世德其昌" 四个亮金大字，两旁药柜上的墙上满满的
悬著各式匾额，显见这家药店的主人在古梅镇的名声十分良好，目前世德堂
的主人是一个老医生，他正在铺里打瞌睡。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col23" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/eastland/goomay/monster/old_doctor" ]) );
	ob->reset();
}
