// File: /d/eastland/goomay/rich_house.c
// Generated by Roommaker Thu Nov 23 18:41:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("立锥堂");
	ob->set_long( @LONG_DESCRIPTION
这里是大财主钱不多的家，可是看起来却一点也不起眼，大厅里空空
荡荡的只有几张太师椅围著一张八仙桌，跟你想像的大财主之家实在相差
甚远，有几个人正围著桌子商议不休，看来最好不要打扰他们，西边有一
道珠帘轻掩的月洞门。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/green_pearl", 
		"north" : "/d/eastland/goomay/row25" ]) );
	ob->set( "objects", ([ 
		"richman" : "/d/eastland/goomay/monster/richman" ]) );
	ob->reset();
}
