// File: /d/eastland/goomay/row25.c
// Generated by Roommaker Thu Nov 23 18:41:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("武斗大会会场门口");
	ob->set_long( @LONG_DESCRIPTION
这里是著名的天下第一武斗大会会场门口，每一个习武的人都以能在
武斗大会上崭露头角为毕生大志，所以决斗的、熟悉场地的还有过过乾瘾
的都把武斗大会会场当成圣地，常要来朝拜一番。原本朝廷禁止民间使用
本会场，後来禁不胜禁，乾脆开放收钱，倒也增加了不少收入。街道向东
西延伸而去，北方是武斗大会场，南方是立锥堂。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/row24", 
		"west" : "/d/eastland/goomay/row26", 
		"south" : "/d/eastland/goomay/rich_house" ]) );
	ob->set( "objects", ([ 
		"guardian" : "/d/eastland/goomay/monster/guardian" ]) );
	ob->reset();
}
