// File: /d/eastland/goomay/row11.c
// Generated by Roommaker Thu Nov 23 18:38:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石板大道");
	ob->set_long( @LONG_DESCRIPTION
你走在古梅镇平坦的青石大道上，光洁的青石板显示著这个城镇的活力，
伴随在你身边的是小贩的吆喝声、马车的辚辚声还有偶而疾驰而过的骏马，那
是一些想要成名的武林人物，古梅镇的西风尘沙中，不知埋葬了多少年轻人的
梦想。南方是衙门的外墙，墙上贴了一些告示(signs)，街道向东西延伸而去。
北方是玄阳观。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/row12", 
		"north" : "/d/eastland/goomay/doshu_temple" ]) );
	ob->set( "item_desc", ([ 
		"signs" : @LONG_TEXT
那两张告示上面写著：

	悬   赏   逃   犯                     追   缉   要   犯
	    ( Huang )			  	   ( Jor )
通缉逃犯黄二一名，身矮、面黄无须、左  通缉江洋大盗左无心一名，身长八尺，孔
脚微跛，脸有刀疤，犯下杀人重刑，被判  武有力，擅轻身功\\\夫，有日行千家夜盗百
秋後斩决，三日前越狱逃走，如有捕获者  户之能，涉及同仁老当及其他窃案四十馀
赏银五百两，通报者半赏。              件，捕获者赏银五千两，通报者半赏。

详情请洽捕头。 

旁边还画了两个丑丑的人像，看起来穷凶极恶、猥屑不堪。	

LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"cop2" : "/d/eastland/goomay/monster/cop", 
		"cop1" : "/d/eastland/goomay/monster/cop" ]) );
	ob->reset();
}
