// File: /d/eastland/goomay/ruin2.c
// Generated by Roommaker Thu Nov 23 18:44:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("破落的贫民窟");
	ob->set_long( @LONG_DESCRIPTION
看惯了古梅镇金碧辉煌的一面，你一下子很难接受这种破落的地方竟然
也是古梅镇的一部份。这里是以往旧镇的遗址，不过还是有些穷人住在这里
，在颓圮的断墙间生长的野花，偶而几声小孩的吵闹声、鸡鸣犬吠，都使你
感觉住在这里的人并不寂寞。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/ruin3", 
		"north" : "/d/eastland/goomay/ruin4", 
		"west" : "/d/eastland/goomay/ruin1" ]) );
	ob->set( "objects", ([ 
		"drunk" : "/d/eastland/goomay/monster/drunk" ]) );
	ob->reset();
}
