// File: /d/eastland/goomay/ruin4.c
// Generated by Roommaker Thu Nov 23 18:44:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("暗巷");
	ob->set_long( @LONG_DESCRIPTION
这里是一条幽暗的窄巷，两旁都是破落的老建筑，檐角的密密蛛丝和
厚厚的灰尘，使你有一种时间冻结了的感觉，巷弄左右都是小小的缺口，
好像一条条小路，一阵阵的犬吠鸡鸣在破落的废墟中回响。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/hunter_house", 
		"north" : "/d/eastland/goomay/ruin5", 
		"south" : "/d/eastland/goomay/ruin2" ]) );
	ob->reset();
}
