// File: /d/eastland/goomay/ruin5.c
// Generated by Roommaker Thu Nov 23 18:45:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("荒废的广场");
	ob->set_long( @LONG_DESCRIPTION
你来到一片开阔的广场，原本平整的地面此刻已长满了杂草，鹅黄色
的野花随著微风在小路两旁款款而笑，泛出赭红色油光的路面显示这里仍
然有许\多人每天经过，□□的风声中，有断断续续的轴轳转动声自北方传
来。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/entrance", 
		"south" : "/d/eastland/goomay/ruin4" ]) );
	ob->reset();
}
