// File: /d/eastland/goomay/sooth_shop.c
// Generated by Roommaker Thu Nov 23 18:35:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("有所不知命相");
	ob->set_long( @LONG_DESCRIPTION
你走进一家命相馆，迎面一张特大号的挂帘把内堂遮了大半，上头画了
个大大的金钱... 原来这家是专卜金钱挂的，你可别小看了这间小小的店子
，江湖上提起「有所不知」这四个大字真是无人不知，据说他上通天文、下
知地理、前推千载後算百年，十足十的无所不知，这个店名的是由他的口头
禅「客官你有所不知」来的。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/row16" ]) );
	ob->set( "objects", ([ 
		"soothsayer" : "/d/eastland/goomay/monster/soothsayer" ]) );
	ob->reset();
}
