// File: /d/eastland/goomay/wei_yuan.c
// Generated by Roommaker Thu Nov 23 18:47:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("威远镖局");
	ob->set_long( @LONG_DESCRIPTION
这是铁笔狂鹰周逵所开设的镖局，一进门就是一片坚实的练武场，
门口两侧高高竖起的旗杆上各自挂著一面黑底金面的锦旗，上面锦绣
著「威远」两个大字，迎风烈烈作响，显得极有威势。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col25" ]) );
	ob->set( "objects", ([ 
		"man3" : "/d/eastland/goomay/monster/mercenary", 
		"man2" : "/d/eastland/goomay/monster/mercenary", 
		"master" : "/d/eastland/goomay/monster/chief_merc", 
		"man1" : "/d/eastland/goomay/monster/mercenary" ]) );
	ob->reset();
}
