// File: /d/eastland/goomay/wine_shop2.c
// Generated by Roommaker Thu Nov 23 18:34:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("赵燕居二楼");
	ob->set_long( @LONG_DESCRIPTION
这里是赵燕居大酒楼的二楼，宽阔的厅堂摆\满了桌椅，此刻虽然客人
不少，可是却又不显得吵闹，邻街的地方有几的坐位都还空著，只坐著一
个很有气派的中年人。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/goomay/wine_shop" ]) );
	ob->set( "objects", ([ 
		"master" : "/d/eastland/goomay/monster/master_fan", 
		"singer" : "/d/eastland/goomay/monster/singer" ]) );
	ob->reset();
}
