// File: /d/eastland/goomay/yi_hong.c
// Generated by Roommaker Thu Nov 23 18:36:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("怡红院");
	ob->set_long( @LONG_DESCRIPTION
看见沿门挂出的两排红灯笼(lantern)，你已经可以猜到这是什麽地方，
每个灯笼上都写著「怡红」两个大字，怡红院是专门招待有钱大爷的地方，
所以不管三教九流，只要现在口袋有钱，都是怡红院的上宾。也因为如此，
院内的姑娘、妈妈还有提大茶壶的王八龟奴每个都是见多识广，只要你有兴
趣一定可以听到一些有趣的事。□
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/goomay/row16" ]) );
	ob->set( "objects", ([ 
		"servant" : "/d/eastland/goomay/monster/servant" ]) );
	ob->reset();
}
