// File: /d/eastland/haiwei/hockshop.c
// Generated by Roommaker Sat Jan 22 13:08:55 1994

#include <goomay.h>

inherit "/d/eastland/goomay/hocker";
//inherit ROOM;

void create()
{
	::create();
	set_short("同仁当铺");
	set_long( @LONG_DESCRIPTION
你现在走进了一间布置得相当考究的厅院，门口一爿蓝色的布帘上写著
四个大字「同仁老当」，这家当铺是古梅镇暴发户钱不多的产业，他刚刚从
以前当铺的主人手中把这家当铺巧取豪夺过来，正打算好好赚上一票，不过
他对古董的眼光可真不是盖\的。墙上有一张纸，大概是说一些当铺的行事规
矩，乌檀木做成的隔窗後面正有一位老朝奉对著你笑。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"west" : Goomay"col22" ]) );
      set("c_item_desc",(["paper":@C_LONG
    这是一张十分陈旧的泛黄皮纸，上面被人用乌亮的浓墨挥洒著
流利的隶书，使你看的心旷神怡。写著 ：

    亲爱的同仁老当客户大爷们，小店一向秉持诚信态度为客户服务
，然为避免不必要之纠纷，特此公告小铺之条规以昭大信，盼小店与
客户共同遵循，相互规矩为是。下列条规 ：

    一、物品当值均以时价折抵保管费後计算。
    二、本店最多只接受同一位客户四次保管委托。
    三、所托物品在本店盘点时间之前未取者视同流当，小店得任意处置。
    四、取回托物时本铺得酌量收取保管费与利息。

小店的营业项目有： 当物 (impawn)、赎回当物(take)、查询当物(list)
，请您多多照顾小店的生意。谢谢 !!
 
   有需要托物服务的请面洽本铺大朝奉。

C_LONG

                           ]));

	set( "objects", ([
		"shopkeeper" : Mob"pawnbroker",
		]));

	reset();
}
void init()
{
	::init();
        add_action("impawn2", "impawn");
}
int impawn2(string str)
{
       if ((int)this_player()->query_quest_level("Goddess_statue") > 2 ) 
		return hocker::impawn(str);
	else
	tell_object(this_player(),@C_HOCKSHOP
刘掌柜叹了一口气道：「对不起 !! 客官 !! 小店暂停营业了，我们正在想办法
找回被偷走的质押品－一尊价值连城的月神像(statue)，如果找不回来，小店信
誉扫地那是不消说了，恐怕连我自己都性命难保 !! 唉 ～～」
C_HOCKSHOP
	);
	return 1;
}
