// File: /d/noden/recamp/camp3.c
// Generated by Roommaker Sat Nov 25 14:16:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->seteuid(getuid());
	ob->set_short("帐棚");
	ob->set_long( @LONG_DESCRIPTION
这里是一个用兽皮、麻布、以及一些不知名的东西拼凑搭成的帐棚，帐棚
内部的空间并不是很大，你可以看到这里堆著一些瓶瓶罐罐的药剂(potions)，
几个木箱(chests)或立或倒地排在角落里，往东可以离开这个帐棚。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"chests" : @LONG_TEXT
几个外面漆著鲜艳色彩的箱子，不过很可惜，里面除了一些衣物以外，没有
其他有趣东西。
LONG_TEXT
, 
		"potions" : @LONG_TEXT
这些药剂有的是绿的，有的是黄的，但是上面都没有贴标签，只有调配者
才知道这些药剂是用来干什麽的。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp1" ]) );
	ob->set( "objects", ([ 
		"shaman" : "/d/noden/recamp/npc/shaman" ]) );
	ob->reset();
}
