// File: /d/noden/recamp/camp1.c
// Generated by Roommaker Sat Nov 25 14:08:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("营地");
	ob->set_long( @LONG_DESCRIPTION
你现在站在一个营地中央的空地上，你的面前是一堆已经烧光的营火(
campfire)，在你的北边是一个大帐棚，东边有一个用茅草搭成的小屋，西
边是另一个比较小的帐棚，往南可以离开这个营地。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"campfire" : @LONG_TEXT
这堆营火已经烧光了, 旁边有一些焦黑的树枝与木柴, 很显然的有人不久
前曾在这聚会或生火煮食。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp2", 
		"north" : "/d/noden/recamp/camp4", 
		"south" : "/d/noden/15,3.noden", 
		"west" : "/d/noden/recamp/camp3" ]) );
	ob->set( "objects", ([ 
		"boarman" : "/d/noden/recamp/npc/boarman" ]) );
	ob->reset();
}
