// File: /d/noden/recamp/camp_pool.c
// Generated by Roommaker Sat Nov 25 14:29:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地道");
	ob->set_long( @LONG_DESCRIPTION
你看到宽广的地道中央竟有一个水池(pool)。水池清凉沁新，令人心旷神怡。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/recamp/camp9", 
		"up" : "/d/noden/recamp/camp8" ]) );
	ob->set( "item_desc", ([ 
		"pool" : "这座水池深不可测，散发著股清凉的气息，令人心旷神怡。\n" ]) );
	ob->set( "objects", ([ 
		"frog#2" : "/d/noden/recamp/npc/frog", 
		"frog#5" : "/d/noden/recamp/npc/frog", 
		"frog#3" : "/d/noden/recamp/npc/frog", 
		"frog#1" : "/d/noden/recamp/npc/frog", 
		"frog#4" : "/d/noden/recamp/npc/frog" ]) );
	ob->set( "water_source", 1 );
	ob->reset();
}
