// Generated by Roommaker Tue Dec  7 22:16:00 1993
// Modified by freeway 5/15 1995

#include <mudlib.h>
#include "camp.h" 

inherit ROOM;

void create()
{
	::create();
   set_short("帐棚");
	set_long( @LONG_DESCRIPTION
你现在来到一个比较大的帐棚，这里的摆设让你有一种感觉，住在这个
帐棚里面的人一定是一位勇猛的战士，你看见地上铺著一张熊皮，周围有一
大堆的野兽头骨，像是战利品般的被分类堆放著，你面前有一张座椅，上面
铺著一张五彩斑斓的虎皮，座椅前面有一个锅子(cauldron)正放在炉火上煮
著，散发出一股香味。帐棚里还挂著一张诱人的立体图片(picture)。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"cauldron" : @LONG_TEXT
这个锅子的香味使你忍不住伸长脖子往里头看，哇....恶....一粒半兽人
的头颅正在锅子里和你大眼瞪小眼，你突然觉得这股香味变得有点臭了。
LONG_TEXT
,
                "picture":@C_LONG
你不禁吞了吞口水，心跳猛然加速，呼吸急促起来，画面中画满了许多
赤裸裸的女孩，正以各种撩人的姿势，大胆的展露出那健美的身材。你
发现上面好像有人摸过的痕迹，你不禁也想要摸摸看(touch)。
C_LONG
		]) );

	set( "exits", ([ 
		"south" : "/d/noden/recamp/camp1" ]) );
	set( "objects", ([ 
		"leader" : "/d/noden/recamp/npc/leader" ]) );
		
	reset();
}

void init()
{
	add_action("do_touch","touch");
}

int do_touch(string arg)
{
	if ( !arg || arg != "picture" )
		return notify_fail("你要摸什麽？\n");
	if ( !query("exits/down") ) {
	write(@LONG
你露出邪恶的笑容，伸手向图中耸起的部份摸去，发现软软的，好像真的一样，
於是你双出齐出，使了一招「双龙抢珠」，突然「拍」的一声，下边出现了一道
暗门。
LONG
	);
	tell_room(this_object(),this_player()->query("c_name")+
	"伸手向图中耸起的部份摸去，突然「拍」的一声，下边出现了一道暗门。\n",
	this_player() );
	set("exits/down",CAMP"camp5");
   set( "exit_suppress", ({ "down" }) );
	return 1;
	}
	write("你伸手向图中耸起的部份摸去，暗门就自动关了起来。\n");
	delete("exits/down");
	return 1;
}

void reset()
{
	delete("exits/down");
	::reset();
}
