// File: /d/eastland/yogor/eastgate.c
// Generated by Roommaker Thu Jan 27 00:52:30 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "幽国城");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在来到位於群山环抱的幽国城东门，幽国城自古以来一直是少商谷最大
的首府，少商谷物产丰富，四季如春，不过这几年西边太仓山兴起一股悍匪，官
兵几次围剿都没能平定，因此幽国城只开东门，南、北、西三门平时都紧闭著。
C_LONG_DESCRIPTION
	);

	set_outside( "eastland" );
	set( "light", 1 );
	set( "exits", ([ 
		"east" : "/d/eastland/5,15.east" ]) );
	reset();
}
