// File: /d/deathland/island/forest05.c
// Generated by Roommaker Thu Nov 23 19:56:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之岛的森林");
	ob->set_long( @LONG_DESCRIPTION
一个黑漆漆的森林, 这森林似乎充满著荆棘与矮灌木, 地上都是腐烂的树叶, 是
个令人很想逃离的地方. 你发觉你已在森林的深处了. 
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/island/forest04" ]) );
	ob->set( "objects", ([ 
		"beast" : "/d/deathland/monster/beast03" ]) );
	ob->reset();
}
