// File: /d/deathland/island/forest09.c
// Generated by Roommaker Thu Nov 23 19:57:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之岛的森林");
	ob->set_long( @LONG_DESCRIPTION
一个黑漆漆的森林, 这森林似乎充满著荆棘与矮灌木, 地上都是腐烂的树叶, 是
个令人很想逃离的地方. 你发觉你已在森林的深处了. 
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/island/forest06", 
		"south" : "/d/deathland/island/forest10" ]) );
	ob->reset();
}
