// File: /d/deathland/island/forest12.c
// Generated by Roommaker Thu Nov 23 19:57:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之岛的森林");
	ob->set_long( @LONG_DESCRIPTION
一个黑漆漆的森林, 这森林似乎充满著荆棘与矮灌木, 地上都是腐烂的树叶, 是
个令人很想逃离的地方. 你发觉你已在森林的深处了. 东边有一个小木屋, 但是
好像年久失修的样子.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southwest" : "/d/deathland/island/forest10", 
		"east" : "/d/deathland/island/forest15" ]) );
	ob->reset();
}
