// File: /d/deathland/island/stair06.c
// Generated by Roommaker Thu Nov 23 19:53:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("Í¨ÍùµØµ×µÄ½×Ìİ");
	ob->set_long( @LONG_DESCRIPTION
ÄãÎ»ì¶Ò»¸ö½×ÌİÉÏ,Õâ½×ÌİÒÔÂİĞı×´¿¿ÔÚÑÒ±ÚÉÏÍùÏÂÑÓÉìÖø.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/deathland/island/stair07", 
		"up" : "/d/deathland/island/stair05" ]) );
	ob->reset();
}
