// File: /d/deathland/island/swamp06.c
// Generated by Roommaker Thu Nov 23 19:50:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之岛的沼泽");
	ob->set_long( @LONG_DESCRIPTION
一个黑漆漆的沼泽, 沼泽下似乎有著可怕的生物想把你拖下去, 你必须小心谨慎
你的每一步. 越往东走沼泽的水就越深, 而且你的视线也被雾几乎完全地遮住了. 这
地里你已经无法清楚地看到四周的状况了, 只知道你的脚已经快深陷於沼泽里了.

LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"east", 
		"north", 
		"south" }) );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/island/swamp10", 
		"south" : "/d/deathland/island/swamp07", 
		"north" : "/d/deathland/island/swamp05", 
		"west" : "/d/deathland/island/swamp02" ]) );
	ob->set( "search_desc", ([ 
		"here" : @LONG_TEXT
你无法看清楚四面八方是否有你能立足的地方, 只知道离开这个沼泽
是你最好的选择.
LONG_TEXT
 ]) );
	ob->reset();
}
