// File: /d/noden/drow/r02.c
// Generated by Roommaker Mon Nov 27 14:19:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("侍卫队长休息室");
	ob->set_long( @LONG_DESCRIPTION
一进来，你似乎就可以感觉到一股战士们蓄势待发的气氛，这里是黑暗
精灵部队队长的休息室。你可以看到有张简单的行军床，和一张大桌子，桌
上放了一些文件，而角落则有一个大衣架，挂了一件军服。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/drow/r03" ]) );
	ob->set( "objects", ([ 
		"soldier" : "/d/noden/drow/mob/soldier",
		"captain" : "/d/noden/drow/mob/captain" ]) );
	ob->reset();
}
