// File: /d/noden/drow/r03.c
// Generated by Roommaker Mon Nov 27 14:19:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通道");
	ob->set_long( @LONG_DESCRIPTION
这里是黑暗精灵村的通道，由於整个村落都是在地底下的深处，这
里阴凉而空气清新，广大的通道宽广平坦，靠近石壁的地方，都雕刻有
蜘蛛，和蛇的图案。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/drow/r04", 
		"south" : "/d/noden/drow/r06", 
		"west" : "/d/noden/drow/r02" ]) );
	ob->reset();
}
