// File: /d/noden/drow/r05.c
// Generated by Roommaker Mon Nov 27 14:20:11 1995

#include <mudlib.h>

void create(object ob)
{
        if ( !ob ) return ;
        ob->set_short("兵器储藏室");
        ob->set_long( @LONG_DESCRIPTION
这是黑暗精灵村里，士兵们的武器及装备的收藏室。由於受到大蛇的骚
扰，这里平时就存放了好多士兵们战斗所需的武装等等，你可以看到墙上挂
的几幅人像，那些是历代的勇士们的画像。
LONG_DESCRIPTION
        );

        ob->set( "light", 0 );
        ob->set( "exits", ([
                "west" : "/d/noden/drow/r04" ]) );
        ob->set( "objects", ([
                "soldier#3" : "/d/noden/drow/mob/soldier",
                "soldier#2" : "/d/noden/drow/mob/soldier",
                "soldier#1" : "/d/noden/drow/mob/soldier" ]) );
        ob->reset();
}
