// File: /d/noden/drow/r16.c
// Generated by Roommaker Mon Nov 27 14:19:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("海伦神殿");
	ob->set_long( @LONG_DESCRIPTION
这里是海伦神殿，巨大的柱子雕塑著多种花卉，而神殿中央坐落著一
位女神－海伦，这里是黑暗精灵族人在迎接新生命时，都会带来给老村长
命名并且接受海伦女神枷筮的地方，通常由老村长来进行这件工作，但是
奴役却没有接受女神祝福的机会。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/drow/r15" ]) );
	ob->set( "objects", ([ 
		"m5" : "/d/noden/drow/mob/chief" ]) );
	ob->reset();
}
