// File: /d/noden/drow/r18.c
// Generated by Roommaker Mon Nov 27 14:20:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("广大通道");
	ob->set_long( @LONG_DESCRIPTION
这里是黑暗精灵村的主要通道，由於整个村落都是在地底下的深处
，这里阴凉而空气清新，广大的通道斜向地延伸，这里宽广平坦，靠近
石壁的地方，都雕刻有蜘蛛，和蛇的图案。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r22", 
		"northwest" : "/d/noden/drow/r13", 
		"east" : "/d/noden/drow/r19", 
		"west" : "/d/noden/drow/r17" ]) );
	ob->set( "objects", ([ 
		"guard" : "/d/noden/drow/mob/guard" ]) );
	ob->reset();
}
