// File: /d/noden/drow/r19.c
// Generated by Roommaker Mon Nov 27 14:20:38 1995

#include <mudlib.h>

void create(object ob)
{
        if ( !ob ) return ;
        ob->set_short("储藏室");
        ob->set_long( @LONG_DESCRIPTION
这里是黑暗精灵族人的储藏室，大部分的粮食以及民生物资都储存
在此，为了防止『努巴』以及其他的动物来盗取，啃食，这里也有士兵
的岗哨驻扎此地。
LONG_DESCRIPTION
        );

        ob->set( "light", 0 );
        ob->set( "exits", ([
                "west" : "/d/noden/drow/r18" ]) );
        ob->set( "objects", ([
                "soldier#2" : "/d/noden/drow/mob/soldier",
                "soldier#1" : "/d/noden/drow/mob/soldier" ]) );
        ob->reset();
}
