// File: /d/noden/drow/r21.c
// Generated by Roommaker Mon Nov 27 14:20:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("赛亚达神殿");
	ob->set_long( @LONG_DESCRIPTION
哇！眼前一个石像，居然雕刻的跟真人一样，挥舞双手，凝视远方，
全身穿著著一套幽黑色的盔甲，那一双带点慈蔼却炯炯有神的眼睛，好像
一个真人般，他就是黑暗精灵的守护神－赛亚达－。　
据说在远古时，就是他以一人之力，将八歧大蛇封在禁断之岩，後来族人
为了纪念他，也就盖了这间神殿，这里没有灿丽的雕塑，取而代之的是环
绕在神像旁的小水池，潺潺水声，令你有种清净的感觉。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/drow/r27" ]) );
	ob->set( "objects", ([ 
		"keiwi" : "/d/noden/drow/mob/keiwi" ]) );
	ob->reset();
}
