// File: /d/noden/drow/r22.c
// Generated by Roommaker Mon Nov 27 14:20:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("广大通道");
	ob->set_long( @LONG_DESCRIPTION
这里是黑暗精灵村的主要通道，由於整个村落都是在地底下的深处
，这里阴凉而空气清新，广大的通道斜向地延伸，这里宽广平坦，靠近
石壁的地方，都雕刻有蜘蛛，和蛇的图案。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r25", 
		"northeast" : "/d/noden/drow/r18" ]) );
	ob->reset();
}
