// File: /d/noden/drow/r23.c
// Generated by Roommaker Tue Dec  5 11:55:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗洞穴");
	ob->set_long( @LONG_DESCRIPTION
这里是村中奴役的起居室，简陋而肮脏，黑暗精灵是种阶级分明的种族
，贵族与平民，以及最低阶层的奴役，奴役大多被称为『努巴』，是没有社
会地位的下等精灵，只能提供劳役工作。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/drow/r24" ]) );
	ob->set( "objects", ([ 
		"slave#4" : "/d/noden/drow/mob/slave", 
		"slave#3" : "/d/noden/drow/mob/slave", 
		"slave#2" : "/d/noden/drow/mob/slave", 
		"slave#1" : "/d/noden/drow/mob/slave" ]) );
	ob->reset();
}
