// File: /d/noden/drow/r27.c
// Generated by Roommaker Mon Nov 27 14:18:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑暗精灵村入口");
	ob->set_long( @LONG_DESCRIPTION
通过昏暗的石阶，你来到了黑暗精灵村的入口了，这是一个由蜘蛛
图案雕塑在两个巨大石柱的大门，两旁挂有火把，由於黑暗精灵不需要
光，而这火把，则是由村内的人所点燃，为的是使外来的人，能较容易
的找到这地底的村落。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/drow/r24", 
		"north" : "/d/noden/drow/r21", 
		"south" : "/d/noden/drow/r28", 
		"northeast" : "/d/noden/drow/r25" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/noden/drow/mob/guard2", 
		"guard#1" : "/d/noden/drow/mob/guard2" ]) );
	ob->reset();
}
