// File: /d/noden/drow/r29.c
// Generated by Roommaker Mon Nov 27 14:15:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("蛇窝");
	ob->set_long( @LONG_DESCRIPTION
天啊？！好多的蛇！这里到处是蛇，有赤尾青竹丝，百步蛇，雨伞节
和巨大的蟒蛇等等，想必这里是大多数蛇的栖身场所吧。地上布满著蛇蜕
下的蛇皮，踩过去有种沙沙的声音，好恶心!!令你想快步通过。
咦？蛇的蜕皮中好像隐藏了个通道？是在．．．．．
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exit_suppress", ({ 
		"down" }) );
	ob->set( "exits", ([ 
		"down" : "/d/noden/drow/r42", 
		"southeast" : "/d/noden/drow/r32" ]) );
	ob->set( "objects", ([ 
		"snake#4" : "/d/noden/drow/mob/s1", 
		"snake#3" : "/d/noden/drow/mob/s1", 
		"snake#2" : "/d/noden/drow/mob/s1", 
		"snake#1" : "/d/noden/drow/mob/s1" ]) );
	ob->reset();
}
