// File: /d/noden/drow/r30.c
// Generated by Roommaker Mon Nov 27 14:22:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("蛇窝");
	ob->set_long( @LONG_DESCRIPTION
天啊？！好多的蛇！这里到处是蛇，有赤尾青竹丝，百步蛇，雨伞节
和巨大的蟒蛇等等，想必这里是大多数蛇的栖身场所吧。地上布满著蛇蜕
下的蛇皮，踩过去有种沙沙的声音，好恶心!!令你想快步通过。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r32", 
		"east" : "/d/noden/drow/r31" ]) );
	ob->set( "objects", ([ 
		"snake" : "/d/noden/drow/mob/s2" ]) );
	ob->reset();
}
