// File: /d/noden/drow/r39.c
// Generated by Roommaker Mon Nov 27 14:18:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("潮湿通道");
	ob->set_long( @LONG_DESCRIPTION
这里既潮湿又阴冷，前方不时传来阵阵冷飕飕的风声，令你感觉十分
的不好，四周的墙上结满了蜘蛛网，你最好赶紧离开。　　
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r40", 
		"northwest" : "/d/noden/drow/r38", 
		"southeast" : "/d/noden/drow/r41" ]) );
	ob->set( "objects", ([ ]) );
	ob->reset();
}
