// File: /d/noden/drow/r41.c
// Generated by Roommaker Mon Nov 27 14:18:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("潮湿下水道");
	ob->set_long( @LONG_DESCRIPTION
这里是一处下水道，地上积水大约半尺，并且有一股薰人的霉味，
水流异常缓慢，还飘来一些垃圾，好像是地面上的人乱丢的，四周墙壁
不时渗出水渍，滴滴答答的声音在这通道里造成回音。　
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/drow/r39", 
		"east" : "/d/noden/farwind/tunnel3.c", 
		"west" : "/d/noden/drow/r40" ]) );
	ob->set( "objects", ([ ]) );
	ob->reset();
}
