// File: /d/noden/drow/r42.c
// Generated by Roommaker Mon Nov 27 14:14:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阴暗水池");
	ob->set_long( @LONG_DESCRIPTION
这里灰暗潮湿，积水约半公尺深，你闻到一股脑人的霉味，与
水流悉娑的声音，你看到石墙上仍有蛇蜕下的皮黏挂在那儿，可见得
这里还是有生物的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/noden/drow/r29" ]) );
	ob->set( "in_well", 1 );
	ob->set( "objects", ([ 
		"mad snake" : "/d/noden/drow/mob/s7" ]) );
	ob->set( "underwater", 1 );
	ob->reset();
}
