// File: /d/deathland/main/d10.c
// Generated by Roommaker Thu Nov 23 20:16:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深渊的南边");
	ob->set_long( @LONG_DESCRIPTION
从这往北看去,有一个非常大,又非常深的深渊横在你的面前,似乎让人觉得它
就是通往地狱的入口 . 到了这里 , 一股寒意涌上心头,让你不禁怀疑是否你处在
一个噩梦中而一直无法醒来.风不停地由深渊吹上来,越来越强劲,你只能紧紧地贴
著岩壁慢慢地走,这样你才能避勉整个人被风吹走.往西看去有一团雾(fog)一直滞
留在那儿,你很惊讶为何在如此强劲的风势之下,那团雾竟然不会被吹散.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/main/d8", 
		"west" : "/d/deathland/main/d12" ]) );
	ob->set( "item_desc", ([ 
		"fog" : "一团黑雾.\n" ]) );
	ob->reset();
}
