// File: /d/deathland/main/d2.c
// Generated by Roommaker Thu Nov 23 20:18:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一个很深的洞穴");
	ob->set_long( @LONG_DESCRIPTION
这洞穴像是一直延申到地底去.而风从地底不停地吹上来. 一些奇奇怪怪的
图形画满了整个洞穴,除此之外,地上的足迹也是零零乱乱的,你无法清楚地分辨
出究竟是属於那一种生物的脚印.
南方有个水池通往海中,而往北方看去有个洞通往地底深处.
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"northdown" : "/d/deathland/main/d3", 
		"south" : "/d/deathland/main/d6" ]) );
	ob->reset();
}
