// File: /d/deathland/main/d3.c
// Generated by Roommaker Thu Nov 23 20:18:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一个很深的洞穴");
	ob->set_long( @LONG_DESCRIPTION
这洞穴像是一直延申到地底去.而风从地底不停地吹上来.地上的足迹越来
越多,也越来越零乱,仔细一看岩壁,似乎覆\盖\著\一层血迹,你了解到这里一定曾
经发生过一场非常大规模的□杀.
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southup" : "/d/deathland/main/d2", 
		"northdown" : "/d/deathland/main/d7" ]) );
	ob->reset();
}
