// File: /d/deathland/main/d6.c
// Generated by Roommaker Thu Nov 23 20:18:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("令人毛骨悚然的地方");
	ob->set_long( @LONG_DESCRIPTION
当你游进这洞穴中时,你的心灵忽然充满了毛骨悚然的感觉.
一些残骸在水中飘浮著,使你想尽快离开水中
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"out" : "/d/deathland/main/d4", 
		"north" : "/d/deathland/main/d2" ]) );
	ob->set( "objects", ([ 
		"octpus" : "/d/deathland/monster/octpus" ]) );
	ob->set( "underwater", 1 );
	ob->reset();
}
