// File: /d/deathland/main/d8.c
// Generated by Roommaker Thu Nov 23 20:16:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深渊的南边");
	ob->set_long( @LONG_DESCRIPTION
从这往北看去,有一个非常大,又非常深的深渊横在你的面前,似乎让人觉得它
就是通往地狱的入口.虽然你目前是处在地底的深处, 但是你仍然能看清附近的地
形地物,这个地方十分的空旷,往东方看似乎有几个帐篷,但是你无法确定. 往西看
去一片死寂,你无法清晰的看见任何事物.而南边是一往上的斜坡.
    风不停地由深渊(Abyss)吹上来,一不小心你将摔入这地狱的入口.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/deathland/main/d7", 
		"east" : "/d/deathland/main/d9", 
		"west" : "/d/deathland/main/d10" ]) );
	ob->set( "item_desc", ([ 
		"abyss" : "一个非常大,又非常深的深渊.似乎它是通往地狱的捷径.\n" ]) );
	ob->reset();
}
