// File: /d/deathland/main/d9.c
// Generated by Roommaker Thu Nov 23 20:17:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深渊南方");
	ob->set_long( @LONG_DESCRIPTION
从这往北看去,有一个非常大,又非常深的深渊横在你的面前,似乎让人觉得它就
是通往地狱的入口.往东方看有几个帐篷( tents ),你相信应该有一些生物住在那儿
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/main/d11", 
		"west" : "/d/deathland/main/d8" ]) );
	ob->set( "item_desc", ([ 
		"tents" : "几个很大的帐蓬.\n" ]) );
	ob->reset();
}
