// File: /d/eastland/saulin_temple/back_temple.c
// Generated by Roommaker Wed Nov 22 22:57:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("後殿");
	ob->set_long( @LONG_DESCRIPTION
空空汤汤的一座大殿，除了正中供奉的释迦牟尼佛外，几乎是别无长物，
这里的地面光亮如镜，好像常常有一大群人坐在地上似的，也许\这里是少林
僧人参禅打座的地方，不过现在却是一片死寂。南北方各是一条长廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/hallway22", 
		"south" : "/d/eastland/saulin_temple/hallway12" ]) );
	ob->reset();
}
