// File: /d/eastland/saulin_temple/boro_room2.c
// Generated by Roommaker Wed Nov 22 23:07:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院 问剑厅");
	ob->set_long( @LONG_DESCRIPTION
进入这里後，你只能看见一道道的剑光此起彼落，有时撞击声绵密漫长
，有时却良久无声。这里是少林弟子回山之後向前辈讨教江湖上名门大派剑
法的地方，所以在这里的试剑者都是一等一的高手。虽然少林弟子鲜少用剑
，但是少林寺却一直不缺俗家剑法高手，问剑厅实在功\不可没。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/boro_temple" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/yan_guan" ]) );
	ob->reset();
}
