// File: /d/eastland/saulin_temple/boro_room1.c
// Generated by Roommaker Wed Nov 22 23:07:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院 试掌厅");
	ob->set_long( @LONG_DESCRIPTION
进入这里後，你只能看见一对对精光闪烁的眼睛此起彼落，呼呼的拳劲
掌风在这狭小的石室中翻腾，然而却听不到一点人声，这里是少林弟子回山
之後向前辈讨教江湖上名门大派掌法\的地方，所以在这里的试掌者都是一等
一的高手。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/boro_temple" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/monk_su1" ]) );
	ob->reset();
}
