// File: /d/eastland/saulin_temple/boro_temple.c
// Generated by Roommaker Wed Nov 22 23:07:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院");
	ob->set_long( @LONG_DESCRIPTION
般若堂是少林寺专门研究各门各派武学的所在，少林武功\得享盛名千年，
除了人才辈出外，能够知己知彼也是制胜之因，现在堂中有许\多老僧正在静思
，随便打扰他们绝对不是什麽好玩的事情。南北方各有一间黑摸摸的小室，门
外是一片树林。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/forest9", 
		"north" : "/d/eastland/saulin_temple/boro_room2", 
		"south" : "/d/eastland/saulin_temple/boro_room1" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/shi" ]) );
	ob->reset();
}
