// File: /d/eastland/saulin_temple/classroom.c
// Generated by Roommaker Wed Nov 22 23:10:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("讲经堂");
	ob->set_long( @LONG_DESCRIPTION
你走进一座宽大的厅堂，堂中此刻正坐满了人，每个人都聚精会神的
听著堂上一名老僧说法，还有人不时在佛经上、衣服上、等等只要是可以
写字的地方做著笔记。虽然堂上拥挤不堪的坐满了人，可是除了老僧的宏
道说法和沙沙的书写声外，竟是半点杂声也无。西方是一条走廊，东方有
一条小径。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/stone_path2", 
		"west" : "/d/eastland/saulin_temple/hallway22" ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkb" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkc" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkd" : "/d/eastland/saulin_temple/monster/meditate_monk" ]) );
	ob->reset();
}
