// File: /d/eastland/saulin_temple/damo_temple.c
// Generated by Roommaker Wed Nov 22 23:29:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("达摩院");
	ob->set_long( @LONG_DESCRIPTION
走进达摩院，你一眼就被院中的大菩提树吸引，树下正有许\多老僧正
在入定，院内各处还有几名年轻僧人在低头沉思，偶而起身摆\弄一些奇怪
的姿势。达摩院是少林寺发扬本身基本武学的地方，据闻院内诸僧无不身
兼数项绝技，在这里撒野的人一定讨不了好的去。南北方各有一座小殿，
门外则是一片宁静的树林。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/forest11", 
		"south" : "/d/eastland/saulin_temple/damo_room2", 
		"north" : "/d/eastland/saulin_temple/damo_room1" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/shu_du" ]) );
	ob->reset();
}
