// File: /d/eastland/saulin_temple/damo_room2.c
// Generated by Roommaker Wed Nov 22 23:29:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("达摩院 见性堂");
	ob->set_long( @LONG_DESCRIPTION
走进这里，只见好几个年轻和尚在已经被磨的光亮的青石地上摆\弄著
各种奇特的姿势，或似狼踞、似猿呼，或似鸟伸、似鹤展，这些就是少林
内功\中的动功\，专心致志的他们使得这里像极了一座蜡像馆，你不禁有些
毛骨悚然。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/damo_temple" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/monk" ]) );
	ob->reset();
}
