// File: /d/eastland/saulin_temple/enforce_room2.c
// Generated by Roommaker Wed Nov 22 23:25:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("戒性堂");
	ob->set_long( @LONG_DESCRIPTION
你走进一个小小的石室，除了一尊达摩祖师像外，室内别无一物
，有几名少林弟子正背著你端坐面壁静思，阵阵低沈的诵经声使得你
昏昏欲睡，你不禁想赶快离开这个沈闷的地方。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/enforce_temple" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/enforcer" ]) );
	ob->reset();
}
