// File: /d/eastland/saulin_temple/farm4.c
// Generated by Roommaker Wed Nov 22 23:12:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("菜园");
	ob->set_long( @LONG_DESCRIPTION
这里是一片宽阔的菜园，园中此刻正有许\多僧人和长工在工作著，
这些田地都是少林寺的庙产，所收成的五谷\蔬果除了能自给自足外还能
卖给批发商，当然，所有的庙产盈馀都是用於济助四乡贫民。菜园的东
边有一口山泉(spring)，僧人们正把泉水引进园中灌溉。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/farm3", 
		"south" : "/d/eastland/saulin_temple/farm2" ]) );
	ob->set( "item_desc", ([ 
		"spring" : @LONG_TEXT
这是一口清澈的山泉，冷洌的泉水正汹涌的从泉眼喷出，在僧人筑成的
护堤内汇成一个大池，不断冒出的泉水从堤口流出，僧人们引著这些水
作为灌溉以及日常生活用水。当然，你也可以试试这纯天然涌出的矿泉
水，不过你得先找到装水的瓢儿(gourd)。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/serv_monk" ]) );
	ob->set( "water_source", 1 );
	ob->reset();
}
