// File: /d/eastland/saulin_temple/forest1.c
// Generated by Roommaker Wed Nov 22 23:14:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的废弃小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条小径上，覆满枯\叶的小径显示已经有许\久没有人走过这里
了，习习的微风穿过林梢向你吹来，只有寂寂的四周虫鸣鸟啼和野花飘香，
远方好像有一角屋檐在林影间闪动。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/doshy_temple", 
		"northeast" : "/d/eastland/saulin_temple/left_path2" ]) );
	ob->set( "objects", ([ 
		"fox2" : "/d/eastland/saulin_temple/monster/wild_fox", 
		"fox1" : "/d/eastland/saulin_temple/monster/wild_fox" ]) );
	ob->reset();
}
