// File: /d/eastland/saulin_temple/forest10.c
// Generated by Roommaker Wed Nov 22 23:08:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条小径上，洁净的小径显示经常有人走过这里，习习的微风
穿过林梢向你吹来，只有寂寂的四周虫鸣鸟啼和野花飘香，小径向北方和
南方蜿蜒而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/forest9", 
		"north" : "/d/eastland/saulin_temple/forest11" ]) );
	ob->set( "objects", ([ 
		"fly2" : "/d/noden/monster/spider", 
		"fly" : "/d/noden/monster/spider" ]) );
	ob->reset();
}
