// File: /d/eastland/saulin_temple/front_square6.c
// Generated by Roommaker Wed Nov 22 23:32:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("广场");
	ob->set_long( @LONG_DESCRIPTION
这是一片用石板铺成的大广场，每个石板的中间都凹了下去，远远望去
好像水面上的波纹，十分的壮观。另外场边还摆\著许\多的兵器，看来此处是
少林寺三千武僧练武的地方。此处的北边和东边有一些殿堂，西边和南边则
是一望无际的广场。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/front_square4", 
		"south" : "/d/eastland/saulin_temple/front_square3", 
		"north" : "/d/eastland/saulin_temple/side_temple2", 
		"west" : "/d/eastland/saulin_temple/front_square5" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/bonze" ]) );
	ob->reset();
}
