// File: /d/eastland/saulin_temple/grass2.c
// Generated by Roommaker Wed Nov 22 23:01:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条黄土小径上，四周都是松林，除了山风吹掠、虫鸣鸟啼外，没
有一点尘俗杂音，阴凉幽静的森林气息深深的迷醉每一颗来自俗世尘嚣的心，
你顿时放下世俗的一切种种牵绊，放开心胸来体会这份难得的自然之美。东南
方各有一条小径，北方则是十八铜人阵阵门。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/grass1", 
		"south" : "/d/eastland/saulin_temple/grass3", 
		"north" : "/d/eastland/saulin_temple/entrance" ]) );
	ob->reset();
}
