// File: /d/eastland/saulin_temple/grass3.c
// Generated by Roommaker Wed Nov 22 23:00:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条黄土小径上，四周都是松林，除了山风吹掠、虫鸣鸟啼外，没
有一点尘俗杂音，阴凉幽静的森林气息深深的迷醉每一颗来自俗世尘嚣的心，
你顿时放下世俗的一切种种牵绊，放开心胸来体会这份难得的自然之美。南北
方各有一条小径，东方是塔林，西方则是碑林。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/towers1", 
		"south" : "/d/eastland/saulin_temple/grass4", 
		"west" : "/d/eastland/saulin_temple/tomb_stones1", 
		"north" : "/d/eastland/saulin_temple/grass2" ]) );
	ob->reset();
}
