// File: /d/eastland/saulin_temple/guess_house1.c
// Generated by Roommaker Wed Nov 22 23:36:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("客房");
	ob->set_long( @LONG_DESCRIPTION
走进这个房间，一阵清新的檀香味迎面而来，这里是专供香客歇脚挂
单的客房，两侧宽敞的大通铺上此刻正稀稀落落的坐著躺著一些休息的香
客，门口有几名服事僧垂手低眉而立，等著接受香客们的差遣。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/stone_path0" ]) );
	ob->set( "objects", ([ 
		"guestb" : "/d/eastland/saulin_temple/monster/guest", 
		"monk" : "/d/eastland/saulin_temple/monster/serv_monk", 
		"guesta" : "/d/eastland/saulin_temple/monster/guest" ]) );
	ob->reset();
}
