// File: /d/eastland/saulin_temple/hallway1.c
// Generated by Roommaker Wed Nov 22 22:51:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊");
	ob->set_long( @LONG_DESCRIPTION
你走在一条长廊上，两旁都是庭台堂芜，廊上僧人来往香客如织，挤的
根本没有心情去欣赏四周的环境。少林寺号称千廊百院，像这样的长廊不知
有多少，你可得小心迷路。南方是一条穿堂，长廊往东方延伸而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway2", 
		"south" : "/d/eastland/saulin_temple/hallway0" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/hwei_lin" ]) );
	ob->reset();
}
