// File: /d/eastland/saulin_temple/hallway22.c
// Generated by Roommaker Wed Nov 22 22:56:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊");
	ob->set_long( @LONG_DESCRIPTION
你走在一条长廊上，两旁都是庭台堂芜，廊上僧人来往香客如织，挤的
根本没有心情去欣赏四周的环境。少林寺号称千廊百院，像这样的长廊不知
有多少，你可得小心迷路。北方是一条石阶小径，南方是後殿，东方是讲经
堂，西方则是普贤院。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/classroom", 
		"west" : "/d/eastland/saulin_temple/pusan_temple", 
		"south" : "/d/eastland/saulin_temple/back_temple", 
		"north" : "/d/eastland/saulin_temple/stone_path1" ]) );
	ob->reset();
}
