// File: /d/eastland/saulin_temple/hallway0.c
// Generated by Roommaker Wed Nov 22 22:55:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("穿堂");
	ob->set_long( @LONG_DESCRIPTION
你走在一条长廊上，两旁都是庭台堂芜，廊上僧人来往香客如织，挤的
根本没有心情去欣赏四周的环境少林寺号称千廊百院，像这样的长廊不知有
多少，你可得小心迷路。向北向西各有一条走廊，南方则是大殿，长廊两旁
门户重叠，不知道通往什麽地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/main_temple3", 
		"north" : "/d/eastland/saulin_temple/hallway1", 
		"west" : "/d/eastland/saulin_temple/hallway21" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"mobs" : "/d/eastland/saulin_temple/monster/yang_win" ]) );
	ob->reset();
}
