// File: /d/eastland/saulin_temple/herb_room.c
// Generated by Roommaker Wed Nov 22 23:37:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("药阁");
	ob->set_long( @LONG_DESCRIPTION
踏进这里，一阵浓郁的药草香扑鼻而来，这里是少林寺贮藏药物的
地方，一格格的木柜放置的各种不同的药草，层层叠叠地直堆到屋顶。
虽然这里贵重的药物很多，但是有毒的也不少，所以除非有精通药物学
的人代劳，否则最好不要乱打这些药草的主意。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/herb_field", 
		"west" : "/d/eastland/saulin_temple/plaster_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/herb_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/herb_monk" ]) );
	ob->reset();
}
