// File: /d/eastland/saulin_temple/left_path1.c
// Generated by Roommaker Wed Nov 22 23:16:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条青石小径上，磨损得圆润光华的石径无言的对你夸耀
少林寺的悠久历史。清风习习四下寂寂，只有虫鸣鸟啼和野花飘香，
和少林寺的其他部份比起来，这里就像世外桃源一样。小径一直向东
西方而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway18", 
		"west" : "/d/eastland/saulin_temple/left_path2" ]) );
	ob->reset();
}
