// File: /d/eastland/saulin_temple/left_path2.c
// Generated by Roommaker Wed Nov 22 23:14:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("三叉小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条青石小径上，磨损得圆润光华的石径无言的对你夸耀
少林寺的悠久历史。清风习习四下寂寂，只有虫鸣鸟啼和野花飘香，
和少林寺的其他部份比起来，这里就像世外桃源一样。小径在此处分
向西南和西北而去，西南方看似有一座森林。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/saulin_temple/forest1", 
		"northwest" : "/d/eastland/saulin_temple/forest2", 
		"east" : "/d/eastland/saulin_temple/left_path1" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/hwei_ti" ]) );
	ob->reset();
}
