// File: /d/eastland/saulin_temple/main_temple1.c
// Generated by Roommaker Wed Nov 22 23:32:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大雄宝殿前厅石阶");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了一处石阶前，你的目光被前方雄伟的石柱(stonehenge)所吸引。
你仰头望去，高耸的横梁上挂著一块匾额，上面用苍劲有力的字体写著——大雄
宝殿。往北看去就是大雄宝殿的前厅，这里庄严肃穆的气氛让你的心情不由得严
肃起来。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/side_temple2", 
		"south" : "/d/eastland/saulin_temple/front_square5", 
		"west" : "/d/eastland/saulin_temple/side_temple1", 
		"north" : "/d/eastland/saulin_temple/main_temple2" ]) );
	ob->set( "item_desc", ([ 
		"stonehenge" : "这是一根十分巨大的石柱，上面好像有雕刻，可惜距离太远看不清楚。\n" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
