// File: /d/eastland/saulin_temple/plaster_temple.c
// Generated by Roommaker Wed Nov 22 23:37:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("药王殿");
	ob->set_long( @LONG_DESCRIPTION
这里是供奉药王菩萨的地方，同时也是寺僧看病医疗的所在，这里的掌药
师父同时也是医道高深的医生，小如热感风寒、跌打损伤，大至毒痈肿瘤，他
们都能妥善处理，当然，这里也施医施药，不过如果方便的话，求药的香客最
好还是捐点香油钱。你可以问掌药师父目前殿内的药物的种类。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/herb_room", 
		"north" : "/d/eastland/saulin_temple/hallway4" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/heal_monk" ]) );
	ob->reset();
}
