// File: /d/eastland/saulin_temple/pusan_temple.c
// Generated by Roommaker Wed Nov 22 23:27:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("普贤院");
	ob->set_long( @LONG_DESCRIPTION
走进这个充满彩绘壁画的小院，你几乎忽略了正堂供奉的普贤菩萨，骑
著白象的普贤菩萨现在看起来好像有些苦恼，不知道在烦些什麽？你突然注
意到墙上(wall)的壁画空了一块，难怪怎麽看都不对劲。西方是雨花院，东
方则是一条走廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway22", 
		"west" : "/d/eastland/saulin_temple/rain_temple" ]) );
	ob->set( "item_desc", ([ 
		"elephant" : "看什麽？大象都跑了! 只留下白白的一块了!\n", 
		"pushan" : @LONG_TEXT
你看著普贤菩萨的画像，突然，普贤菩萨开口说话了: 
  唉! 我那头孽畜不知道跑到哪里去了，待会佛祖查问起来，我可如何是好？如
  果你能帮我找到它，一定要替我狠狠地教训它，这样就能把它逼回来。还有，
  劣骑的三昧真火极强，如果还没找到克制它的方法，最好不要去惹它。
LONG_TEXT
, 
		"wall" : @LONG_TEXT
这是一面充满了绚丽彩画的墙壁，画中描述南无释迦牟尼会见弟子，诸天诸佛齐
来朝拜，十八罗汉及八部天龙在两旁护法，文殊菩萨骑著青狮、普贤(Pushan)菩
萨骑著 .... 咦？他的白象(elephant)呢？
LONG_TEXT
 ]) );
	ob->reset();
}
