// File: /d/eastland/saulin_temple/right_path2.c
// Generated by Roommaker Wed Nov 22 23:40:52 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("三叉小径");
	ob->set_long( @LONG_DESCRIPTION
你走在一条青石小径上，磨损得圆润光华的石径无言的对你夸耀
少林寺的悠久历史。清风习习四下寂寂，只有虫鸣鸟啼和野花飘香，
和少林寺的其他部份比起来，这里就像世外桃源一样。小径在此处分
向东南和东北而去，东南方看似有一座大殿。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/right_path1", 
		"southeast" : "/d/eastland/saulin_temple/white_temple", 
		"northeast" : "/d/eastland/saulin_temple/forest8" ]) );
	ob->reset();
}
