// File: /d/eastland/saulin_temple/river_side1.c
// Generated by Roommaker Wed Nov 22 23:09:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林缘草地");
	ob->set_long( @LONG_DESCRIPTION
你走在一片草地上，北方是一片松林，除了山风吹掠、虫鸣鸟啼外，没
有一点尘俗杂音，阴凉幽静的森林气息深深的迷醉每一颗来自俗世尘嚣的心
，你顿时放下世俗的一切种种牵绊，放开心胸来体会这份难得的自然之美。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/river_side3", 
		"south" : "/d/eastland/saulin_temple/stone_path2" ]) );
	ob->reset();
}
