// File: /d/eastland/saulin_temple/road1.c
// Generated by Roommaker Wed Nov 22 23:38:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山脚下");
	ob->set_long( @LONG_DESCRIPTION
此处位於少室山的山脚下，附近都是连绵不绝的高山，你的眼前有一条
用云石铺设成的石阶盘旋上山颠，山顶似乎有一群建筑物，可惜距离太远你
看不清是何种建筑物。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/saulin_temple/road2", 
		"north" : "/d/eastland/2,8.east" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
