// File: /d/eastland/saulin_temple/road2.c
// Generated by Roommaker Wed Nov 22 23:38:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山下");
	ob->set_long( @LONG_DESCRIPTION
此处位於少室山的山下，附近都是连绵不绝的高山，你正站在一条用
云石铺设成的石阶上，你的四周都是苍苍老松，把此处点缀的绿意盎然，
而繁花千万更显活泼生气，远处山顶似乎有一群建筑物，可惜距离太远你
看不清是何种建筑。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/saulin_temple/road1", 
		"up" : "/d/eastland/saulin_temple/road3" ]) );
	ob->set( "objects", ([ 
		"guest" : "/d/eastland/saulin_temple/monster/guest" ]) );
	ob->reset();
}
