// File: /d/eastland/saulin_temple/road4.c
// Generated by Roommaker Wed Nov 22 23:39:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腰");
	ob->set_long( @LONG_DESCRIPTION
此处位於少室山的山腰，在你的上方少林寺的山门雄伟的矗立著。此
刻你位於一条用云石铺设成的石阶上，的四周都是苍苍老松，把此处点缀
的绿意盎然，而繁花万千更显生气活泼。 
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/saulin_temple/road3", 
		"up" : "/d/eastland/saulin_temple/gate" ]) );
	ob->set( "objects", ([ 
		"fighter" : "/d/eastland/saulin_temple/monster/barbarian" ]) );
	ob->reset();
}
