// File: /d/eastland/saulin_temple/side_temple1.c
// Generated by Roommaker Wed Nov 22 23:32:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("偏殿");
	ob->set_long( @LONG_DESCRIPTION
这里是偏殿，宽阔的殿堂中列著一排排的架子，架上则点著由各地善男
信女所奉献的长明灯，每盏油灯放出的微光，都是世上苦难众生的希望，望
著点点明灯似海如浪，一股肃穆虔诚的感觉油然而生，你不禁也想长跪佛前
，祈求佛祖的导引。往西看去有一座塔楼，东方是大雄宝殿的石阶，南方则
是一片广场。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/main_temple1", 
		"west" : "/d/eastland/saulin_temple/bell_tower", 
		"south" : "/d/eastland/saulin_temple/front_square4" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/staff_monk" ]) );
	ob->reset();
}
