// File: /d/eastland/saulin_temple/small_path1.c
// Generated by Roommaker Wed Nov 22 23:05:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("後山小径");
	ob->set_long( @LONG_DESCRIPTION
这里是少林寺的後山，四周都是青葱苍郁的茂林，到了这里，你已经完全远
离了少林寺中的游人笑语、禅吟佛唱，但在这片可爱的青草地上，却有一些树倒
草掀的破坏痕迹，几个大脚印(footsteps) 踩烂了草皮，直直的往远方的森林迤
洒而去，你可以跟踪脚印去看看到底是哪种庞大的怪物这麽没有公德心。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/small_path2", 
		"south" : "/d/eastland/saulin_temple/tomb_stones4" ]) );
	ob->set( "item_desc", ([ 
		"footsteps" : @LONG_TEXT
你弯下腰去观察地上的脚印。乖乖! 这一定是一头特大号的大象，光看这些脸盆
大的脚印就可以想像它那庞大的身躯! 万一不小心被它压到那就惨了。你确定你
要去找它麻烦吗？ 
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"deer" : "/d/noden/elf/monster/brocket", 
		"deer2" : "/d/noden/elf/monster/brocket" ]) );
	ob->reset();
}
