// File: /d/eastland/saulin_temple/stone_path2.c
// Generated by Roommaker Wed Nov 22 23:09:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石阶小径");
	ob->set_long( @LONG_DESCRIPTION
你走在少林寺内千廊百院间的通道上，磨损得圆润光华的石阶无言的对你
夸耀少林寺的悠久历史。遥望寺外蓊郁松林，寺内黄瓦朱墙，寺僧来去、游客
相接，你不禁有出世之想。西方是讲经堂，东边是藏经阁。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/book_temple1", 
		"north" : "/d/eastland/saulin_temple/river_side1", 
		"south" : "/d/eastland/saulin_temple/river_side2", 
		"west" : "/d/eastland/saulin_temple/classroom" ]) );
	ob->reset();
}
