// File: /d/eastland/saulin_temple/tomb_stones1.c
// Generated by Roommaker Wed Nov 22 23:04:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("碑林");
	ob->set_long( @LONG_DESCRIPTION
这里是少林寺著名的碑林，存放著历代少林所获得的荣誉象徵。每一面
石碑都记录著当代执政者和社会舆论对少林寺的肯定。当然，其中也有一些
少林寺对寺内圆寂高僧的追思，以藉此鼓励後进。不过，站在这麽许\多石碑
当中，一不小心恐怕就会迷路，所以这里平时人迹罕至。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/grass3", 
		"west" : "/d/eastland/saulin_temple/tomb_stones3", 
		"south" : "/d/eastland/saulin_temple/tomb_stones2", 
		"north" : "/d/eastland/saulin_temple/tomb_stones3" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
