// File: /d/eastland/saulin_temple/unsu_room1.c
// Generated by Roommaker Wed Nov 22 23:25:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("文殊院 经堂");
	ob->set_long( @LONG_DESCRIPTION
这里是文殊院的经堂，一部份需要特殊人才解读翻译或是讲解的
西天竺文原经都会先在这里副录抄本後再送到藏经阁典藏，所以这里
也收藏了极为丰富的佛学经典，必要的时候你可以请经堂里的师傅帮
你讲解经中的精义。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/unsu_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/pray_monk" ]) );
	ob->reset();
}
