// File: /d/eastland/saulin_temple/unsu_room2.c
// Generated by Roommaker Wed Nov 22 23:25:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("文殊院 忏堂");
	ob->set_long( @LONG_DESCRIPTION
这里是文殊院的忏堂，凡是寺中僧人觉得心中有所疑惑或是对经文有
所疑问，都可以来这里念经拜忏，以求得内心的平静与对佛法的更深一步
体会。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/unsu_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/pray_monk" ]) );
	ob->reset();
}
