// File: /d/eastland/saulin_temple/white_temple.c
// Generated by Roommaker Wed Nov 22 23:41:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白衣殿");
	ob->set_long( @LONG_DESCRIPTION
进入了白衣殿，迎面而来的就是一座和人等高的白衣大士金身，
慈眉善目的白衣大士双目灵动栩栩如生，好像正在注视你，你的心中
感到一阵肃穆，丝毫不敢轻慢。环顾四壁令你大感兴趣。东边的墙上
有著名的「十三和尚救唐王图」，北边壁上是「心意六合掌谱」，南
边壁上是各种兵器的招式分解图。都是少林的入门武功\。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/eastland/saulin_temple/right_path2" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/hand_monk", 
		"monk2" : "/d/eastland/saulin_temple/monster/hand_monk" ]) );
	ob->reset();
}
