// File: /d/eastland/dragon/cave5.c
// Generated by Roommaker Sat Nov 25 14:00:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("龙穴");
	ob->set_long( @LONG_DESCRIPTION
你发现此处是一个火山熔洞，四周都是奇怪的火红色岩石，并且有时有一些奇怪的
岩石结晶，当其被火光映照之时，会反射出绚丽的光线，加上原有的火红构成一副
优美的景色，令你几乎忘了身在何处。你的前方所传来的腥味越来越浓的，现在每
当你踏出一步，就不禁有毛骨悚然的感觉。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/dragon/cave8", 
		"northeast" : "/d/eastland/dragon/cave3" ]) );
	ob->reset();
}
