// File: /d/eastland/dragon/cave29.c
// Generated by Roommaker Sat Nov 25 14:06:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大户之家");
	ob->set_long( @LONG_DESCRIPTION
这里是一个富丽堂皇的房间，四处都是以黄金沏造成的家具，而地板则是以珍贵的
红珊玉制成，当人踩在其上一种透骨的清凉涌上心头令人神清气爽，天花板则是彩色琉
璃瓦，而由千年麝香鲸油制成的火把中传出一股似有似无的神秘芳香，让你有置身仙境
的感觉，真不愧\是富可敌国的郑大户所摆\出的排场。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave30", 
		"south" : "/d/eastland/dragon/cave27" ]) );
	ob->set( "objects", ([ 
		"man1" : "/d/eastland/dragon/monster/man1" ]) );
	ob->reset();
}
