// File: /d/eastland/dragon/cave36.c
// Generated by Roommaker Sat Nov 25 14:08:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
这是一间十分秀气的房间，因为它里面的摆\饰全部漆以粉红色，当以进入此房间
时你还以为你自己是置身於梦中呢，有一个书桌放在左角，其旁有一个梳□台，其上
有一一面大镜子，左侧则有一张大床，当你靠近它时有阵阵幽香由床上传出，左面墙
上还挂著一些弓箭式的武器，看起来此屋的主人似乎能文能武。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave35" ]) );
	ob->reset();
}
