// File: /d/eastland/dragon/cave12.c
// Generated by Roommaker Sat Nov 25 14:02:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
此处是一个古老的地下城的房间，此处的墙壁及地板都是以大理石铺设成的同时墙上正
有几只火把燃烧著，这房间摆\设简陋，仅有一张木床，一张木桌及几张石椅，但是在屋子的
角落有一堆堆的木材，真不知屋主要这许\多木材来做什麽，也许\是一个樵夫吧!
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/dragon/cave10" ]) );
	ob->set( "objects", ([ 
		"woodman" : "/d/eastland/dragon/monster/woodman" ]) );
	ob->reset();
}
