// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("龙穴");
	set_long( @C_LONG_DESCRIPTION
你已经走完洞窟，来到一个神秘的地方，此处是一个四周都围绕著高山峻岭的山谷
，山谷的的中央有一个漂亮的湖，湖的四周有许多的垂杨，并且遍地鲜花绿草，并且从
此望去天空明晰可见，这里真是个世外桃源，但是有点奇怪的是，这里居然看不到任何
生物的踪迹，真是有点糟蹋此处之美。湖的前方有一座祭坛，并且它的右方有一巨鼓。
C_LONG_DESCRIPTION
	);
	set("beat_control",1);
	set_outside("dragoncave");
	set( "light", 1 );
	set( "exits", ([
		"east" : Lcave"cave21"
	]) );
	reset();
#include <replace_room.h>
}
