// File: /d/noden/hawk/crack1.c
// Generated by Roommaker Mon Dec  4 21:08:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你现在正站在一个狭窄的洞穴中，一条恰可容纳一个人通过的裂缝从外面透进
一些昏暗的光线，这个洞穴很窄，但是你发现洞穴的顶端有一块可供攀爬的岩石突
出，只要你稍微一跳就够得著，洞穴往下是一条更大的裂缝，里面黑漆漆的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"out" : "/d/noden/hawk/clearing", 
		"down" : "/d/noden/hawk/crack3", 
		"up" : "/d/noden/hawk/crack2" ]) );
	ob->set( "objects", ([ 
		"worm#1" : "/d/noden/hawk/monster/cave_worm", 
		"worm#2" : "/d/noden/hawk/monster/cave_worm" ]) );
	ob->reset();
}
