// File: /d/noden/hawk/dungeon.c
// Generated by Roommaker Mon Dec  4 21:11:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地牢");
	ob->set_long( @LONG_DESCRIPTION
你现在位於一个阴暗潮湿的地牢中，地上水深及膝，而且还发出恶臭，四周都是
长满青苔(moss)的坚硬岩石，北边的墙壁上有一个铜环(ring)嵌在你头上约两公尺的
地方，你听见一阵吱吱的叫声从西边的墙壁(wall)後面传出。
LONG_DESCRIPTION
	);

	ob->set( "item_desc", ([ 
		"ring" : @LONG_TEXT
这个铜环上面长满了恶心的铜绿，看起来像是某种机关的控制开关，不过离你
太远了，拉不到....
LONG_TEXT
, 
		"moss" : @LONG_TEXT
这些青苔不知道是什麽突变种，长得像小草一般高，有些顶端甚至还有一些像
花朵一样的红叶片(leaves)。
LONG_TEXT
, 
		"wall" : @LONG_TEXT
这些墙壁看起来都十分坚硬，你敲打西边的墙壁，声音听起来不太一样，也许这个
方向有什麽密门或机关。
LONG_TEXT
 ]) );
	ob->reset();
}
