// File: /d/noden/hawk/path1.c
// Generated by Roommaker Mon Dec  4 21:10:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条崎岖的山路上，往东北边下坡处是一片长著疏落青草的平原
矮丘，往南是一条上山的石阶坡道，这里的山路并不是很宽，只能容纳两个人并肩
而行，东边是深不见底的深谷，西边则是几乎直立的峭壁，山谷深处传来阵阵「呜
....呜....」的叫声，不知道是什麽东西。
LONG_DESCRIPTION
	);

	ob->set_outside( "hawk" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/hawk/path2", 
		"northeast" : "/d/noden/10,10.noden" ]) );
	ob->set( "objects", ([ 
		"scout#2" : "/d/noden/hawk/monster/scout", 
		"scout#1" : "/d/noden/hawk/monster/scout" ]) );
	ob->reset();
}
