// File: /d/noden/hawk/room2-17.c
// Generated by Roommaker Mon Sep 30 14:39:08 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("中央大道");
	ob->set_long( @LONG_DESCRIPTION
你继续走在内城的道路上，观察鸟人们所建筑的房子，发现大部份比较雄
伟的屋子都是颇新的，而老旧的房子则都是破破烂烂的，但是还是很多人住，
而较新较好的房子反而空空荡荡，或许是鸟人天性喜欢住在比较简陋的房子
吧....但不知道为什麽会多出这些新建筑呢？
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/hawk/room2-16", 
		"northeast" : "/d/noden/hawk/room2-19" ]) );
	ob->reset();
}
