// File: /d/noden/hawk/room1-13.c
// Generated by Roommaker Mon Sep 30 10:32:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("贫民窟");
	ob->set_long( @LONG_DESCRIPTION
这里是天空之城里最灰暗的角落。由於战争的因素，鸟人们过份的重视战
斗能力的高低，因此许多年迈的老战士们就失去了赖以为生的依据，如果没有
亲人供养的，最後的下场通常是来到这贫民窟渡过馀生。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room1-12", 
		"southeast" : "/d/noden/hawk/room1-14" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/noden/hawk/monster/older" ]) );
	ob->reset();
}
