// File: /d/noden/hawk/room2-13.c
// Generated by Roommaker Mon Sep 30 14:38:31 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("中央大道");
	ob->set_long( @LONG_DESCRIPTION
你走在内城最宽广的中央大道，你可以看到许许多多的鸟人或飞行在空中，
或走在道路上。但是他们都用怀疑的眼神看著你，当你想上前与他们攀谈的时候
，更是躲你躲的远远的，真不知道为什麽他们会这样排斥你。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room2-11", 
		"southeast" : "/d/noden/hawk/room2-14" ]) );
	ob->set( "objects", ([ 
		"man" : "/d/noden/hawk/monster/man", 
		"woman" : "/d/noden/hawk/monster/woman" ]) );
	ob->reset();
}
