// File: /d/noden/hawk/room1-20.c
// Generated by Roommaker Mon Sep 30 10:32:27 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小屋");
	ob->set_long( @LONG_DESCRIPTION
这是一间装饰很简陋的小屋，不过打扫的满乾净的，而且摆设也满有
格调的，或许在这居住的是一位很有气质的人唷。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/noden/hawk/room1-14" ]) );
	ob->set( "objects", ([ 
		"war" : "/d/noden/hawk/monster/bernice" ]) );
	ob->reset();
}
