// File: /d/noden/hawk/room2-15.c
// Generated by Roommaker Mon Sep 30 14:38:50 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("内城中心");
	ob->set_long( @LONG_DESCRIPTION
你现在站在天空之城内城的中心，雄伟高耸的建筑物代表了鸟人族科技
工业与建筑技术的高明，两侧楼房排列的整整齐齐，不过最引起你注意的是
这些房子都没有门。当你正在怀疑的时候，你看到几只鸟人从墙上的大窗户
飞了出来，才让你恍然大悟。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/hawk/room1-9", 
		"north" : "/d/noden/hawk/room2-14" ]) );
	ob->reset();
}
