// File: /d/noden/hawk/room2-19.c
// Generated by Roommaker Mon Sep 30 14:39:18 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("军备战用道路");
	ob->set_long( @LONG_DESCRIPTION
离开了中央大道，你又开始感到一股沉重的压力，往来的人潮变少了，但是
却多了来来往往巡逻的士兵。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/room2-17", 
		"northup" : "/d/noden/hawk/room2-21" ]) );
	ob->reset();
}
