// File: /d/noden/hawk/room2-2.c
// Generated by Roommaker Mon Sep 30 14:33:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("碧玉森林");
	ob->set_long( @LONG_DESCRIPTION
这里是鸟人族人最引以自豪的碧玉森林，所有的树干都泛著淡绿色的光
茫，又彷佛可以直视入树干的内部。这种树即使是如你一般见闻广博的旅行
家也是前所未见的。树林里更弥漫著一股淡淡的香味，更是让你留连忘返。
树梢上开满了许多翠绿色的花朵(flower)，同时也有不少的果实(fruit) ，　
看起来很好吃的样子。　
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"fruit" : "饱满的紫色果子，你想要吃一口吗？\n", 
		"flower" : "淡绿色的花朵，同时又散发出淡淡的香味。\n" ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room2-4" ]) );
	ob->set( "objects", ([ 
		"injured" : "/d/noden/hawk/monster/injured" ]) );
	ob->reset();
}
