// File: /d/noden/hawk/room1-19.c
// Generated by Roommaker Mon Sep 30 10:33:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("军营哨站");
	ob->set_long( @LONG_DESCRIPTION
鸟人族的军营，你可以看到很多年轻的士兵们在这里努力的锻练自己的武
艺，希望能慢慢的提升自己的地位，也因此整栋建筑里充满了汗臭味和吆喝的
声音。外面则是一高耸的小塔台，上面站了个哨兵，负责观察敌人的动向。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/hawk/room1-12" ]) );
	ob->set( "objects", ([ 
		"soldier" : "/d/noden/hawk/monster/soldier", 
		"scout" : "/d/noden/hawk/monster/scout", 
		"soldier1" : "/d/noden/hawk/monster/soldier" ]) );
	ob->reset();
}
