// File: /d/noden/hawk/room1-16.c
// Generated by Roommaker Mon Sep 30 10:31:55 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("光辉森林");
	ob->set_long( @LONG_DESCRIPTION
名虽曰光辉森林，不过你看了半天还是不知道这森林有啥特别的地方，让你
觉得有受骗了的感觉。四处晃晃，你突然觉得这里的空气远比外面新鲜多了，让
你感到身心舒爽，精神也好多了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/hawk/room1-15", 
		"northeast" : "/d/noden/hawk/room1-17" ]) );
	ob->reset();
}
