// File: /d/noden/hawk/room2-10.c
// Generated by Roommaker Mon Sep 30 14:37:18 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("内城观察哨");
	ob->set_long( @LONG_DESCRIPTION
这里是整个天空之城最高的地方，因此也派有数名眼力极佳哨兵负责观察，
眼尖的你发现了东边有一个淡绿色的雾团，不知道那是啥东东。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/hawk/room2-21", 
		"southdown" : "/d/noden/hawk/room2-8" ]) );
	ob->set( "objects", ([ 
		"sentry" : "/d/noden/hawk/monster/scout", 
		"sentry2" : "/d/noden/hawk/monster/scout" ]) );
	ob->reset();
}
