// File: /d/noden/hawk/room1-15.c
// Generated by Roommaker Mon Sep 30 10:32:13 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小公园");
	ob->set_long( @LONG_DESCRIPTION
一个小小脏脏的公园，是这些老人闲来无事时聊天闲晃的地方，你可以看到
不少年老力衰的鸟人在这边聊天。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/hawk/room1-14", 
		"east" : "/d/noden/hawk/room1-16" ]) );
	ob->set( "objects", ([ 
		"older3" : "/d/noden/hawk/monster/older", 
		"older1" : "/d/noden/hawk/monster/older", 
		"oldera" : "/d/noden/hawk/monster/older1", 
		"older2" : "/d/noden/hawk/monster/older" ]) );
	ob->reset();
}
