// File: /d/noden/hawk/room2-21.c
// Generated by Roommaker Mon Sep 30 14:39:28 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("内城观察哨");
	ob->set_long( @LONG_DESCRIPTION
这里是整个天空之城最高的地方，因此也派有数名眼力极佳哨兵负责观察，
眼尖的你发现了西边有一个淡绿色的雾团，不知道那是啥东东。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southdown" : "/d/noden/hawk/room2-19", 
		"west" : "/d/noden/hawk/room2-10" ]) );
	ob->set( "objects", ([ 
		"sentry" : "/d/noden/hawk/monster/scout", 
		"sentry2" : "/d/noden/hawk/monster/scout" ]) );
	ob->reset();
}
