// File: /d/noden/hawk/room2-14.c
// Generated by Roommaker Mon Sep 30 14:38:39 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("市政大厅");
	ob->set_long( @LONG_DESCRIPTION
映在你眼前的是天空之城的行政中心，鸟人族平常聚会商议事情就是在这边举
行，你可以看到许多强壮的士兵守护在这里。往上就可以进入市政大厅，你可以进
去参观参观，说不定可以看到一些奇奇怪怪的东西。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/hawk/room2-13", 
		"south" : "/d/noden/hawk/room2-15", 
		"up" : "/d/noden/hawk/room3-1", 
		"northeast" : "/d/noden/hawk/room2-16" ]) );
	ob->reset();
}
