// File: /d/noden/hawk/room3-6.c
// Generated by Roommaker Mon Sep 30 14:41:43 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("领袖办公室");
	ob->set_long( @LONG_DESCRIPTION
鸟人族历代领袖所居住的地方，因此墙边放满了许许多多的兵器，都是
以往的领袖所使用的神兵利器和具有强大防护力的铠甲，不过这边戒备森严
，劝你还是不要图谋不轨。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room3-1" ]) );
	ob->set( "objects", ([ 
		"leader" : "/d/noden/hawk/monster/adolph" ]) );
	ob->reset();
}
