// File: /d/noden/hawk/room2-8.c
// Generated by Roommaker Mon Sep 30 14:37:05 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("军备战用道路");
	ob->set_long( @LONG_DESCRIPTION
走到了这里，你又开始感到一股沉重的压力，往来的人潮变少了，但是
却多了来来往往巡逻的士兵，戒备森严的气氛让你感到浑身不自在。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/room2-7", 
		"northup" : "/d/noden/hawk/room2-10", 
		"southeast" : "/d/noden/hawk/room2-11" ]) );
	ob->set( "objects", ([ 
		"soldier3" : "/d/noden/hawk/monster/fighter", 
		"soldier" : "/d/noden/hawk/monster/soldier", 
		"soldier2" : "/d/noden/hawk/monster/soldier" ]) );
	ob->reset();
}
