// File: /d/noden/hawk/altar2.c
// Generated by Roommaker Sun Jan  9 07:54:22 1994

#include <mudlib.h>
#include "hawk.h"
inherit ROOM;

void create()
{
        object pontiff;

        ::create();
        set_short("圆形祭坛");
        set_long( @C_LONG_DESCRIPTION
你现在来到了一个圆形的大祭坛，祭坛中央有一个圆形的洞穴(pit)，在洞穴四周
散布著六个石桌(table)，最大的一个石桌上放著一个三角锥(prymaid)，环绕著祭坛总
共有二十四根白色石柱(pillars)，祭坛的东、北、西三个方向都被极高的悬崖峭壁所
绕，往南是一片空地。
C_LONG_DESCRIPTION
        );

        set_outside( "hawk" );
        set( "item_desc", ([
                "table" : "这些石桌有大有小，全部都是圆形，似乎是某种魔法阵的装置。\n",
                "prymaid" : @LONG_TEXT
这个三角锥是透明的，但又不是水晶或玻璃做的，它的一个平面正对著东方
太阳升起的地方，祭坛四周二十四根石柱的影子映在三角锥内部，似乎排列
成什麽符号 ....
LONG_TEXT
,
                "pillars" : @LONG_TEXT
这些石柱都是大理石做成的，有高有低，有粗有细，不知道当初建造这些石柱
的人为什麽要把它们做成这样，难道有什麽机关 ....
LONG_TEXT
,
                "pit" : @LONG_TEXT
这个洞穴深不见底，跳(jump)下去不知道会有什麽後果？你似乎隐约听到洞穴
底部传来一阵女人哭泣的呜咽声。
LONG_TEXT
 ]) );
        set( "exits", ([
                "south" : "/d/noden/hawk/altar1" ]) );

        // pontiff is unique, one reboot one pontiff
        pontiff = new( MOB"pontiff");
        pontiff->move(this_object());

        set( "objects", ([
                "guard#1": "/d/noden/hawk/monster/altar_guard",
                "guard#2": "/d/noden/hawk/monster/altar_guard",
                "guard#3": "/d/noden/hawk/monster/altar_guard" ]) );

        reset();
}

//int clean_up()
//{

//      return 0;
//}

void init()
{
        if( this_player() ) this_player()->set_explore("noden#23");
        add_action("do_jump","jump");
        add_action("put_misc", "put");
}

int do_jump(string str)
{
        if ( (!str) || (str != "pit") ) return 0;
        tell_object(this_player(),@LONG
你鼓起勇气往这个小洞穴一跳，忽然一阵黑雾袭来，你晕了过去。
LONG
        );
        this_player()->set_temp("block_command",1);
        call_out ("to_go",5,this_player());
        return 1;
}

int put_misc(string str)
{
   	object misc,player;
	player = this_player();
   	misc = present( "sky amulet", this_player() );

   	if( !str )
   	{
        	write( "你要放啥?\n" );
        	return 1;
     	}
   	if( str != "amulet into prymaid" ) 
	{
        	write( "你要放啥在哪?\n" );
        	return 1;
      	}
   	if( !misc ) 
	{
        	write( "你身上没有适当的东西可以放进三角锥!\n" );
         	return 1;
     	}
   	if( (string)misc->query("c_name")!="天空守护徽章" )
        	return 1;

	tell_room(environment(player),set_color(
		(string)player->query("c_name")+"把一枚闪闪发光的徽章放"+
		"入三角锥的里面，顿时一道绿红色的光芒从三角锥的内部直射"+
		"天际，四周的石柱发出悲鸣声，你发现"+
		(string)player->query("c_name")+"身上的伤口发出金色的光"+
		"芒，一瞬间就愈合了。\n","HIG"),this_player() );

	tell_object(this_player(),"你把手中的天空守护徽章放入三角锥里，"+
		"一时天雷勾动地火，绿红色的光芒直射天际，四周的石柱发出"+
		"震耳欲聋的悲鸣声。在你为之惊愕的同时，你身上的伤口竟都"+
		"愈合了。\n");

	player->set("medication_resistance", 0);
	player->set("hit_points", (int)player->query("max_hp"));
        player->set("spell_points", (int)player->query("max_sp"));
       	player->set("talk_points", (int)player->query("max_tp"));
        player->set("force_points", (int)player->query("max_fp"));
	misc->remove();
   	return 1;
}

int to_go()
{
        tell_object(this_player(),@LONG
过了不知道多久，你才醒了过来，发现自己身处在一个不知道是哪里的地方。
LONG
        );
        this_player()->move_player(HAWK"room1-1","SNEAK");
        this_player()->set_temp("block_command",0);
        return 1;
}

