// File: /d/noden/hawk/altar1.c
// Generated by Roommaker Sun Jan  9 04:16:40 1994

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("祭坛入口");
	set_long( @C_LONG_DESCRIPTION
你现在来到一座圆形祭坛前的入口，这座祭坛位於群山环抱的一个谷底，四周
全都是难以攀爬的悬崖峭壁，在你的东边有一个生锈的铁门，地上零零散散地有几
个脚印(footprints)，你注意到西边的峭壁上垂下一根绳子(rope)，绳子高高地绑
在高处一棵长在峭壁间的树上。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "item_desc", ([ 
		"rope" : @LONG_TEXT
这根绳子绑在这里似乎已经很久了，你试著拉一拉试试重量，绳子发出一阵轻微
的「啪拉」断裂声，为了你的安全起见，最好别试著攀爬(climb)这根绳子。
LONG_TEXT
, 
		"footprints" : @LONG_TEXT
这些脚印有两种，一种有四根脚趾，可能还带有爪子，你猜大概是鸟人族所留下的
，另一种脚印要比鸟人族的大得多，有三根脚趾，看不出有没有爪子，有些脚印上
似乎还有乾掉的血迹，也许这里鸟人族曾和某种生物发生过战争。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/hawk/altar2",
		"east" : "/d/noden/hawk/cave" ]) );
	set( "pre_exit_func", ([
		"north": "check_guard" ]) );
	set( "objects", ([
		"guard#1" : "/d/noden/hawk/monster/altar_guard",
		"guard#2" : "/d/noden/hawk/monster/altar_guard",
		"guard#3" : "/d/noden/hawk/monster/altar_guard",
		"guard#4" : "/d/noden/hawk/monster/altar_guard" ]) );
	create_door( "east", "west", ([
		"keyword" : ({ "rusty iron door", "iron door", "door" }),
		"name" : "rusty iron door",
		"c_name" : "生锈铁门",
		"c_desc" : "一扇厚重的生锈铁门",
		"status" : "locked",
		"lock" : "HAWK_ALTAR_ENTRANCE"
	]) );
	reset();
}

int check_guard()
{
	if( present( "altar guard" ) ) {
		write(
		"祭坛守卫挡住你的去路，说道: 任何想侵犯神圣祭坛者，格—杀—勿—论！\n"
		);	
		return 1;
	}
}
