// File: /d/noden/hawk/crack2.c
// Generated by Roommaker Sun Jan  9 03:43:35 1994

#include <mudlib.h>
#include <move.h>

inherit ROOM;

int key_present = 1;

void create()
{
	::create();
	set_short("洞穴顶端");
	set_long( @C_LONG_DESCRIPTION
你现在正站在一个洞穴顶端突出的一块岩石上，在你的北边有一个小洞(hole)，你
可以感觉一股新鲜的空气随著小洞中吹进来的凉风灌了进来，这块突出的岩石距离地面
 不远，从这里跳下去应该不会受伤。
C_LONG_DESCRIPTION
	);
	set( "item_desc", ([ 
		"hole" : @LONG_TEXT
你将眼睛凑进那个小洞，发现外面是一个悬崖壁上的平台，平台上赫然躺著一具
白色的骷髅(skeleton)！
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"jump" : "/d/noden/hawk/crack1" ]) );
	set( "item_func", ([
		"skeleton": "look_skeleton" ]) );
	reset();
}

void look_skeleton()
{
	object key;

	if (!key_present)
		write(
		    "一具早已被风沙侵蚀得脆弱不堪的骷髅，似乎是个鸟人的骸骨。\n"
		);
	else {
		write(@ALONG
你发现骷髅的手中握著一把铁灰色的钥匙，你伸手一探，将钥匙从
骷髅手中取了下来。
ALONG
		);
		key_present = 0;
		key = new( "/d/noden/hawk/obj/altar_key" );
		if( (int)key->move(this_player()) != MOVE_OK )
			key->move( this_object() );
           this_player()->set_explore("noden#24");
	}
}

void reset()
{
	::reset();
	key_present = 1;
}
