// File: /d/eastland/1,16.east.c
// Generated by Roommaker Mon Jan 31 06:36:48 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("山丘");
	set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。你看到某个山丘上有座坟场, 一股诡异的乌云笼罩著
这个小山头, 或许\你应该爬上去看看。
LONG_DESCRIPTION
	);

   set_outside( "eastland" );
   set( "no_monster", 1 );
	set( "exits", ([ 
           "north" : "d/eastland/11,13.east",
           "east" : "d/eastland/12,14.east" ]) );
   set( "original", "d/eastland/11,14" );
	set( "virtual_server", "/d/eastland/virtual/east_server" );
   set( "x_coordinate", 11 );
   set( "y_coordinate", 14 );
	reset();
}

void init()
{
   add_action( "climb_up", "climb" );
}

int climb_up(string arg)
{
   if( !arg || arg != "up" )
   return notify_fail( "你趴在地上往前爬, 看起来有够蠢!\n" );
   write( "你慢慢地往上爬向山丘之顶。\n" );
   tell_room( environment(this_player()),
     "你看到"+this_player()->query("c_name")+"慢慢地往上爬。\n"
     , this_player() );
   this_player()->move_player( "/d/eastland/ianyeu/grave_yard1", "SNEAK" );
   return 1;
}
