// File: /d/eastland/8,5.east.c
// Generated by Roommaker Thu Jan 27 03:14:49 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("路口");
	set_long( @LONG_DESCRIPTION
你现在来到一处交叉路口，路边有一块大招牌，上面写著「天马号飞船载客站」
，若岚城的西门就在你的东边不远处，往南一条笔直的大道通往南方的幽国城，向西
的道路 穿过一片草原通往古梅镇。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/eastland/8,6.east", 
		"north" : "d/eastland/8,4.east", 
		"west" : "d/eastland/7,5.east", 
		"east" : "/d/eastland/easta/westgate" ]) );
	set( "original", "d/eastland/8,5" );
	set( "virtual_server", "/d/eastland/virtual/east_server" );
	set( "x_coordinate", 8 );
	set( "y_coordinate", 5 );
	reset();
#include <replace_room.h>
}

void init()
{
	if( !find_object("/d/std/cloud/airship_pegasus") )
		"/d/std/cloud/airship_pegasus"->frog();
}
