// File: /d/eastland/1,16.east.c
// Generated by Roommaker Wed Nov 22 13:05:18 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/2,16.east", 
		"south" : "d/eastland/1,17.east", 
		"north" : "d/eastland/1,15.east" ]) );
	ob->set( "objects", ([ 
		"thief#2" : "/d/eastland/monster/mt_bandit", 
		"thief#1" : "/d/eastland/monster/mt_bandit" ]) );
	ob->set( "original", "d/eastland/1,16" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 1 );
	ob->set( "y_coordinate", 16 );
	ob->reset();
}
