// File: /d/eastland/1,12.east.c
// Generated by Roommaker Wed Nov 22 13:04:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。在北边的山坡上，生长著许\多芦苇，芦丛当中有一条狭
窄的小路，不知通向何处?
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/2,12.east", 
		"south" : "d/eastland/1,13.east", 
		"north" : "/d/eastland/liang_shan/out3" ]) );
	ob->set( "objects", ([ 
		"thief#2" : "/d/eastland/monster/mt_bandit", 
		"thief#1" : "/d/eastland/monster/mt_bandit" ]) );
	ob->set( "original", "d/eastland/1,12" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 1 );
	ob->set( "y_coordinate", 12 );
	ob->reset();
}
