// File: /d/eastland/10,4.east.c
// Generated by Roommaker Wed Nov 22 13:06:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "east" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/11,4.east", 
		"west" : "d/eastland/9,4.east", 
		"north" : "d/eastland/10,3.east", 
		"south" : "d/eastland/10,5.east" ]) );
	ob->set( "objects", ([ 
		"wolf" : "/d/eastland/monster/huge_wolf" ]) );
	ob->set( "original", "d/eastland/10,4" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 11 );
	ob->set( "y_coordinate", 4 );
	ob->reset();
}
