// File: /d/eastland/10,13.east.c
// Generated by Roommaker Wed Nov 22 13:05:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河边");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了河边的平地上，疏落的青草点缀在河岸数不尽的卵石坪
上，潺潺的流水声使人忘却了烦恼。另外你看到在河边有一家小茶铺。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"enter" : "/d/eastland/ianyeu/tea_booth", 
		"east" : "d/eastland/11,13.east", 
		"north" : "d/eastland/10,12.east" ]) );
	ob->set( "original", "d/eastland/10,13" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 10 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
