// File: /d/eastland/11,4.east.c
// Generated by Roommaker Wed Nov 22 13:07:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/12,4.east", 
		"west" : "d/eastland/10,4.east", 
		"north" : "d/eastland/11,3.east", 
		"south" : "d/eastland/11,5.east" ]) );
	ob->set( "objects", ([ 
		"sheep#9" : "/d/eastland/monster/sheep", 
		"sheep#11" : "/d/eastland/monster/sheep", 
		"sheep#7" : "/d/eastland/monster/sheep", 
		"sheep#5" : "/d/eastland/monster/sheep", 
		"sheep#12" : "/d/eastland/monster/sheep", 
		"sheep#3" : "/d/eastland/monster/sheep", 
		"sheep#1" : "/d/eastland/monster/sheep", 
		"sheep#8" : "/d/eastland/monster/sheep", 
		"sheep#13" : "/d/eastland/monster/sheep", 
		"sheep#6" : "/d/eastland/monster/sheep", 
		"sheep#10" : "/d/eastland/monster/sheep", 
		"sheep#4" : "/d/eastland/monster/sheep", 
		"sheep#2" : "/d/eastland/monster/sheep", 
		"girl" : "/d/eastland/monster/shepherdess" ]) );
	ob->set( "original", "d/eastland/11,4" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 11 );
	ob->set( "y_coordinate", 4 );
	ob->reset();
}
