// File: /d/eastland/12,5.east.c
// Generated by Roommaker Wed Nov 22 13:08:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("叉路");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一处叉路，往北是一条黄泥夹著碎石的大路，通往捍卫北方的牧马关
，往东的碎石路穿过一片碧绿的田野，通往东海滨的海威镇，往西的大道通往繁华富
庶的京城「若岚城」。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/13,5.east", 
		"west" : "d/eastland/11,5.east", 
		"north" : "d/eastland/12,4.east", 
		"south" : "d/eastland/12,6.east" ]) );
	ob->set( "original", "d/eastland/12,5" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 12 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
