// File: /d/eastland/16,10.east.c
// Generated by Roommaker Wed Nov 22 13:10:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "d/eastland/15,10.east", 
		"north" : "d/eastland/16,9.east", 
		"south" : "d/eastland/16,11.east" ]) );
	ob->set( "original", "d/eastland/16,10" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 16 );
	ob->set( "y_coordinate", 10 );
	ob->reset();
}
