// File: /d/eastland/16,8.east.c
// Generated by Roommaker Wed Nov 22 13:10:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("沙滩");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了海边的沙滩上，一望无际的大海在远处和碧蓝的天空相接，使
人忘却了烦恼。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/16,9.east", 
		"north" : "d/eastland/16,7.east", 
		"west" : "d/eastland/15,8.east" ]) );
	ob->set( "objects", ([ 
		"crab#1" : "/d/eastland/monster/crab", 
		"crab#2" : "/d/eastland/monster/crab" ]) );
	ob->set( "original", "d/eastland/16,8" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 16 );
	ob->set( "y_coordinate", 8 );
	ob->reset();
}
