// File: /d/eastland/19,11.east.c
// Generated by Roommaker Wed Nov 22 13:11:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("沙滩");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了海边的沙滩上，一望无际的大海在远处和碧蓝的天空相接，使
人忘却了烦恼。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/19,12.east", 
		"west" : "d/eastland/18,11.east" ]) );
	ob->set( "objects", ([ 
		"mew" : "/d/eastland/haiwei/monster/mew" ]) );
	ob->set( "original", "d/eastland/19,11" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 19 );
	ob->set( "y_coordinate", 11 );
	ob->reset();
}
