// File: /d/eastland/2,2.east.c
// Generated by Roommaker Wed Nov 22 13:12:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/3,2.east", 
		"north" : "d/eastland/2,1.east", 
		"south" : "/d/eastland/goomay/back_gate" ]) );
	ob->set( "original", "d/eastland/2,2" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 2 );
	ob->set( "y_coordinate", 2 );
	ob->reset();
}
