// File: /d/eastland/2,4.east.c
// Generated by Roommaker Wed Nov 22 13:12:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("道路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条碎石铺成的道路上，道路向南、北方延伸。路旁的草
地上长著一些不知名的野花及野草。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/3,4.east", 
		"south" : "d/eastland/2,5.east", 
		"north" : "/d/eastland/goomay/mgate", 
		"west" : "d/eastland/1,4.east" ]) );
	ob->set( "original", "d/eastland/2,4" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 2 );
	ob->set( "y_coordinate", 4 );
	ob->reset();
}
