// File: /d/eastland/5,1.east.c
// Generated by Roommaker Wed Nov 22 13:15:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。一座庞大的黑色山脉矗立在北方，遥远的山顶上还冒
著袅袅的白烟。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "d/eastland/4,1.east", 
		"south" : "d/eastland/5,2.east", 
		"northeast" : "/d/eastland/volcano/wild1" ]) );
	ob->set( "original", "d/eastland/5,1" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 1 );
	ob->reset();
}
