// File: /d/eastland/5,17.east.c
// Generated by Roommaker Wed Nov 22 13:15:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖\著举目所及的山丘，几株大树散
布在山坡上。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "d/eastland/5,16.east" ]) );
	ob->set( "original", "d/eastland/5,17" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 17 );
	ob->reset();
}
