// File: /d/eastland/5,15.east.c
// Generated by Roommaker Wed Nov 22 13:15:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("道路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条碎石铺成的道路上，道路向东、西方向延伸。路旁的草
地上长著一些不知名的野花及野草。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/6,15.east", 
		"west" : "/d/eastland/yogor/eastgate", 
		"north" : "d/eastland/5,14.east", 
		"south" : "d/eastland/5,16.east" ]) );
	ob->set( "original", "d/eastland/5,15" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 15 );
	ob->reset();
}
