// File: /d/eastland/5,3.east.c
// Generated by Roommaker Wed Nov 22 13:16:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/6,3.east", 
		"west" : "d/eastland/4,3.east", 
		"north" : "d/eastland/5,2.east", 
		"south" : "d/eastland/5,4.east" ]) );
	ob->set( "objects", ([ 
		"wolf#2" : "/d/eastland/monster/wolf", 
		"wolf#1" : "/d/eastland/monster/wolf" ]) );
	ob->set( "original", "d/eastland/5,3" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 3 );
	ob->reset();
}
