// File: /d/eastland/8,13.east.c
// Generated by Roommaker Mon Nov 20 15:19:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大石桥");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一座长约一百公尺的大石桥上，羿水河滔滔不绝地在大石桥下
流过，河水流过桥孔，发出轰隆隆如雷的声响，往北一条笔直的大道穿过一望无
际的田野，过石桥往南则是通往幽国城的官道。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/8,14.east", 
		"north" : "d/eastland/8,12.east" ]) );
	ob->set( "objects", ([ 
		"wife" : "/d/eastland/monster/bandit_wife", 
		"bandit" : "/d/eastland/monster/bandit" ]) );
	ob->set( "original", "d/eastland/8,13" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 8 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
