// File: /d/eastland/9,14.east.c
// Generated by Roommaker Wed Nov 22 13:20:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河边");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了河边的平地上，疏落的青草点缀在河岸数不尽的卵石坪
上，潺潺的流水声使人忘却了烦恼。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/9,15.east", 
		"west" : "d/eastland/8,14.east" ]) );
	ob->set( "objects", ([ 
		"rhinoceros1" : "/d/eastland/monster/rhinoceros", 
		"rhinoceros2" : "/d/eastland/monster/rhinoceros" ]) );
	ob->set( "original", "d/eastland/9,14" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 9 );
	ob->set( "y_coordinate", 14 );
	ob->reset();
}
