// File: /d/eastland/9,4.east.c
// Generated by Roommaker Wed Nov 22 13:19:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草地");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片绿油油的草地上，青翠的草地带著令人愉悦的
气息。几丛植物散布在碧绿的草地间，点缀著五彩缤纷的不知名野
花，使人心旷神宜。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/10,4.east", 
		"south" : "/d/eastland/easta/northgate", 
		"north" : "d/eastland/9,3.east", 
		"west" : "d/eastland/8,4.east" ]) );
	ob->set( "original", "d/eastland/9,4" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 9 );
	ob->set( "y_coordinate", 4 );
	ob->reset();
}
