// File: /d/deathland/ruin1/down01.c
// Generated by Roommaker Thu Nov 23 20:45:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹地下室");
	ob->set_long( @LONG_DESCRIPTION
这里是遗迹的地下室 ,似乎是用来避难的地方 .然而地上到处是一堆堆的骨骸与乾
掉的血迹 .更让人觉得气氛显得十分的诡异 .你无法想像当时的情况是如何 ,但是你\或\
\许\可以理解到为甚麽这地方一直没有人发现它 ,因为当时的一场灾难把这座城市的人都
给毁灭了 .甚至於躲在这里的人都不能幸勉 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/deathland/ruin1/ruin55", 
		"south" : "/d/deathland/ruin1/down02" ]) );
	ob->reset();
}
