// File: /d/deathland/ruin1/entry.c
// Generated by Roommaker Thu Nov 23 20:51:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹入口");
	ob->set_long( @LONG_DESCRIPTION
除了在你面前的一座破旧的遗迹之外,这里似乎是一片虚无的世界,在你的上下都是
黝黑的岩石,使你有一种沉重的压迫感,除了退回去之外,\或\许\你可以进入那处未知的遗
迹看看.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"ruin" : "/d/deathland/ruin1/ruin31", 
		"back" : "/d/deathland/ruin1/path04" ]) );
	ob->reset();
}
