// File: /d/deathland/ruin1/path01.c
// Generated by Roommaker Thu Nov 23 20:52:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑黑的小径");
	ob->set_long( @LONG_DESCRIPTION
在这个隐密的大洞穴中 ,你查觉到这里与迷宫中其他地方有一些不同 ,这里的
空间比较开阔 .而且当你小心的把这个地方仔细地看了一遍後 ,你注意到有一条很
隐密的小径通向东方 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/ruin1/path02", 
		"west" : "/d/deathland/dwarf/darkroom" ]) );
	ob->reset();
}
