// File: /d/deathland/ruin1/ruin31.c
// Generated by Roommaker Thu Nov 23 20:51:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹");
	ob->set_long( @LONG_DESCRIPTION
一座破旧的遗迹 ,这里似乎已经荒废很久了 .地上到处是残砖破瓦 ,更让人觉得
这地方已经\许\久未曾有人烟了 .一种绿色的藓苔植物附在两旁的墙壁上 ,使得这地方
的气氛更显得十分的诡异 .
    从这里你可以离开这个令人不舒服的古代遗迹 ,当然你也可以发挥你丰富的探险
精神更进一步的深入遗迹的内部.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/ruin1/ruin32", 
		"leave" : "/d/deathland/ruin1/entry" ]) );
	ob->reset();
}
