// File: /d/deathland/ruin1/ruin34.c
// Generated by Roommaker Thu Nov 23 20:50:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹");
	ob->set_long( @LONG_DESCRIPTION
一座破旧的遗迹 ,这里似乎已经荒废很久了 .地上到处是残砖破瓦 ,更让人觉得
这地方已经\许\久未曾有人烟了 .一种绿色的藓苔植物附在两旁的墙壁上 ,使得这地方
的气氛更显得十分的诡异 .
    在这里你发现你的北边似乎存在著人类活动的讯息 ,但是你不能够确定 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/ruin1/ruin35", 
		"south" : "/d/deathland/ruin1/ruin33" ]) );
	ob->reset();
}
