// File: /d/deathland/ruin1/ruin32.c
// Generated by Roommaker Thu Nov 23 20:50:52 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹");
	ob->set_long( @LONG_DESCRIPTION
一座破旧的遗迹 ,这里似乎已经荒废很久了 .地上到处是残砖破瓦 ,更让人觉得
这地方已经\许\久未曾有人烟了 .一种绿色的藓苔植物附在两旁的墙壁上 ,使得这地方
的气氛更显得十分的诡异 .
    从这里你可以更进一步的深入遗迹的内部 .但是你慢慢地感觉到危险已经渐渐的
逼近了 .    
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/ruin1/ruin33", 
		"south" : "/d/deathland/ruin1/ruin31" ]) );
	ob->reset();
}
