// File: /d/deathland/ruin1/ruin53.c
// Generated by Roommaker Thu Nov 23 20:46:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遗迹");
	ob->set_long( @LONG_DESCRIPTION
一座破旧的遗迹 ,这里似乎已经荒废很久了 .地上到处是残砖破瓦 ,更让人觉得
这地方已经\许\久未曾有人烟了 .一种绿色的藓苔植物附在两旁的墙壁上 ,使得这地方
的气氛更显得十分的诡异 .
    这里是遗迹的一处死胡同 ,似乎这个地方是市场的所在 .你似乎还能听到小贩叫
卖的声音 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/ruin1/ruin43" ]) );
	ob->set( "objects", ([ 
		"merchant" : "/d/deathland/monster/merchant03" ]) );
	ob->reset();
}
