// File: /d/noden/asterism/city11.c
// Generated by Roommaker Thu Nov 23 19:13:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城市大路");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩(asterism)城的大道路, 由於半身人灵巧的设计天份及矮人的
建筑技巧, 这里的道路十分宽敞笔直, 而且道路两旁种植的树木花草在相互搭配之下, 
让人好像置身於一座优美的公园。北边和东边是坚固的城墙, 经过数百年的风吹日晒, 
依然屹立不摇。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/asterism/city21", 
		"south" : "/d/noden/asterism/city12" ]) );
	ob->reset();
}
