// File: /d/noden/asterism/city41.c
// Generated by Roommaker Thu Nov 23 19:12:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城市大路");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩(asterism)城的大道路, 由於半身人灵巧的设计天份及矮人的
建筑技巧,这里的道路十分宽敞笔直, 而且道路两旁种植的树木花草在相互搭配之下, 
让人好像置身於一座优美的公园。北边是面坚固的城墙, 经过数百年风吹日晒, 依然
屹立不摇。而南边有一家新开的药店。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/asterism/city31", 
		"south" : "/d/noden/asterism/apoth", 
		"west" : "/d/noden/asterism/city51" ]) );
	ob->reset();
}
