// File: /d/noden/asterism/ladder01.c
// Generated by Roommaker Thu Nov 23 19:11:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往山顶的石梯");
	ob->set_long( @LONG_DESCRIPTION
一座巨大的山峰耸立在你的面前,在贝尔基山脉的主峰,阿莱特山
的面前,你感觉到你是如此的渺小.有个小小的石梯通向山顶,而山顶
上有座宏伟的城市,艾斯特律恩城。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/6,13.noden", 
		"up" : "/d/noden/asterism/ladder02" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
