// File: /d/noden/asterism/path4.c
// Generated by Roommaker Thu Nov 23 19:14:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小径");
	ob->set_long( @LONG_DESCRIPTION
你现在正漫步在一片树林中。四周的蝉鸣鸟声使你几乎想要永远住在这人间仙境,
不再回到那纷扰的世界。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/asterism/path3", 
		"south" : "/d/noden/asterism/wall" ]) );
	ob->reset();
}
