// File: /d/noden/asterism/path1.c
// Generated by Roommaker Thu Nov 23 19:13:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小径");
	ob->set_long( @LONG_DESCRIPTION
你现在正漫步在一片树林中。四周的蝉鸣鸟声使你几乎想要永远住在这人间仙境,
不再回到那纷扰的世界。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/asterism/patha", 
		"south" : "/d/noden/asterism/path2", 
		"northeast" : "/d/noden/asterism/city14" ]) );
	ob->set( "objects", ([ 
		"monkey#1" : "/d/noden/asterism/monster/monkey", 
		"monkey#2" : "/d/noden/asterism/monster/monkey" ]) );
	ob->reset();
}
