// File: /d/noden/asterism/tower2-0.c
// Generated by Roommaker Thu Nov 23 19:15:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人高塔的地下室");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中矮人高塔的地下室，所有想外出寻求发展的矮人年轻人，
都一定会先在这接受矮人长老的训勉。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/asterism/court", 
		"up" : "/d/noden/asterism/tower2-1" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/noden/asterism/monster/dwarf_elder" ]) );
	ob->reset();
}
