// File: /d/noden/asterism/tower3-5.c
// Generated by Roommaker Thu Nov 23 19:15:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的五楼");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中地精高塔的第五层。矮人和半身人为这片土地本来的
主人建筑了这麽一座外观宏伟的住所。这儿四周的墙璧,被各式各色的宝石镶点
得五彩缤纷。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower3-4", 
		"up" : "/d/noden/asterism/tower3-6" ]) );
	ob->set( "objects", ([ 
		"chest" : "/d/noden/asterism/item/bigchest" ]) );
	ob->reset();
}
