// File: /d/noden/asterism/tower1-0.c
// Generated by Roommaker Thu Nov 23 19:14:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的地下室");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中半身人高塔的地下室,堆积著一堆杂七杂八的废弃物,让这地
方显得十分混乱.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_c_msg", ([ ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/asterism/court", 
		"up" : "/d/noden/asterism/tower1-1" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/noden/asterism/monster/halfling_elder" ]) );
	ob->reset();
}
