// File: /d/noden/asterism/tower3-2.c
// Generated by Roommaker Thu Nov 23 19:15:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的二楼");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中地精高塔的第二层。矮人和半身人为这片土地本来的
主人建筑了这麽一座外观宏伟的住所。这儿四周的墙璧,被各式各色的宝石镶点
得五彩缤纷。而墙壁上刻著一堆奇怪的符号。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower3-1", 
		"up" : "/d/noden/asterism/tower3-3" ]) );
	ob->set( "objects", ([ 
		"girl#1" : "/d/noden/asterism/monster/gnome_girl", 
		"girl#2" : "/d/noden/asterism/monster/gnome_girl", 
		"child#2" : "/d/noden/asterism/monster/gnome_child", 
		"child#1" : "/d/noden/asterism/monster/gnome_child" ]) );
	ob->reset();
}
