// File: /d/noden/asterism/tower1-2.c
// Generated by Roommaker Thu Nov 23 19:14:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的第二层");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中半身人高塔的第二层,一种快乐的气氛感染了你的心头,在
半身人无可救药的乐天派的影响下,他们认为一层的防卫措施已经足够,因此这里天天
都在开宴会,充满著欢笑的声音.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower1-1", 
		"up" : "/d/noden/asterism/tower1-3" ]) );
	ob->set( "objects", ([ 
		"girl#1" : "/d/noden/asterism/monster/halfling_girl", 
		"boy#1" : "/d/noden/asterism/monster/halfling_boy", 
		"girl#2" : "/d/noden/asterism/monster/halfling_girl", 
		"boy#2" : "/d/noden/asterism/monster/halfling_boy" ]) );
	ob->reset();
}
