// File: /d/noden/asterism/tower1-4.c
// Generated by Roommaker Thu Nov 23 19:14:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的第四层");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中半身人高塔的第四层,许许多多的建筑设计都是在此产
生的,半身人灵巧的头脑造就了这个漂亮的城市.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower1-3", 
		"up" : "/d/noden/asterism/tower1-5" ]) );
	ob->set( "objects", ([ 
		"artisan" : "/d/noden/asterism/monster/artisan" ]) );
	ob->reset();
}
