// File: /d/noden/asterism/tower3-4.c
// Generated by Roommaker Thu Nov 23 19:15:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的四楼");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中地精高塔的第四层。矮人和半身人为这片土地本来的
主人建筑了这麽一座外观宏伟的住所。这儿四周的墙璧,被各式各色的宝石镶点
得五彩缤纷。靠北边的墙看来虽是刚补的，但是现在又是坑坑洞洞，好像被很强
的力量冲击过很多次。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower3-3", 
		"up" : "/d/noden/asterism/tower3-5" ]) );
	ob->set( "objects", ([ 
		"student#2" : "/d/noden/asterism/monster/gnome_student", 
		"student#1" : "/d/noden/asterism/monster/gnome_student", 
		"teacher" : "/d/noden/asterism/monster/gnome_teacher" ]) );
	ob->reset();
}
