// File: /d/noden/asterism/tower2-4.c
// Generated by Roommaker Thu Nov 23 19:16:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人高塔的第四层");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中矮人高塔的第四层,也就是矮人王阿莱特斯四世的起居室，
但这里似乎是个小孩子的游戏间。再往上一层是矮人的会议室.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower2-3", 
		"up" : "/d/noden/asterism/tower2-5" ]) );
	ob->set( "objects", ([ 
		"drynurse" : "/d/noden/asterism/monster/drynurse" ]) );
	ob->reset();
}
