// File: /d/noden/asterism/tower3-0.c
// Generated by Roommaker Thu Nov 23 19:15:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的地下室");
	ob->set_long( @LONG_DESCRIPTION
这里是艾斯特律恩城中地精高塔的地下室，所有即将外出寻求发展的地精年轻人，
依惯例都会先在这接受地精长老的训勉。这□布置得富丽堂皇,壁上全镶上各式宝
石,什麽祖母绿,猫眼石,红榴石,钻石都看得到。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/asterism/court", 
		"up" : "/d/noden/asterism/tower3-1" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/noden/asterism/monster/gnome_elder" ]) );
	ob->reset();
}
