// File: /d/eastland/legend/lake/house18.c
// Generated by Roommaker Thu Mar 21 17:26:58 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小茅屋");
	ob->set_long( @LONG_DESCRIPTION
屋子里几乎没有什麽贵重的摆设，除了墙角边一张破烂的桌子和几张椅子外，
四周斑白的墙壁把这里衬托得更是凄凉。墙的另一边有几支破烂的渔篓子，和一支
钓杆，似乎很久没人使用它们，它们上面都积了一层厚厚的灰尘。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/village18" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/eastland/legend/monster/older" ]) );
	ob->reset();
}
