// File: /d/eastland/legend/lake/house1.c
// Generated by Roommaker Thu Mar 21 17:25:20 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小木屋");
	ob->set_long( @LONG_DESCRIPTION
一间用绘木制成的屋子。屋内并无神坛，却有丝丝檀香香气扑鼻芬芳。建筑虽
不似宫阙镂簋朱宏，雕粱画栋，但静逸的气氛油然而生。桌椅家具排列井然，桌上
一本茶花『二乔』，两朵一白一红的盛开著，花色纯正无丝毫驳杂，可见主人对茶
花颇有研究。除此之外，屋内更无他物。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/village3" ]) );
	ob->set( "objects", ([ 
		"man" : "/d/eastland/legend/monster/man1", 
		"woman" : "/d/eastland/legend/monster/woman1" ]) );
	ob->reset();
}
