// File: /d/eastland/legend/lake/mountain4.c
// Generated by Roommaker Thu Mar 21 17:30:20 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山巅");
	ob->set_long( @LONG_DESCRIPTION
你翻过刚才那面峭壁之後来到了山的另一边。 你现在正走在一条山巅的山路
上,山路崎岖不平,地上长了些稀稀疏疏的野草,旁边有一颗大树。这里的视野很好
,你俯视下去可以看到一面大湖。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"bluff" }) );
	ob->set( "exits", ([ 
		"bluff" : "/d/eastland/legend/lake/mountain3", 
		"west" : "/d/eastland/legend/lake/mountain5" ]) );
	ob->reset();
}
