// File: /d/eastland/legend/lake/mountain1.c
// Generated by Roommaker Thu Mar 21 17:29:40 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腰");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条蜿延而上的山路，四周都是峻嶙的高山。这条山路出乎意外
的狭窄，它的坡度很陡让你有种快要往下掉的感觉。山路的地上光秃秃的连一根杂
草也没有，两旁还有几块巨大的岩石。    
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/legend/lake/mountain0", 
		"up" : "/d/eastland/legend/lake/mountain2" ]) );
	ob->set( "objects", ([ 
		"tiger#2" : "/d/eastland/legend/monster/tiger", 
		"tiger#1" : "/d/eastland/legend/monster/tiger" ]) );
	ob->reset();
}
