// File: /d/eastland/legend/lake/mountain2.c
// Generated by Roommaker Thu Mar 21 17:30:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山巅");
	ob->set_long( @LONG_DESCRIPTION
你走著走著来到了山巅的位置, 身旁的浮云把你笼罩在一片白雾里,白茫茫地
使你看不到任何东西。 远远望去,隐隐约约有几座突出云层的小山群,小山群好似
戴著一顶顶白色的帽子。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"east", 
		"down" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/mountain3", 
		"down" : "/d/eastland/legend/lake/mountain1" ]) );
	ob->reset();
}
