// File: /d/eastland/legend/lake/mountain8.c
// Generated by Roommaker Tue Jul 30 18:55:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山下");
	ob->set_long( @LONG_DESCRIPTION
你走到了这里山路愈见平缓。在你旁边是一大片花丛，花丛里五颜六色的花朵
争相璨烂地开放著，可乐了一旁正在采花蜜的野蜂。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"nu" }) );
	ob->set( "exits", ([ 
		"northup" : "/d/eastland/legend/lake/mountain7", 
		"down" : "/d/eastland/legend/lake/plain0", 
		"nu" : "/d/eastland/legend/lake/mountain7" ]) );
	ob->set( "objects", ([ 
		"daoist" : "/d/eastland/legend/monster/daoist" ]) );
	ob->reset();
}
