// File: /d/eastland/legend/lake/mountain0.c
// Generated by Roommaker Tue Jul 30 18:48:57 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山脚下");
	ob->set_long( @LONG_DESCRIPTION
你的四周都是峻嶙的高山,眼前有一条蜿延而上的山路。上山时可要特别小心
,尤其是在这种人烟稀少的地方,通常都会有狮子老虎这类的猛兽出现。 你身边最
好多带些乾粮以备後患,尤其是当山难发生时,那可是叫天天不应,叫地地不灵喔。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exit_suppress", ({ 
		"nwd" }) );
	ob->set( "exits", ([ 
		"nwd" : "/d/eastland/beggar/area/s4e2", 
		"northwestdown" : "/d/eastland/beggar/area/s4e2", 
		"up" : "/d/eastland/legend/lake/mountain1" ]) );
	ob->reset();
}
