// File: /d/eastland/legend/lake/tree1.c
// Generated by Roommaker Thu Mar 21 17:26:35 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("树洞");
	ob->set_long( @LONG_DESCRIPTION
你身处在神木的树洞里，在这里，冥冥中似乎可以听到佛家的梵语声，它带给你内
心一阵阵的平和感受，使你不再想要有嘶杀的念头。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/plain0" ]) );
	ob->set( "objects", ([ 
		"spirit" : "/d/eastland/legend/monster/spirit1" ]) );
	ob->reset();
}
