// File: /d/eastland/legend/lake/village4.c
// Generated by Roommaker Thu Mar 21 17:27:48 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古木小径");
	ob->set_long( @LONG_DESCRIPTION
你来到了一条古木小径的尽头。小径的两旁有一排排不知名的树木，树枝挡住
了阳光，显得有些阴凉。咦，你耳际传来一阵阵水落差的声音，鼻子一嗅，感到空
气中布满些许的水气，淙淙的水声，附近似乎有条瀑布。你南边是一座古色古香的
凉亭，累了可以去那里稍微休憩小番。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"east" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/village5", 
		"south" : "/d/eastland/legend/lake/village6", 
		"west" : "/d/eastland/legend/lake/village2" ]) );
	ob->reset();
}
