// File: /d/eastland/legend/lake/village10.c
// Generated by Roommaker Thu Mar 21 17:28:52 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("渔村道路");
	ob->set_long( @LONG_DESCRIPTION
你正走在渔村的道路上，迎面扑来的是一股浓浓的腥臭味；在地上，纵横交错
著血水枯乾的小河；一团团苍蝇，正汲汲於腐烂的鱼肉上，不时发出嗡嗡地鸣声。
晦暗不明的天空，乌云团簇好似一只只正在张牙舞爪的野兽，野兽正恶狠狠地瞪著
你，好像对著你说：『快来吧，快来吧，我的食物』。渔村道路往东、南边延申，
西边有一片小空地，北边有一间矮房子。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"矮房子" : "一间破旧的老房子，屋顶没了，只留下三面斑白的墙壁，想必是没人住。\n", 
		"小空地" : "一块小小的空地，地上野草丛生。\n" ]) );
	ob->set( "exit_suppress", ({ 
		"west" }) );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/legend/lake/village9", 
		"west" : "/d/eastland/legend/lake/village19", 
		"north" : "/d/eastland/legend/lake/village17" ]) );
	ob->reset();
}
