// File: /d/eastland/legend/lake/village11.c
// Generated by Roommaker Thu Mar 21 17:29:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("渔村道路");
	ob->set_long( @LONG_DESCRIPTION
你正走在渔村的道路上，迎面扑来的是一股浓浓的腥臭味；在地上，纵横交错
著血水枯乾的小河；一团团苍蝇，正汲汲於腐烂的鱼肉上，不时发出嗡嗡地鸣声。
晦暗不明的天空，乌云团簇好似一只只正在张牙舞爪的野兽，野兽正恶狠狠地瞪著
你，好像对著你说：『快来吧，快来吧，我的食物』。道路往西、北边延申；南边
有片空地；东边有两间房子。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/legend/lake/village12", 
		"west" : "/d/eastland/legend/lake/village9" ]) );
	ob->reset();
}
