// File: /d/eastland/legend/lake/village17.c
// Generated by Roommaker Thu Mar 21 17:29:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("渔村道路");
	ob->set_long( @LONG_DESCRIPTION
你正走在渔村的道路上，迎面扑来的是一股浓浓的腥臭味；在地上，纵横交错
著血水枯乾的小河；一团团苍蝇，正汲汲於腐烂的鱼肉上，不时发出嗡嗡地鸣声。
晦暗不明的天空，乌云团簇好似一只只正在张牙舞爪的野兽，野兽正恶狠狠地瞪著
你，好像对著你说：『快来吧，快来吧，我的食物』。东和南边是一堆和人同高度
的野草；道路往西、北边延申。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/legend/lake/village18", 
		"south" : "/d/eastland/legend/lake/village10" ]) );
	ob->set( "objects", ([ 
		"girl#1" : "/d/eastland/legend/monster/girl", 
		"boy#1" : "/d/eastland/legend/monster/boy", 
		"boy#2" : "/d/eastland/legend/monster/boy" ]) );
	ob->reset();
}
