// File: /d/eastland/legend/lake/village2.c
// Generated by Roommaker Tue Jun 11 20:05:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古木小径");
	ob->set_long( @LONG_DESCRIPTION
你来到了一条古木小径，小径的两旁有一排排不知名的树木，树枝挡住了阳光
，显得有些阴凉，树上一些鸟儿正啾啾地叫著。在北边的树底下似乎有著足迹，不
仔细看还不太清楚。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"north" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/village4", 
		"west" : "/d/eastland/legend/lake/village1", 
		"north" : "/d/eastland/legend/lake/village3" ]) );
	ob->reset();
}
