
ID(L)                   LOCAL FUNCTIONS                     ID(L)

NAME
     id() - checks to see if a string  is  a  legal  id  for  the
     object

SYNOPSIS
     int id (string str) ;

DESCRIPTION
     The id() lfun is defined in the standard object. It  returns
     1  if the string is a member of the object's "id" array, and
     0 if not.

SEE_ALSO
     /std/object/ob_logic.c

AUTHOR
     Mobydick@TMI-2


TMI-2 Release 0.9         Last change:                   4-2-93

