// File: /d/noden/moyada/anthill/check_point.c
// Generated by Roommaker Mon Dec  4 20:45:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("岗哨");
	ob->set_long( @LONG_DESCRIPTION
看这里守卫森严的样子，里面一定住著极为重要的人物。守卫蚁正盯著
你看，似乎并不欢迎你。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/moyada/anthill/cellar3", 
		"east" : "/d/noden/moyada/anthill/square" ]) );
	ob->set( "objects", ([ 
		"ant guard#2" : "/d/noden/moyada/monster/ant_guard", 
		"kaisa ant" : "/d/noden/moyada/monster/kaisa_ant", 
		"ant guard#1" : "/d/noden/moyada/monster/ant_guard", 
		"ant knight" : "/d/noden/moyada/monster/ant_knight" ]) );
	ob->reset();
}
