// File: /d/noden/moyada/anthill/kitchen.c
// Generated by Roommaker Mon Dec  4 20:47:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("餐厅");
	ob->set_long( @LONG_DESCRIPTION
这里看起来像是这些怪蚁们吃饭用餐的地方，蚁厨师正在忙著把食物弄的更
美味。几只战士蚁正在享受它们的大餐，看起来似乎很好吃的样子。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/moyada/anthill/cellar2" ]) );
	ob->set( "objects", ([ 
		"ant solider#1" : "/d/noden/moyada/monster/ant_solider", 
		"ant solider#2" : "/d/noden/moyada/monster/ant_solider", 
		"ant solider#3" : "/d/noden/moyada/monster/ant_solider", 
		"ant cooker" : "/d/noden/moyada/monster/ant_cooker" ]) );
	ob->reset();
}
