// File: /d/noden/forest/ruin/hidden_path4.c
// Generated by Roommaker Mon Dec  4 21:22:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兽径");
	ob->set_long( @LONG_DESCRIPTION
小径南北延伸著。从这里, 可以遥望对面的山头, 有点模糊的影像让
人意识到自己原来已经走了这麽远呀! 环顾四周, 全是朦胧的山影, 这个
小盆地的四周完全被山所包围了, 难怪人迹罕至。在往北的路上, 一些零
散的石板被铺在地面上, 或许\小径的终点已经接近了吧?
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/entry", 
		"south" : "/d/noden/forest/ruin/hidden_path3" ]) );
	ob->set( "objects", ([ 
		"wolf3" : "/d/noden/monster/wolf", 
		"wolf1" : "/d/noden/monster/wolf", 
		"wolf2" : "/d/noden/monster/wolf" ]) );
	ob->reset();
}
