// File: /d/noden/forest/ruin/hidden_path3.c
// Generated by Roommaker Mon Dec  4 21:21:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兽径");
	ob->set_long( @LONG_DESCRIPTION
小径在树林中南北蜿蜒著。虽说是人迹罕至, 但树木仍然整齐地沿路
生长著。虽然枝叶已经能遮蔽整个路面, 落叶也早已积了厚厚的一大层,
但是要认出路面依然不难。只是, 大树们总是毫无变化地排排站著。原先
就已经漫长的路, 因此而更加显得无穷无尽了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/forest/ruin/hidden_path2", 
		"north" : "/d/noden/forest/ruin/hidden_path4" ]) );
	ob->set( "objects", ([ 
		"tiger2" : "/d/noden/forest/ruin/monster/tiger2", 
		"tiger1" : "/d/noden/forest/ruin/monster/tiger1" ]) );
	ob->reset();
}
