// File: /d/noden/forest/ruin/hidden_path.c
// Generated by Roommaker Mon Dec  4 21:20:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兽径");
	ob->set_long( @LONG_DESCRIPTION
小径在你眼前向北延伸。这大概就是往谷底的路吧! 好像是非常漫长
的样子。这里据说是人迹罕至, 但看来似乎不是这麽回事。小径上有著不
少来来往往的痕迹, 虽然其中有些看起来并不太像是人的...
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/hidden_path2", 
		"up" : "/d/noden/forest/ruin/plate" ]) );
	ob->set( "objects", ([ 
		"boar" : "/d/noden/monster/boar", 
		"falcon" : "/d/noden/monster/falcon" ]) );
	ob->reset();
}
