// File: /d/noden/forest/ruin/n_hall.c
// Generated by Roommaker Mon Dec  4 21:22:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大厅");
	ob->set_long( @LONG_DESCRIPTION
你身处於山洞之中。这里并不是非常黑暗, 空间也相当地广大。虽然
年代久远, 但从石制的地板、墙壁与天花板上时时可见精美的雕刻, 可以
看出这是个大厅。而你现在正位於这个大厅的北侧, 北边似乎有一条通道
, 但入口并不十分明显。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exit_suppress", ({ 
		"north" }) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/ruin/ne_hall", 
		"west" : "/d/noden/forest/ruin/nw_hall", 
		"north" : "/d/noden/forest/ruin/tunnel", 
		"south" : "/d/noden/forest/ruin/hall" ]) );
	ob->set( "objects", ([ 
		"goblin3" : "/d/noden/forest/monster/goblin", 
		"goblin2" : "/d/noden/forest/monster/goblin", 
		"goblin1" : "/d/noden/forest/monster/goblin" ]) );
	ob->reset();
}
