// File: /d/noden/forest/ruin/s_hall.c
// Generated by Roommaker Mon Dec  4 21:26:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大厅");
	ob->set_long( @LONG_DESCRIPTION
虽然是在山洞内, 但这里并不是非常黑暗。空间也远远超过了原先在
入口时的估计。地面、墙壁与天花板都是石砌的, 虽然年代久远, 但仍然
时时可见到原先精美的雕饰。是谁, 为什麽要在山腹中埋著这麽大的一个
建筑物呢? 能创造这麽伟大的建筑物的种族, 为什麽现在会消失无踪呢?
    不过有件事是可以确定的, 你现在所在的场所在从前应该是个大厅。
或许曾经繁华非凡, 或许曾经庄严肃穆, 但现在只馀下空虚的回音了。
    你现在身处於这个大厅的南侧, 再往南就可以离开这个洞穴了。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/ruin/se_hall", 
		"west" : "/d/noden/forest/ruin/sw_hall", 
		"north" : "/d/noden/forest/ruin/hall", 
		"south" : "/d/noden/forest/ruin/entry" ]) );
	ob->reset();
}
