// File: /d/noden/forest/ruin/se_hall.c
// Generated by Roommaker Mon Dec  4 21:29:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大厅");
	ob->set_long( @LONG_DESCRIPTION
你身处於山洞之中。这里并不是非常黑暗, 空间也相当地广大。虽然
年代久远, 但从石制的地板、墙壁与天花板上时时可见精美的雕刻, 可以
看出这是个大厅。而你现在身处於这个大厅的东南角落。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/forest/ruin/s_hall", 
		"north" : "/d/noden/forest/ruin/e_hall" ]) );
	ob->reset();
}
