// File: /d/noden/forest/ruin/tunnel.c
// Generated by Roommaker Mon Dec  4 21:29:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通道");
	ob->set_long( @LONG_DESCRIPTION
这里是条南北方向的通道, 上下左右的墙壁均是由石块砌成的, 看来
相当地雄伟壮观。通道的两侧排列著精美的石雕像, 而且各个都有不同的
神情姿势, 令人为建造者的心思赞叹不已。
    通道的南边是个大厅, 往北则是一片黑暗。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/tunnel_2", 
		"south" : "/d/noden/forest/ruin/n_hall" ]) );
	ob->set( "item_desc", ([ 
		"statues" : @LONG_TEXT
    这些石雕像都被安置於壁上一个个凹入的半圆形小洞中, 被维护得相
当好。他们均是以小鬼族的造型来塑造的, 活泼的神情与栩栩如生的姿态
令观赏者不由得发出会心的一笑。
LONG_TEXT
, 
		"statue" : @LONG_TEXT
    这个石雕像被安置於壁上一个个凹入的半圆形小洞中, 被维护得相当
好。他是以小鬼族的造型来塑造的, 活泼的神情与栩栩如生的姿态令观赏
者不由得发出会心的一笑。
LONG_TEXT
 ]) );
	ob->reset();
}
