// File: /d/eastland/ianyeu/elder_house.c
// Generated by Roommaker Wed May 15 19:34:19 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长老之屋");
	ob->set_long( @LONG_DESCRIPTION
当你踏进这□时, 立刻被四周的物品所吸引。在墙上, 
挂满了宝刀、利剑、长弓 .... 等各类武器, 同时在墙角及
大大小小的橱柜中, 亦堆满了数不清的各式珠宝衣物; 但你
也注意到其中竟也有如绷带、火把、药瓶之类的『垃圾』, 
看来这□的主人是个『搜集狂』。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/ianyeu/hamlet_path2" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/eastland/ianyeu/monster/elder" ]) );
	ob->reset();
}
