// File: /d/eastland/ianyeu/hunter_house.c
// Generated by Roommaker Wed May 15 19:37:53 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("猎人小屋");
	ob->set_long( @LONG_DESCRIPTION
一间用茅草盖\成的小屋。你看到四周的墙上挂满了各种
动物的标本, 而最令你惊讶的是: 不仅有鹿角、狼皮、虎头
、狮身、熊掌 .... 等, 甚至在北面的墙上还有一只麒麟牙!!
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/ianyeu/hamlet_path1" ]) );
	ob->set( "objects", ([ 
		"hunter" : "/d/eastland/ianyeu/monster/hunter" ]) );
	ob->reset();
}
