// File: /d/eastland/ianyeu/wang_home.c
// Generated by Roommaker Wed May 15 19:38:23 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("民宅");
	ob->set_long( @LONG_DESCRIPTION
你正在一间狭小的木屋中, 可是或许\是主人太穷了, 
以致於让你有一种空旷的感觉。你看到除了一张桌子及几
把椅子外, 就没有其它的家俱了。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/ianyeu/hamlet_path1" ]) );
	ob->set( "objects", ([ 
		"wang" : "/d/eastland/ianyeu/monster/wang" ]) );
	ob->reset();
}
