// File: /u/m/mad/room/hamlet_path2.c
// Generated by Roommaker Wed May  3 12:47:05 1995

#include "mad.h"

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("小径");
	set_long( @LONG_DESCRIPTION
你正走在烟雨村内的小径上。当你往前走时, 你感觉到
这儿似乎是人烟稀少; 不仅屋宇疏落, 连小路上都杂草丛生,
你不禁怀疑这是否为一个废弃的村庄! 不过你注意到在东、
西、北各有一间小屋。
LONG_DESCRIPTION
	);

   set_outside("eastland");
	set( "exits", ([ 
           "east" : IAN"guey_home", 
           "north" : IAN"elder_house", 
           "west" : IAN"liang_home", 
           "south" : IAN"hamlet_path1" ]) );
   create_door( "west", "east", ([
                "keyword" : ({ "wooden door", "door" }),
                "name" : "wooden door",
                "c_name" : "木门",
                "c_desc" : "一扇很普通的木门",
                "status" : "locked",
                "lock" : "IANYEU_LIANG_HOME"
        ]) );
	reset();
}
