// File: /u/m/mad/room/hole.c
// Generated by Roommaker Fri May 19 12:44:27 1995

#include "mad.h"

inherit ROOM;

void create()
{
	::create();
   set_short( "巢穴" );
	set_long( @LONG_DESCRIPTION
你正在某种动物的巢穴之中。很意外地, 这□不但相当宽敞
, 而且地上还铺满了洁净柔软的稻草, 空气中似乎还散发出一股
淡淡的馨香, 甚至令你昏昏欲睡!
LONG_DESCRIPTION
	);

   set( "objects", ([
           "raccoon" : IANMOB"raccoon" ]) );
	set( "exits", ([ 
           "out" : "/d/eastland/14,12.east" ]) );
	set( "pre_exit_func", ([ 
		"out" : "no_out" ]) );
	reset();
}

int no_out()
{
   if( present("satyr") && this_player()->query("stop_attack") ) {
     tell_object( this_player(),
         "\n你的双脚被石化了, 无法动弹!!\n\n" );
     return 1;
   }
   else return 0;
}
void init()
{
  if(this_player()) this_player()->set_explore("eastland#19");
}
