// File: /u/m/mad/room/liang_home.c
// Generated by Roommaker Wed May  3 12:28:48 1995

#include "mad.h"

inherit DOORS;
inherit ROOM;

int cleaver = 1;

void create()
{
	::create();
   set_short( "民宅" );
	set_long( @LONG_DESCRIPTION
这是一间平凡的小木屋。当你环顾四周时, 看到所有的
窗户均被钉上木条而封死; 虽然大门敞开, 却有一层厚厚的
布幔遮住了门口, 因此, 纵使是白日, 屋内仍是一片黑暗,
或许\这家人在惧怕什麽吧!
LONG_DESCRIPTION
	);

   set( "objects", ([
           "mother" : IANMOB"liang_mother",
           "girl" : IANMOB"girl" ]) );
	set( "exits", ([ 
          "east" : IAN"hamlet_path2" ]) );
   create_door( "east", "west", ([
                "keyword" : ({ "wooden door", "door" }),
                "name" : "wooden door",
                "c_name" : "木门",
                "c_desc" : "一扇很普通的木门",
                "status" : "locked",
                "lock" : "IANYEU_LIANG_HOME"
        ]) );
   set( "c_item_desc", ([
            "bed" : "一个普普通通的小木床.\n" ]) );
   set( "search_desc", ([
            "bed" : "@@search_bed" ]) );
	reset();
}

void reset()
{
   ::reset();
   cleaver = 1;
}

string search_bed()
{
   object obj;

   if( !cleaver ) return "你找了又找，并没有发现任何东西。\n";

   obj = new( IANOBJ"cleaver" );

   obj->move(this_object());
   cleaver = 0;
   return "你仔细地搜找小木床, 发现了一把屠刀!\n";
}
void init()
{
  if(this_player()) this_player()->set_explore("eastland#20");
}
