// File: /d/eastland/haiwei/inn1.c
// Generated by Roommaker Sat Jan 22 03:02:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("地洞");
        set_long( @C_LONG_DESCRIPTION
这里是一个不见天日的地洞，地面有一些积水，因此有很重的湿气让你觉的混身不
舒服，同时此处的墙壁上有许多狼的爪痕，地面上亦一些狼毛，真不知道这些狼是从
拿□来的。
C_LONG_DESCRIPTION
        );
    set("light",0);
    set("objects",([
        "wolf": "/d/eastland/haiwei/monster/wolf"])); 
        set( "exits", ([ 
                "up" : "/d/eastland/haiwei/cornfield2", 
                "west" : "/d/eastland/haiwei/hole2" ]) );
        reset();
}
