// File: /d/eastland/haiwei/inn1.c
// Generated by Roommaker Sat Jan 22 03:02:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悦来客栈");
        set_long( @C_LONG_DESCRIPTION
你现在正站在一间客栈门前的空地上，门口有几根让客人栓马用的木桩，客栈
的大门敞开著，一串灯笼垂在大柱旁，上面写著「悦来客栈」四个字。往西是一条
青石大道，南边一排大树，树後是一片青翠的田野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad4", 
                "east" : "/d/eastland/haiwei/inn2" ]) );
        set( "objects", ([
                "carter#1": "/d/eastland/haiwei/monster/carter",
                "carter#2": "/d/eastland/haiwei/monster/carter" ]) );
        reset();
#include <replace_room.h>
}
