// File: /d/eastland/haiwei/inn2.c
// Generated by Roommaker Sat Jan 22 03:12:03 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悦来客栈");
        set_long( @C_LONG_DESCRIPTION
这里是海威镇的悦来客栈，往来官道上的旅客和官差都常常在这里休息，在这里
可以打听到各地的消息和传言，这里的店小二非常热心助人，如果你有什麽困难尽管
向他开口，一定会得到帮助。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "up" : "/d/eastland/haiwei/inn3", 
                "west" : "/d/eastland/haiwei/inn1" ]) );
        set( "objects", ([
                "waiter" : "/d/eastland/haiwei/monster/waiter",
                "chief" : "/d/eastland/haiwei/monster/chief_merc",
                "merc#1" : "/d/eastland/haiwei/monster/mercenary",
                "merc#2" : "/d/eastland/haiwei/monster/mercenary",
                "merc#3" : "/d/eastland/haiwei/monster/mercenary"]) );
        reset();
#include <replace_room.h>
}
