// File: /d/eastland/haiwei/inn3.c
// Generated by Roommaker Sat Jan 22 03:19:17 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悦来客栈");
        set_long( @LONG_DESCRIPTION
这里是悦来客栈的二楼上座，喜欢清净和出手阔绰的人都喜欢在这里喝酒聊天
，面对著西边的座位可以看到客栈前的空地和大街，一排绿意盎然的盆栽装饰著靠
窗的扶手，靠东边一座木梯往下通往一楼。
LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "down" : "/d/eastland/haiwei/inn2" ]) );
        reset();
}
