// File: /d/eastland/haiwei/mroad3.c
// Generated by Roommaker Sat Jan 22 02:47:08 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("青石大道");
        set_long( @C_LONG_DESCRIPTION
你现在正走在一条青石板铺成的大道，往东是海威镇的大街，西边是一家镇上
的大财主聂员外开的商店，青石大道由南往北贯通海威镇，往北是一座雄伟的牌楼
，上面刻著「镇海门」三个大字，往南的青石大道通往一片绿油油的田野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad4", 
                "west" : "/d/eastland/haiwei/shop", 
                "north" : "/d/eastland/haiwei/n_gate", 
                "east" : "/d/eastland/haiwei/mroad2" ]) );
        set( "objects", ([ 
                "vender" : "/obj/vendor" ]) );
        reset();
#include <replace_room.h>
}
