// File: /d/eastland/haiwei/mroad1.c
// Generated by Roommaker Sat Jan 22 06:54:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威镇大街");
        set_long( @C_LONG_DESCRIPTION
你现在正走在海威镇的大街上，东边是海威镇中心的路口，南边是鱼市场，不过
从这里没有路进去，北边不远处就是海岸，一些砖瓦屋散布在路旁，为了抵挡海风，
这些屋子都在屋後种了一排排的树木，海威镇的大街往西边延伸出去。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad2", 
                "east" : "/d/eastland/haiwei/road_cross" ]) );
        set( "objects", ([ 
                "beggar" : "/d/eastland/haiwei/monster/beggar" ]) );
        reset();
#include <replace_room.h>
}
