// File: /d/eastland/haiwei/mroad4.c
// Generated by Roommaker Sat Jan 22 13:03:48 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("青石大道");
        set_long( @C_LONG_DESCRIPTION
你现在正走在一条青石大道上，东边是一间两层楼高的客栈，客栈门口插著数
十枝绿色镶白边的旗子(flags)，西边是一家当铺，往南的大道通往一片青翠的田
野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set("item_desc",([
                "flags" : "这几枝旗子看起来像是家镖局的旗帜，上面绣著一个大大的「周」字。\n" ]) );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/hockshop", 
                "north" : "/d/eastland/haiwei/mroad3",
           //     "south" : "/d/eastland/haiwei/cornfield",
               "south" : "/d/eastland/beggar/area/mroad5", 
                "east" : "/d/eastland/haiwei/inn1" ]) );
        reset();
#include <replace_room.h>
}
