// File: /d/eastland/haiwei/n_gate.c
// Generated by Roommaker Fri Jan 21 20:16:14 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("镇海门");
        set_long( @C_LONG_DESCRIPTION
你现在来到一座雄伟的牌楼前，牌楼上的石匾刻著三个龙飞凤舞的大字「镇海
门」，青石道穿过牌楼往北是一条两旁种满木棉树的大道，往南的路口衔接海威镇
的大街，东边一座小茶亭，不过入口不在这一边。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad3", 
                "northwest" : "/d/eastland/16,9.east" ]) );
        set( "objects", ([ 
                "bonze" : "/d/eastland/haiwei/monster/bonze" ]) );
        reset();
#include <replace_room.h>
}
