// File: /d/eastland/haiwei/road_jetty.c
// Generated by Roommaker Tue Dec 28 22:44:58 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威港");
        set_long( @C_LONG_DESCRIPTION
你现在正走在海威镇通往港口的碎石路上，你的西边是一望无际的大海，海岸
边怪石嶙峋，显示海威港得天独厚的地理环境，据说这一带虽然有海盗出没，但是
他们从来不敢攻打海威镇，就是因为海威镇的地形易守难攻，东边的空地上是一列
列晒鱼网的木架，往南不远处是一个鱼市场。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "north" : "/d/eastland/haiwei/jetty", 
                "south" : "/d/eastland/haiwei/road_cross" ]) );
        reset();
#include <replace_room.h>
}
