// File: /d/eastland/haiwei/road_cross.c
// Generated by Roommaker Thu Dec 30 02:14:30 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威镇街道");
        set_long( @C_LONG_DESCRIPTION
你现在站在海威镇中心的路口，北边是一条碎石路，通往海威镇的港口，东边
是海威镇有名的「镇海将军庙」，里面奉祀著三百年前打败入侵的海盗王的镇海大
将军，南边是一个热闹的鱼市场，从这里都可以听见鱼贩叫卖的吆喝声，往西则是
海威镇的大街。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad1", 
                "north" : "/d/eastland/haiwei/road_jetty", 
                "south" : "/d/eastland/haiwei/market1", 
                "east" : "/d/eastland/haiwei/temple_square" ]) );
        reset();
#include <replace_room.h>
}
