// File: /d/eastland/haiwei/tea_shop.c
// Generated by Roommaker Sat Jan 22 02:36:54 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("好茶亭");
        set_long( @C_LONG_DESCRIPTION
你现在来到一个小茶亭，一块碧绿泛著油亮的竹板挂在茶亭的横梁上，上面
用娟秀的字体写著一些价目表(menu)，这里的桌椅大多是竹制的，茶亭的四面都
是透光的竹帘窗，你可以看到北边不远处的海岸以及东北边的码头。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad2" ]) );
        set( "objects", ([ 
                "girl" : "/d/eastland/haiwei/monster/girl" ]) );
        reset();
}
void init()
{ if(this_player()) this_player()->set_explore("eastland#18");
}
