
// File: /d/eastland/haiwei/temple_square.c
// Generated by Roommaker Mon Jan 31 06:47:24 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("庙前广场");
        set_long( @C_LONG_DESCRIPTION
你现在正站在镇海将军庙前的广场，一对神态威武的石狮子(statue)站在庙门
口，广场中央还有一个大香炉(censer)，袅袅的香烟衬托著将军庙宏伟的建筑，营
造出一种虔诚祈福的气氛。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "item_desc", ([ 
                "censer" : "这是一个铜铸的大型香炉，上面刻著「威镇四海，保境卫民」八个大字。\n", 
                "statue" : "这对石狮子因为岁月的关系，上面已经被海风侵蚀出许\多的坑洞。\n" ]) );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/road_cross", 
                "east" : "/d/eastland/haiwei/temple" ]) );
        set( "objects", ([ 
                "martialist" : "/d/eastland/haiwei/monster/entertainer", 
                "sparrow#1" : "/d/eastland/haiwei/monster/sparrow", 
                "sparrow#2" : "/d/eastland/haiwei/monster/sparrow", 
                "sparrow#3" : "/d/eastland/haiwei/monster/sparrow" ]) );
        reset();
#include <replace_room.h>
}
