// File: /d/noden/11,5.noden.c
// Generated by Roommaker Tue Dec 14 12:38:27 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("河流上游");
	set_long( @LONG_DESCRIPTION
你现在沿著河流来到它的上游，你的西边是一座高耸入云的山脉，河流从山上
直泻而下造成一道壮观的瀑布(waterfall)，你发现岸边有一些脚印通往瀑布後面，
难道....，如果你想探个究竟的话，最好先学会游泳再来。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"waterfall" : @LONG_TEXT
这道瀑布从半山腰直泻而下，高度至少有 200 公尺，声势颇为壮观，从河边
草丛的脚印判断，瀑布後面可能有山洞，如果你想穿过(pass)瀑布进入山洞的
话，必须先逆流游到瀑布前面。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "d/noden/11,4.noden", 
		"east" : "d/noden/12,5.noden" ]) );
	set( "original", "d/noden/11,5" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 11 );
	set( "y_coordinate", 5 );
	set( "objects", ([
		"boar" : "/d/noden/monster/boar" ]) );
	reset();
}

void init()
{
	add_action( "do_pass", "pass" );
}

int do_pass(string arg)
{
	if( !arg || arg!="waterfall" )
            return notify_fail(
                    "通过什麽？\n" );
	if( random( (int)this_player()->query_skill("swimming") ) < 20 ) {
               write(
                    "你企图游过瀑布下的急流，但是被湍急的河水给冲回来。\n"
              );
		return 1;
	}
   write(
            "你奋力向瀑布游去，果然不出所料，瀑布後面有一个洞穴！\n"
     );
	this_player()->move_player( "/d/noden/tamumu/cave1", "SNEAK" );
   this_player()->set_explore("noden#27");
	return 1;
}

