// File: /d/noden/13,8.noden.c
// Generated by Roommaker Sun Dec 19 20:10:49 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("森林");
	set_long( @LONG_DESCRIPTION
你现在正走在一片森林之中，在你东边和南边都是空旷的平地，但是这里的
树木长得异常茂密，你注意到有一颗大得很不寻常的暗红色岩石(stone)，上面光
溜溜的，没有任何青苔或藤蔓。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"mark" : "一个小小的蜘蛛符号，不仔细看会误认为是岩石上的小斑点。\n", 
		"stone" : @LONG_TEXT
这块岩石看起来应该是火山地区才有的东西，怎麽会出现在这里？你左看右看
总是觉得似乎有什麽不对劲.....
LONG_TEXT
, 
		"crack" : "这个裂缝不大，不过如果你不怕脏的话，勉强可以挤进去(enter)看。\n" ]) );
	set( "exits", ([ 
		"south" : "d/noden/13,9.noden", 
		"north" : "d/noden/13,7.noden", 
		"west" : "d/noden/12,8.noden", 
		"east" : "d/noden/14,8.noden" ]) );
	set( "objects", ([ 
		"spider" : "/d/noden/monster/spider" ]) );
	set( "original", "d/noden/13,8" );
	set( "search_desc", ([ 
		"stone" : "@@search_stone",
 ]) );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 13 );
	set( "y_coordinate", 8 );
	reset();
}

void init()
{
	add_action( "do_enter", "enter" );
}

string search_stone()
{
    if( this_player() ) this_player()->set_explore("noden#28");
   return
      "你仔细地拨开岩石附近的草丛，发现了一个蜘蛛的符号(mark)，这个符号刻在\n"
        "岩石的一个裂缝(crack)旁边。\n" ;
}

int do_enter(string arg)
{
	if( !arg || arg!="crack" )
            return notify_fail(
                    "进入哪里？\n" );
   write(
            "你小心地挤进窄小的缝隙，突然，脚下一个踩空....\n" );
    tell_room( this_object(),
            this_player()->query("c_name") + "走到岩石後面，你听到一声惊呼，然後人就不见了....\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb1", "SNEAK" );
   tell_room( "/d/noden/tomb/tomb1",
            this_player()->query("c_name") + "从上面的洞口掉了下来。\n",
		this_player() );
	return 1;
}
