// File: /d/noden/16,10.noden.c
// Generated by Roommaker Thu Nov 25 09:27:03 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("河边弯路");
	set_long( @LONG_DESCRIPTION
这条路在这里弯向东方，河流在你的东北方不远处注入大海，路旁许多
修剪整齐的树木笔直地站在道路两旁，你的东边就是繁华热闹的海港都市蓝
沙港，这里一向是许多冒险者常到的交通要道，许多传奇的故事也都以这里
做背景。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/noden/16,11.noden", 
		"north" : "d/noden/16,9.noden", 
		"west" : "d/noden/15,10.noden", 
		"east" : "/d/noden/bluesand/port_r0" ]) );
	set( "objects", ([
	   "chocobo#1" : "/d/noden/moyada/monster/chocobo",
        ]));
	set( "original", "d/noden/16,10" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 16 );
	set( "y_coordinate", 10 );
	reset();
}

int clean_up() { return 0; }
