// File: /d/noden/16,13.noden.c
// Generated by Roommaker Wed Dec 22 14:55:12 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("废弃古屋");
	set_long( @LONG_DESCRIPTION
你现在来到一处荒凉的空地上，北边和西边是一片茂密的森林，南边和东边
则是乌黑恶臭的沼泽地带，在你面前的是一栋看起来荒废了很久的古屋(house)
，屋子的墙壁已经大部分被苔藓(moss)类植物盖满了，大门歪歪斜斜地倒在一旁
，这个景象使你不禁想到小时候所听过的鬼故事。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"house" : @LONG_TEXT
这间屋子大概就是传说中的鬼屋吧，大门没有关，你敢不敢进去(enter)试试
自己的胆量？
LONG_TEXT
, 
		"moss" : @LONG_TEXT
这些苔藓植物看起来青一块、白一块，有的上面还有一些绿色的黏液，实在
有够恶心。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "d/noden/16,14.noden", 
		"north" : "d/noden/16,12.noden", 
		"west" : "d/noden/15,13.noden", 
		"east" : "d/noden/17,13.noden" ]) );
	set( "original", "d/noden/16,13" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 16 );
	set( "y_coordinate", 13 );
	reset();
}

void init()
{
	add_action( "do_enter", "enter" );
}

int do_enter(string arg)
{
	if( !arg || arg!="house" ) return 0;
   write(
            "你小心地跨过颓圮的大门，进入古屋。\n" );
    tell_room( this_object(),
            this_player()->query("c_cap_name") + "跨过颓圮大门，进入古屋。\n",
		this_player() );
	this_player()->move_player( "/d/noden/house/hall", "SNEAK" );
    tell_room( "/d/noden/house/hall",
            this_player()->query("c_cap_name") + "从门外走了进来。\n",
		this_player() );
	return 1;
}

