// File: /d/noden/2,5.noden.c
// Generated by Roommaker Tue Nov 21 00:40:35 1995

#include <mudlib.h>
inherit ROOM;

void create()
{
	::create();
	set_short("森林");
	set_long( @LONG_DESCRIPTION
你现在漫步在一座森林之中，繁茂的树木散发出一股淡淡的、舒爽
宜人的气息，你可以听到树林间小鸟吱吱喳喳的鸣叫声，脚底下一层落
叶(leaves)铺满了你所站立的地方，底下似乎藏著什麽东西。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"east" : "d/noden/3,5.noden", 
		"north" : "d/noden/2,4.noden", 
		"south" : "d/noden/2,6.noden" ]) );
	reset();
}

void init()
{
	add_action("do_search","search");
	add_action("do_enter","enter");	
}

int do_search(string s)
{
	if (!s || s != "leaves")
		return notify_fail("你找了又找，并没有发现任何东西。\n");
	tell_object(this_player(),@LONG
你仔细察看四周，竟然在西边的树荫下找到一个被树叶盖住的小洞，看起来
像是某样东西的入口(entrance)，你想进去(enter) 看看吗？
LONG
	);
	return 1;
}

int do_enter(string s)
{
	if (!s || s != "entrance")
		return notify_fail("你要进哪里？\n");
	this_player()->move_player("/d/noden/hawk/tomb.c","SNEAK");
	return 1;
}

