// File: /d/noden/6,6.noden.c
// Generated by Roommaker Tue Dec 14 10:53:39 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("森林");
	set_long( @LONG_DESCRIPTION
你现在漫步在一座森林之中，繁茂的树木散发出一股淡淡的、
舒爽宜人的气息，你可以听到树林间小鸟吱吱喳喳的鸣叫声，脚底
下一层落叶铺满了你所站立的地方。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"west" : "d/noden/5,6.noden" ]) );
	set( "original", "d/noden/6,6" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 6 );
	set( "y_coordinate", 6 );
	reset();
}
void init()
{
  if(!find_object("/d/island/island_gate"))
  {
    "/d/island/island_gate"->frog();
  }
  if( this_player() && find_object( "/d/island/island_gate" ) )
     this_player()->set_explore("noden#29");
}  
