// File: /d/noden/6,9.noden.c
// Generated by Roommaker Sat May 14 04:32:03 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("路口");
	set_long( @LONG_DESCRIPTION
你现在来到了一处交叉路口，往北直走的路可以到达诺达尼亚城，也
就是王宫的所在地。往南的路沿著贝尔基山向西南方走，可以到达魔法之
都摩亚达。往东一条笔直的大路是通往诺顿王国东方的主要道路，向东一
直走下去可以到达坎达拉峡谷。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/noden/6,10.noden", 
		"north" : "d/noden/6,8.noden", 
		"west" : "d/noden/5,9.noden", 
		"east" : "d/noden/7,9.noden" ]) );
	set( "objects", ([
	    "black chocobo#1" : "/d/noden/moyada/monster/black_chocobo",
	    ])); 	
	set( "original", "d/noden/6,9" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 6 );
	set( "y_coordinate", 9 );
	reset();
}

int clean_up() { return 0; }
