// File: /d/noden/10,10.noden.c
// Generated by Roommaker Tue Nov 21 00:21:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山脚");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一座高大山峰的山脚下，北边是一条碎石路，你的东北边是一个
峡谷，这里的地势稍高，你发现地上似乎有一些马车走过的痕迹，一条蜿蜒曲折
的山路通往西南边的山上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/path1", 
		"east" : "d/noden/11,10.noden", 
		"north" : "d/noden/10,9.noden" ]) );
	ob->set( "original", "d/noden/10,10" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 10 );
	ob->set( "y_coordinate", 10 );
	ob->reset();
}
