// File: /d/noden/11,10.noden.c
// Generated by Roommaker Tue Nov 21 00:23:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/12,10.noden", 
		"west" : "d/noden/10,10.noden", 
		"north" : "d/noden/11,9.noden", 
		"south" : "d/noden/11,11.noden" ]) );
	ob->set( "objects", ([ 
		"beetle#3" : "/d/noden/monster/beetle", 
		"beetle#2" : "/d/noden/monster/beetle", 
		"beetle#1" : "/d/noden/monster/beetle" ]) );
	ob->set( "original", "d/noden/11,10" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 11 );
	ob->set( "y_coordinate", 10 );
	ob->reset();
}
