// File: /d/noden/13,7.noden.c
// Generated by Roommaker Tue Nov 21 00:27:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河边森林");
	ob->set_long( @LONG_DESCRIPTION
你现在正沿著河边的林中小径漫步，北边的河流日夜不停的流著，这里
的空气有些潮湿，但是凉爽的微风使你觉得全身舒畅。通往远风镇的道路就
在你的东边，但是如果你愿意的话，也可以经由你东北边的石板桥进入远风
镇。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/14,7.noden", 
		"south" : "d/noden/13,8.noden", 
		"west" : "d/noden/12,7.noden", 
		"northeast" : "/d/noden/farwind/bridge" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"snake" : "/d/noden/monster/snake", 
		"snake#2" : "/d/noden/monster/snake" ]) );
	ob->set( "original", "d/noden/13,7" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 13 );
	ob->set( "y_coordinate", 7 );
	ob->reset();
}
