// File: /d/noden/13,5.noden.c
// Generated by Roommaker Tue Nov 21 00:26:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河边小径");
	ob->set_long( @LONG_DESCRIPTION
你现在正沿著河边的小径前进，河边不少的鹅卵石杂乱地排列著，往东
你可以看见一片田野与交错的小径，河流在你的南边缓缓流过，一条沿著河
床的小路向东南通往与远风镇西边的石板桥，西边不远处有几座低矮的山丘
。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/14,5.noden", 
		"north" : "d/noden/13,4.noden", 
		"west" : "d/noden/12,5.noden", 
		"southeast" : "/d/noden/farwind/bridge" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "original", "d/noden/13,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 13 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
