// File: /d/noden/14,5.noden.c
// Generated by Roommaker Mon Nov 20 12:38:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("远风镇郊区");
	ob->set_long( @LONG_DESCRIPTION
现在在你面前的是一片绿油油的田野，青翠的农作物与疏落的农舍散布
在田野间，这里宁静的乡村气息使你感觉十分亲切。在你的北方与西方不远
处散布著一些低矮的山丘，东边则是一片森林，往南走就是远风镇的大街。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/15,5.noden", 
		"south" : "/d/noden/farwind/nmain", 
		"north" : "d/noden/14,4.noden", 
		"west" : "d/noden/13,5.noden" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"wife" : "/d/noden/monster/farmer_wife", 
		"farmer" : "/d/noden/monster/farmer" ]) );
	ob->set( "original", "d/noden/14,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
