// File: /d/noden/14,9.noden.c
// Generated by Roommaker Mon Nov 20 12:34:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("交叉路口");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了一处交叉路口，这条路在这里分成三个方向，往北的
路通往冒险者的故乡远风镇，往东边的路可以到达蓝沙港市，西边的大
路穿过远方山脉中间的坎达拉峡谷，衔接通往诺顿王国西半部的要道。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/15,9.noden", 
		"west" : "d/noden/13,9.noden", 
		"north" : "d/noden/14,8.noden", 
		"south" : "d/noden/14,10.noden" ]) );
	ob->set( "objects", ([ 
		"ghoul" : "/d/noden/monster/ghoul", 
		"troll" : "/d/noden/monster/troll" ]) );
	ob->set( "original", "d/noden/14,9" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
