// File: /d/noden/15,5.noden.c
// Generated by Roommaker Tue Nov 21 00:31:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草地");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片绿油油的草地上，青翠的草地带著令人愉悦的
气息。几丛植物散布在碧绿的草地间，点缀著五彩缤纷的不知名野
花，使人心旷神宜。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/16,5.noden", 
		"west" : "d/noden/14,5.noden", 
		"north" : "d/noden/15,4.noden", 
		"south" : "d/noden/15,6.noden" ]) );
	ob->set( "original", "d/noden/15,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 15 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
