// File: /d/noden/15,6.noden.c
// Generated by Roommaker Mon Nov 20 12:40:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河边林地");
	ob->set_long( @LONG_DESCRIPTION
你现在来到森林靠近河边的一块林地，河流在你的南方缓缓流过，潺潺的
流水声和林间的虫吟鸟鸣交织成一首美丽的交响曲，你的西边是远风镇的围墙
，但是从这里没有通往镇上的入口。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/16,6.noden", 
		"north" : "d/noden/15,5.noden" ]) );
	ob->set( "objects", ([ 
		"crow" : "/d/noden/monster/crow" ]) );
	ob->set( "original", "d/noden/15,6" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 15 );
	ob->set( "y_coordinate", 6 );
	ob->reset();
}
