// File: /d/noden/16,18.noden.c
// Generated by Roommaker Tue Nov 21 00:33:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("道路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条碎石铺成的道路上，沿著道路往南你可以看到精灵村,
那是一个美丽的世外桃源，不知你是否有兴趣到此一游。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/noden/elf/elf/elf1", 
		"north" : "d/noden/16,17.noden" ]) );
	ob->set( "original", "d/noden/16,18" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 16 );
	ob->set( "y_coordinate", 18 );
	ob->reset();
}
