// File: /d/noden/17,7.noden.c
// Generated by Roommaker Mon Nov 20 12:41:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片平地上，疏落的青草点缀著一些碎石，这里开阔的视
野使你可以清楚地看到远方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/18,7.noden", 
		"west" : "d/noden/16,7.noden", 
		"north" : "d/noden/17,6.noden", 
		"south" : "d/noden/17,8.noden" ]) );
	ob->set( "objects", ([ 
		"orc#1" : "/d/noden/monster/young_orc", 
		"orc#2" : "/d/noden/monster/young_orc" ]) );
	ob->set( "original", "d/noden/17,7" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 17 );
	ob->set( "y_coordinate", 7 );
	ob->reset();
}
