// File: /d/noden/17,11.noden.c
// Generated by Roommaker Tue Nov 21 00:33:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白色沙滩");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一处铺满白色沙子的美丽海滩，白沙中点点宝蓝色的细点
将沙滩妆点出一种神秘迷人的气氛，美丽的蓝沙港就在你的北方不远处，
可是这里没有入口可以进入蓝沙港。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/18,11.noden", 
		"west" : "d/noden/16,11.noden", 
		"south" : "d/noden/17,12.noden" ]) );
	ob->set( "original", "d/noden/17,11" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 17 );
	ob->set( "y_coordinate", 11 );
	ob->reset();
}
