// File: /d/noden/18,4.noden.c
// Generated by Roommaker Tue Nov 21 00:35:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("岩岸");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一处突出岸边的岩石上，在你的脚下是个约有五公尺高的悬崖(cliff)
，这里是诺顿大陆的东北角，附近的居民把这里叫做「蝙蝠角」，据说悬崖下住著一
大群蝙蝠，这里的视野相当开阔，天气好的时侯可以望见东北方的古拉干岛。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/noden/18,5.noden", 
		"west" : "d/noden/17,4.noden" ]) );
	ob->set( "original", "d/noden/18,4" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 18 );
	ob->set( "y_coordinate", 4 );
        ob->set( "objects",([ "mob4":"/d/noden/recamp/npc/mob4.c" ])) ;
	ob->reset();
}
