// File: /d/noden/2,15.noden.c
// Generated by Roommaker Tue Nov 21 00:39:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草地");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一片绿油油的草地上，青翠的草地带著令人愉悦的
气息。几丛植物散布在碧绿的草地间，点缀著五彩缤纷的不知名野
花，使人心旷神宜。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/3,15.noden", 
		"west" : "d/noden/1,15.noden", 
		"north" : "d/noden/2,14.noden", 
		"south" : "d/noden/2,16.noden" ]) );
	ob->set( "original", "d/noden/2,15" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 2 );
	ob->set( "y_coordinate", 15 );
        ob->set( "objects", (["mob5":"/d/noden/recamp/npc/mob5.c"])) ;
	ob->reset();
}
