// File: /d/noden/6,13.noden.c
// Generated by Roommaker Tue Nov 21 00:44:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖著举目所及的山丘，几株大树散
布在山坡上。西边是魔法之都——摩亚达城，一个力场保护著它。
这里有座巨大的石梯，一直往山上蜿蜒而上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"up" : "/d/noden/asterism/ladder01", 
		"north" : "d/noden/6,12.noden" ]) );
	ob->set( "original", "d/noden/6,13" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 6 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
