// File: /d/noden/7,10.noden.c
// Generated by Roommaker Tue Nov 21 00:45:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖著举目所及的山丘，几株大树散
布在山坡上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/8,10.noden", 
		"west" : "d/noden/6,10.noden", 
		"north" : "d/noden/7,9.noden", 
		"south" : "d/noden/7,11.noden" ]) );
	ob->set( "objects", ([ 
		"falcon" : "/d/noden/monster/falcon" ]) );
	ob->set( "original", "d/noden/7,10" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 7 );
	ob->set( "y_coordinate", 10 );
	ob->reset();
}
