// File: /d/noden/8,14.noden.c
// Generated by Roommaker Tue Nov 21 00:45:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘组成的丘陵地上，这里的地势起伏
并不很大，青黄交错的短草皮覆盖著举目所及的山丘，几株大树散
布在山坡上。你注意到北边竟有一座很大的森林。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exit_suppress", ({ 
		"north" }) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/9,14.noden", 
		"north" : "/d/noden/forest/entry", 
		"south" : "/d/noden/8,15.noden" ]) );
	ob->set( "original", "d/noden/8,14" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 8 );
	ob->set( "y_coordinate", 14 );
	ob->reset();
}
