// File: /d/noden/9,9.noden.c
// Generated by Roommaker Tue Nov 21 00:47:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("坎达拉峡谷");
	ob->set_long( @LONG_DESCRIPTION
这里是坎达拉峡谷，高耸的山脉挡住了南方及北方的通路。这里
是接通诺顿王国东西交通的主要通道，从前这里本来有一座堡垒以守
御天险，但是自从魔法师们发现了传送法术的奥秘之後，这里的军事
价值就没有那麽重要了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/10,9.noden", 
		"west" : "d/noden/8,9.noden" ]) );
	ob->set( "objects", ([ 
		"bandit 2" : "/d/noden/monster/bandit" ]) );
	ob->set( "original", "d/noden/9,9" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 9 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
