// File: /d/deathland/palace/pa_01.c
// Generated by Roommaker Thu Nov 23 20:35:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇宫大厅");
	ob->set_long( @LONG_DESCRIPTION
这里是皇宫的大厅,但是除了周围的墙壁是用纯金砌成的外,与其他矮人的
建筑物并无太大的不同.而且这建筑物的造形非常呆板,显示矮人缺乏艺术修养
.大厅的北方是一间会议室,而东方则是矮人皇室的起居室.南方是仆人的住所.
西方是皇宫通往外面的出口.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_02", 
		"north" : "/d/deathland/palace/pa_04", 
		"south" : "/d/deathland/palace/pa_03", 
		"west" : "/d/deathland/city/c7" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/deathland/monster/royal01", 
		"guard#1" : "/d/deathland/monster/royal01" ]) );
	ob->reset();
}
