// File: /d/deathland/palace/pa_03.c
// Generated by Roommaker Thu Nov 23 20:36:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇宫走廊");
	ob->set_long( @LONG_DESCRIPTION
皇宫走廊,标准的矮人建筑特色,笔直,刻板,单调.这走廊连接著大厅与仆人
的住所.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/palace/pa_01", 
		"south" : "/d/deathland/palace/pa_06" ]) );
	ob->reset();
}
