// File: /d/deathland/palace/pa_06.c
// Generated by Roommaker Thu Nov 23 20:37:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("仆人的住所");
	ob->set_long( @LONG_DESCRIPTION
许\多仆人忙进忙出的,虽然矮人皇室的成员不多,但是仆人的工作仍是很忙
碌的. 这里是仆人的住所,一些床与衣橱\摆\在角落,而中央放著一张饭桌与几个
椅子.往北是通往大厅的走廊.而东边似乎是一个很大的广场.
的住所.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_07", 
		"north" : "/d/deathland/palace/pa_03" ]) );
	ob->set( "objects", ([ 
		"servant#3" : "/d/deathland/monster/servant", 
		"servant#2" : "/d/deathland/monster/servant", 
		"servant#1" : "/d/deathland/monster/servant" ]) );
	ob->reset();
}
