// File: /d/eastland/forest/2,2.forest.c
// Generated by Roommaker Fri Nov 24 00:03:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的内部");
	ob->set_long( @LONG_DESCRIPTION
你现在正身处於猛兽森林的内部，狂暴的气息令人不寒而栗，尤其是
此起彼落的野兽狂啸声，更是让人胆颤心惊。要是没有什麽重要的事，还
是不要冒险较好。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exit_suppress", ({ 
		"west" }) );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/1,1.forest", 
		"northwest" : "/d/eastland/forest/1,3.forest", 
		"west" : "/d/eastland/forest/0,2.forest", 
		"southeast" : "/d/eastland/forest/3,1.forest", 
		"northeast" : "/d/eastland/forest/3,3.forest" ]) );
	ob->set( "objects", ([ 
		"elephant#1" : "/d/eastland/forest/monster/elephant", 
		"elephant#0" : "/d/eastland/forest/monster/elephant" ]) );
	ob->reset();
}
