// File: /d/eastland/forest/2,4.forest.c
// Generated by Roommaker Fri Nov 24 12:44:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的内部");
	ob->set_long( @LONG_DESCRIPTION
你现在正身处於猛兽森林的内部，狂暴的气息令人不寒而栗，尤其是
此起彼落的野兽狂啸声，更是让人胆颤心惊。要是没有什麽重要的事，还
是快快回头的好。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/1,3.forest", 
		"southeast" : "/d/eastland/forest/3,3.forest" ]) );
	ob->reset();
}
