// File: /d/eastland/forest/3,1.forest.c
// Generated by Roommaker Fri Nov 24 00:08:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深处");
	ob->set_long( @LONG_DESCRIPTION
这里是猛兽森林的深处，树木非常地茂盛，连阳光都无法进入，因此也
显得格外的阴森。当你向四周围望去，你发现黑暗中有无数双碧□闪烁的眼
睛正邪恶地注视著你，令你有毛骨耸然的感觉，恨不得拔腿就跑。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/2,0.forest", 
		"northwest" : "/d/eastland/forest/2,2.forest", 
		"east" : "/d/eastland/forest/4,1.forest" ]) );
	ob->reset();
}
