// File: /d/eastland/forest/4,3.forest.c
// Generated by Roommaker Fri Nov 24 12:45:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深处");
	ob->set_long( @LONG_DESCRIPTION
这里是猛兽森林的深处，树木非常地茂盛，连阳光都无法进入，因此也
显得格外的阴森。当你向四周围望去，你发现黑暗中有无数双碧□闪烁的眼
睛正邪恶地注视著你，要不是为了寻找传说中的灵兽，谁也不愿意到这种鬼
地方来。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/eastland/forest/5,3.forest", 
		"west" : "/d/eastland/forest/3,3.forest", 
		"south" : "/d/eastland/forest/4,2.forest" ]) );
	ob->set( "objects", ([ 
		"lion#1" : "/d/eastland/forest/monster/lion", 
		"lion#0" : "/d/eastland/forest/monster/lion" ]) );
	ob->reset();
}
