// File: /d/eastland/forest/5,1.forest.c
// Generated by Roommaker Fri Nov 24 12:48:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深处");
	ob->set_long( @LONG_DESCRIPTION
这里是猛兽森林的深处，树木非常地茂盛，连阳光都无法进入，因此也
显得格外的阴森。当你向四周围望去，你发现黑暗中有无数双碧□闪烁的眼
睛正邪恶地注视著你，令你有毛骨耸然的感觉，恨不得拔腿就跑。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/forest/4,1.forest", 
		"southeast" : "/d/eastland/forest/6,0.forest", 
		"northeast" : "/d/eastland/forest/6,2.forest" ]) );
	ob->set( "objects", ([ 
		"gorilla#1" : "/d/eastland/forest/monster/gorilla", 
		"gorilla#0" : "/d/eastland/forest/monster/gorilla" ]) );
	ob->reset();
}
