// File: /d/eastland/forest/6,2.forest.c
// Generated by Roommaker Fri Nov 24 12:46:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的内部");
	ob->set_long( @LONG_DESCRIPTION
你现在正身处於猛兽森林的内部，狂暴的气息令人不寒而栗，尤其是
此起彼落的野兽狂啸声，更是让人胆颤心惊。要是没有什麽重要的事，还
是不要冒险较好。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exit_suppress", ({ 
		"east" }) );
	ob->set( "exits", ([ 
		"northwest" : "/d/eastland/forest/5,3.forest", 
		"southwest" : "/d/eastland/forest/5,1.forest", 
		"east" : "/d/eastland/forest/8,2.forest", 
		"northeast" : "/d/eastland/forest/7,3.forest", 
		"southeast" : "/d/eastland/forest/7,1.forest" ]) );
	ob->reset();
}
