// File: /d/eastland/forest/7,3.forest.c
// Generated by Roommaker Fri Nov 24 12:46:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的边缘");
	ob->set_long( @LONG_DESCRIPTION
你现在所在的地方是一片茂密的森林，似乎就是人们所说的猛兽森林
。传说猛兽森林中有很多凶猛的野兽，有不少的人在此失踪，如果没有什
麽重要的事，千万不要随便进入森林内部。                
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/6,2.forest", 
		"northwest" : "/d/eastland/forest/6,4.forest", 
		"southeast" : "/d/eastland/forest/8,2.forest" ]) );
	ob->reset();
}
