//  File  :  /include/mudlib.h
//
//  Standard mudlib object file locations

#define OBJECT                  "/std/object/ob"
#define CONTAINER_OBJECT "/std/object/container_ob"
#define SECURE_OBJECT   "/std/object/sec_ob"
#define USER                    "/std/user"
#define TEST_USER       "/std/user_test"        // add for test by Ruby
#define NPC             "/std/npc"
#define BODY_BASE               "/std/body"
#define ROOM_OBJECT                     "/std/object/room_ob"
#define ROOM                    "/std/room/room"
#define DAEMON                  "/std/cmd_m"
#define WEAPON                  "/std/weapon/weapon"
#define ARMOR                   "/std/armor/armor"
#define MONSTER                 "/std/npc"
#define LIVING                  "/std/living"
#define GHOST                   "/std/ghost"
#define CONTAINER               "/std/container"
#define COINVALUE               "/std/coinvalue"
#define LOCK                    "/std/lock"
#define DOORS                   "/std/doors"
#define GUILD                   "/u/s/sage/guild/guild" 
// #define GUILD                   "/std/guild" 
#define MAP                             "/std/std_map"
#define MOUNT                   "/std/mount"
#define GUILD_OB        "/u/s/sage/guild/std/guild_ob"
//#define GUILD_OB                "/std/guild_ob"
#define SHOP            "/std/room/shop"
#define SELLER          "/std/seller"
#define SOCIAL_GUILD    "/std/social_guild"
#define SOCIAL_GUILD_OB "/std/social_guild_ob"
#define EXPLORE         "/std/explore"
#define TEACHER         "/std/teacher"
#define SAVE            "/std/save"
#define MESSAGE                 "/std/message"


// Some defined medicines.
#define MEDICINE                "/std/medicine/medicine"
#define HERB            "/std/medicine/herb"
#define POTION          "/std/medicine/potion"
#define PILL            "/std/medicine/pill"
//  File  :  /include/mudlib.h
//
//  Standard mudlib object file locations

#define OBJECT                  "/std/object/ob"
#define CONTAINER_OBJECT "/std/object/container_ob"
#define SECURE_OBJECT   "/std/object/sec_ob"
#define USER                    "/std/user"
#define TEST_USER       "/std/user_test"        // add for test by Ruby
#define NPC             "/std/npc"
#define BODY_BASE               "/std/body"
#define ROOM_OBJECT                     "/std/object/room_ob"
#define ROOM                    "/std/room/room"
#define DAEMON                  "/std/cmd_m"
#define WEAPON                  "/std/weapon/weapon"
#define ARMOR                   "/std/armor/armor"
#define MONSTER                 "/std/npc"
#define LIVING                  "/std/living"
#define GHOST                   "/std/ghost"
#define CONTAINER               "/std/container"
#define COINVALUE               "/std/coinvalue"
#define LOCK                    "/std/lock"
#define DOORS                   "/std/doors"
#define GUILD                   "/u/s/sage/guild/guild" 
// #define GUILD                   "/std/guild" 
#define MAP                             "/std/std_map"
#define MOUNT                   "/std/mount"
#define GUILD_OB                "/std/guild_ob"
#define SHOP            "/std/room/shop"
#define SELLER          "/std/seller"
#define SOCIAL_GUILD    "/std/social_guild"
#define SOCIAL_GUILD_OB "/std/social_guild_ob"
#define EXPLORE         "/std/explore"
#define TEACHER         "/std/teacher"
#define SAVE            "/std/save"
#define MESSAGE                 "/std/message"


// Some defined medicines.
#define MEDICINE                "/std/medicine/medicine"
#define HERB            "/std/medicine/herb"
#define POTION          "/std/medicine/potion"
#define PILL            "/std/medicine/pill"
