// File: /d/abyss/hell/bridge.c
// Generated by Roommaker Wed Jan  5 09:52:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "奈何桥");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在正站在一座青石板砌成的巨大拱桥上，桥的北方有一座城楼，你可以隐约
地看见城楼上一块乌黑大匾上写著「酆都城」三个大字，石桥两边的栏杆上雕著许多
奇异的文字，一阵「轰隆轰隆」的声音从桥下(down)传来，听起来不像是水流的声音
。你回首望向桥的南边，只见一片白茫茫中隐约地有一片青山绿水。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"down" : @LONG_TEXT
你靠近桥边，探头往桥底下望去，差点没吓得喊了出来，只见一片殷红的血池
中翻滚著无以数计的黑色小蛇，血池里还有一些不知是人还是什麽的断肢残骸，有
些人还有知觉，正张大了嘴想要哀号，却发不出半点声音。
LONG_TEXT
 ]) );
	set( "exits", ([ 
/*		"south" : "/d/abyss/hell/bridge", */
                "south" : "/d/abyss/entrance/start",
/*		"north" : "/d/abyss/hell/bridge" ]) );*/
                "north" : "/d/abyss/hell/gate" ]));
	reset();
}
