// File: /d/abyss/hell/gate.c
// Generated by Roommaker Wed Jan  5 09:58:34 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "酆都城城门");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在来到了一座巨大城门的门口，城门上高高地悬挂著一幅乌木大匾，上面
写著「酆都城」三个大字，城门大开，你往城里看去，只见鬼影幢幢，一堆白影飘
来飘去，南边一座青石板砌成的巨大拱桥，桥头的石狮下刻著「奈何桥」。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"north" : "/d/abyss/hell/street1", 
		"south" : "/d/abyss/hell/bridge" ]) );
	reset();
}
