// File: /d/abyss/hell/hall.c
// Generated by Roommaker Wed Jan  5 09:38:36 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "森罗殿");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在正位於一间充满鬼气的大殿上，这里的光线十分阴暗，但是你仍然可以
很清楚地看见周遭的事物，大殿的北端是一道阶梯，阶梯上端放著一张巨大的乌木
桌子，两旁林立著数十根双人合抱的火红色圆柱，圆柱後面站著两排不知是人还是
雕像的黑影，你感觉到自己正被好几十双眼睛注视著，一种恐惧夹杂著不安的情绪
正萦绕在你的脑中。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "objects", ([
		"horseface" : "/d/abyss/hell/monster/horseface",
		"bullhead" : "/d/abyss/hell/monster/bullhead",
		"judge" : "/d/abyss/hell/monster/judge",
		"lord_chinguan" : "/d/abyss/hell/monster/lord_chinguan"]) );
	reset();
}
