// File: /d/abyss/hell/monpoh_bower.c
// Generated by Roommaker Wed Jan  5 11:27:32 1994

#include "hell.h"

inherit ROOM;

void create()
{
	::create();
	set_short("Monpoh place", "孟婆亭");
	set_long( @LONG_DESCRIPTION
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你来到一个有著浓绿树荫的小茶亭，凉亭旁的大树垂挂著一块木牌(sign)，上面
写著「孟婆亭」及几行小字。你放眼四周，全是白茫茫的一片，头顶上好像有十个大
太阳在照著一般，令你觉得酷热难当，还是进亭子去歇一会儿吧。
C_LONG_DESCRIPTION
	);

    set("item_func",([
        "sign":"look_sign",]) );
	set( "light", 1 );
    set("exits",([
              "east":"/d/abyss/hell/street2"
                 ]));
	reset();
}

int look_sign()
{
    write("这木牌上写著:免费招待孟婆汤.\n");
    return 1;
}
