// File: /d/abyss/hell/street1.c
// Generated by Roommaker Wed Jan  5 10:07:43 1994

#include "hell.h"

inherit ROOM;

void create()
{
	::create();
	set_short("Street of ghost city", "酆都城街道");
	set_long( @LONG_DESCRIPTION
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在正走在酆都城的街道上，你看见四周的建筑物都黑黝黝地矗立著，一片白
茫茫的雾气笼罩著这里，分不出是白天还是黑夜。许多白色的人影在你的身边飘来飘
去，但是全都静悄悄地没有任何声音，你感到一股寒气正在啃噬你的神智，也许在这
种地方呆太久你会疯掉....。
往南边走出城门就是奈何桥了, 听说一但过了奈何桥就能重返阳间, 不必受轮回之苦.
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"south" : Hell"/gate",
		"north" : Hell"/street4",
		"west" : Hell"/street2", 
		"east" : Hell"/street3" ]) );
	reset();
}
