// File: /d/abyss/hell/street4.c
// Generated by Roommaker Wed Jan  5 10:09:51 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "酆都城街道");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在正走在酆都城的街道上，你看见四周的建筑物都黑黝黝地矗立著，一片白
茫茫的雾气笼罩著这里，分不出是白天还是黑夜。许多白色的人影在你的身边飘来飘
去，但是全都静悄悄地没有任何声音，你感到一股寒气正在啃噬你的神智，也许在这
种地方呆太久你会疯掉....。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"north" : "/d/abyss/hell/street1", 
		"south" : "/d/abyss/hell/street2", 
		"west" : "/d/abyss/hell/street3", 
		"east" : "/d/abyss/hell/street4" ]) );
	reset();
}
