// File: /d/noden/nodania/alley2.c
// Generated by Roommaker Mon Dec  4 19:49:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阴暗小巷");
	ob->set_long( @LONG_DESCRIPTION
这是一条阴暗的小巷子，脏乱狭窄的路面上到处都是垃圾，即使是像
诺达尼亚这样的大城市，也依然有贫穷的存在。巷子的东方隐隐约约有人
说话的声音，但是在这里听不清楚。
    你从说话的声音，可以辨别得出来，好像是吟诵某种咒文的声音。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/dump", 
		"west" : "/d/noden/nodania/alley1" ]) );
	ob->set( "objects", ([ 
		"spy" : "/d/noden/nodania/monster/moorth_spy" ]) );
	ob->reset();
}
