// File: /d/noden/nodania/alley1.c
// Generated by Roommaker Mon Dec  4 19:49:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阴暗小巷");
	ob->set_long( @LONG_DESCRIPTION
这是一条阴暗的小巷子，脏乱狭窄的路面上到处都是垃圾，即使是像
诺达尼亚这样的大城市，也依然有贫穷的存在。巷子的东方隐隐约约有人
说话的声音，但是在这里听不清楚。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/alley2", 
		"west" : "/d/noden/nodania/nodania_r1" ]) );
	ob->set( "objects", ([ 
		"cat" : "/d/noden/nodania/monster/cat" ]) );
	ob->reset();
}
