// File: /d/noden/nodania/barrack.c
// Generated by Roommaker Mon Dec  4 19:50:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇家骑士团军营");
	ob->set_long( @LONG_DESCRIPTION
你现在来到皇家骑士团的军营，这里是武器专家们训练骑士使用
武器战斗的所在地。墙边有一个排满各式武器的架子，北边传来阵阵
金属碰撞与战斗呼喝的声音。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/nodania/e_path2", 
		"north" : "/d/noden/nodania/yard1" ]) );
	ob->set( "objects", ([ 
		"squire#2" : "/d/noden/nodania/monster/squire", 
		"squire#1" : "/d/noden/nodania/monster/squire" ]) );
	ob->reset();
}
