// File: /d/noden/nodania/castle_r2.c
// Generated by Roommaker Mon Dec  4 19:53:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城堡路，诺达尼亚");
	ob->set_long( @LONG_DESCRIPTION
城堡路沿著诺达尼亚城的城墙往东西向延伸，路旁种了不少树木及
矮树丛。在你的西方可以看到城堡的南门。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/castle_r3", 
		"west" : "/d/noden/nodania/s_gate" ]) );
	ob->reset();
}
