// File: /d/noden/nodania/collection.c
// Generated by Roommaker Mon Dec  4 19:59:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("收藏室");
	ob->set_long( @LONG_DESCRIPTION
这是皇后依莉雅的收藏室，国王和皇后都很喜欢收集来自世界各地的
珍奇宝物，并且展示给他们的宾客看。依莉雅皇后的珍藏十分丰富，其中
以一套镶满翡翠的盔甲(armor)和一只用龙的牙齿雕成的鹦鹉(parrot) 最
引人注目。往东走可以回到议事厅。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"armor" : @LONG_TEXT
这套盔甲上面据说镶了超过两万片上等的翡翠，并且经过强大的魔法加以
祝福，能保护穿它的人不受邪恶魔法的伤害。
LONG_TEXT
, 
		"parrot" : @LONG_TEXT
这是一只用龙的牙齿雕成的鹦鹉，虽然它的大小和一般的鹦鹉差了很多，但
是至少有十名以上的王宫仆役都曾发誓过他们听到这只鹦鹉说话。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/throne_room", 
		"west" : "/d/noden/nodania/tower1" ]) );
	ob->set( "objects", ([ 
		"queen" : "/d/noden/nodania/monster/iriah" ]) );
	ob->reset();
}
