// File: /d/noden/nodania/courtyard.c
// Generated by Roommaker Mon Dec  4 20:00:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宫前庭");
	ob->set_long( @LONG_DESCRIPTION
这里是王宫的前庭，一片绿地上布置著几丛花树。国王耶拉曼十一世的
宫殿就在前方，东边一条石板铺成的小径通往皇家骑士团的军营，往西是国
王的马场。王宫大门就在你的南边。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/e_path", 
		"west" : "/d/noden/nodania/w_path", 
		"south" : "/d/noden/nodania/s_gate", 
		"north" : "/d/noden/nodania/palace_hall" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/noden/nodania/monster/palace_guard", 
		"guard#1" : "/d/noden/nodania/monster/palace_guard", 
		"gardener" : "/d/noden/nodania/monster/gardener" ]) );
	ob->reset();
}
