// File: /d/noden/nodania/dump.c
// Generated by Roommaker Mon Dec  4 20:00:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("垃圾堆");
	ob->set_long( @LONG_DESCRIPTION
小巷子到这里成了死巷，在你面前的是一堆垃圾(debris)、瓦砾(rubbles)
与一大堆各式各样的废弃物，很显然的，穷人们把这里当作垃圾场，你向这些垃
圾只看了一眼，就可以确定里面绝对不会有任何有价值的东西。一阵低沈缓慢的
吟诵从东边的墙(wall)後面传出，但是你并没有发现任何出口，唯一值得注意的
只是离地面约三、四公尺高的地方有一扇窗子(window)。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/alley2" ]) );
	ob->set( "item_desc", ([ 
		"rubbles" : "一堆碎石和破瓦片，也许是某户人家修补墙壁所留下来的。\n", 
		"window" : "那扇窗户紧闭著，但是从这里看不到屋子里的情形。\n", 
		"wall" : "这面墙比其他方向的墙看起来新，大概是新盖好的。\n", 
		"debris" : "这堆垃圾多半是吃剩的食物和纸张，看起来怪恶心的。\n" ]) );
	ob->set( "objects", ([ 
		"child2" : "/d/noden/nodania/monster/poor_child", 
		"child1" : "/d/noden/nodania/monster/poor_child" ]) );
	ob->reset();
}
