// File: /d/noden/nodania/e_hall.c
// Generated by Roommaker Mon Dec  4 20:01:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宫回廊");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫中的一处回廊，往东走你可以到达王宫的厨房，
西边是王宫入口的大厅。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/kitchen", 
		"west" : "/d/noden/nodania/palace_hall" ]) );
	ob->reset();
}
