// File: /d/noden/nodania/e_path2.c
// Generated by Roommaker Mon Dec  4 20:02:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板小径");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一条石板铺成的小径，两旁生著疏疏落落的灌木丛。小
径通往北边和西边。东边一座碉堡般的建筑物，想必就是诺顿王国的主
力骑士公会。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/knight/fortress/knight_guild", 
		"north" : "/d/noden/nodania/barrack", 
		"west" : "/d/noden/nodania/e_path" ]) );
	ob->reset();
}
