// File: /d/noden/nodania/greeting_hall.c
// Generated by Roommaker Mon Dec  4 20:04:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("贵宾室");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫的贵宾室，装饰华丽的璧画、地毯等家俱显示
这里的主人相当重视他的客人。往东可以回到王宫大厅。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/palace_hall" ]) );
	ob->set( "objects", ([ 
		"servant" : "/d/noden/nodania/monster/servant" ]) );
	ob->reset();
}
