// File: /d/noden/nodania/hgarden.c
// Generated by Roommaker Mon Dec  4 20:04:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("空中花园");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫二楼的空中花园，这里不但屋顶是透明的，连四周的墙
壁都适用玻璃做的，为了给花卉们充足的阳光。国王收集了不少各地的珍奇花卉
都种在这里，甚至最近还派遣了一支特使团到东方大国去寻找一种名贵的兰花，
你在这里参观时最好小心一点，要是碰坏了任何一株花卉的枝叶花瓣，可是会有
大麻烦的。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/nodania/upstair_1" ]) );
	ob->reset();
}
