// File: /d/noden/nodania/kitchen.c
// Generated by Roommaker Mon Dec  4 20:05:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("厨房");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫中的厨房，你可以看到许多的猪肉、牛肉、蔬
菜、水果等，井井有条的放在桌上或柜子中。这个地方看起来很乾净，
看起来国王的厨子相当尽职。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/e_hall" ]) );
	ob->set( "objects", ([ 
		"cook" : "/d/noden/nodania/monster/cook" ]) );
	ob->reset();
}
