// File: /d/noden/nodania/palace_hall.c
// Generated by Roommaker Mon Dec  4 20:05:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宫大厅");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了王宫大厅之中，整个大厅布置得富丽堂皇，墙壁上装饰著
出自名家的浮雕与璧画。大厅四个角落各有一根三人合抱的大理石柱，柱子
上各装饰著一个天使的石雕，天使手中举著的光球照亮整个大厅。东边的回
廊通往王宫的厨房，西边是贵宾室，国王接待贵宾的地方，往北你可以远远
望见国王的宝座。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/e_hall", 
		"west" : "/d/noden/nodania/greeting_hall", 
		"south" : "/d/noden/nodania/courtyard", 
		"north" : "/d/noden/nodania/throne_room" ]) );
	ob->reset();
}
