// File: /d/noden/nodania/s_gate.c
// Generated by Roommaker Mon Dec  4 20:10:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("诺达尼亚，南门");
	ob->set_long( @LONG_DESCRIPTION
你现在站在诺达尼亚城，也就是诺达尼亚王宫南边的大门口。在你的北
方不远处，就是国王耶拉曼十一世的宫殿。城堡路向东西方延伸下去，南边
则是诺达尼亚广场。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/castle_r2", 
		"west" : "/d/noden/nodania/castle_r1", 
		"north" : "/d/noden/nodania/courtyard", 
		"south" : "/d/noden/nodania/square" ]) );
	ob->set( "objects", ([ 
		"gate guard#2" : "/d/noden/nodania/monster/gate_guard", 
		"gate guard#1" : "/d/noden/nodania/monster/gate_guard" ]) );
	ob->reset();
}
