// File: /d/noden/nodania/theater.c
// Generated by Roommaker Mon Dec  4 20:12:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("诺达尼亚露天剧院");
	ob->set_long( @LONG_DESCRIPTION
这里是远近驰名的诺达尼亚露天剧院，每当这里有歌剧因演出或音乐
会时，诺顿王国各地的人们都会聚集在这里。东边的墙上有一张巨幅的壁
画(wall painting) ，大厅入口中央有一座小喷水池(fountain)。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/square" ]) );
	ob->set( "item_desc", ([ 
		"fountain" : @LONG_TEXT
一座用大理石砌成的小喷泉，据说许多诺达尼亚的少女喜欢将玫瑰花的花
瓣丢进喷泉中许愿，因此你可以看到喷泉的底部有一层厚厚的花瓣。
LONG_TEXT
, 
		"wall painting" : @LONG_TEXT
这幅壁画是宫廷画家比拉得的名作「少年骑士与吟游诗人」，画的是传说
中吉尔瑞克(Gelreck)少年时代和吟游诗人芙娜(Pheuna)相遇的故事。
LONG_TEXT
 ]) );
	ob->reset();
}
