// File: /d/noden/nodania/tower3.c
// Generated by Roommaker Mon Dec  4 20:13:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔楼三楼");
	ob->set_long( @LONG_DESCRIPTION
你现在正站在一座塔楼的三楼，墙角的楼梯分别通往顶楼与二楼，北边的
窗户不知道为了什麽原因用木板钉死了，使得这里看起来有些阴暗，一些破旧
的木桶和沙包凌乱地堆在地上。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/tower2", 
		"up" : "/d/noden/nodania/tower4" ]) );
	ob->reset();
}
