// File: /d/noden/nodania/tower2.c
// Generated by Roommaker Mon Dec  4 20:13:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔楼二楼");
	ob->set_long( @LONG_DESCRIPTION
你现在正站在一座塔楼的二楼，墙角的楼梯分别通往一楼与三楼
，从北方的窗户望出去可以看到诺达尼亚森林，以及雄踞在东北方的
高大山脉。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/tower1", 
		"up" : "/d/noden/nodania/tower3" ]) );
	ob->set( "objects", ([ 
		"cat" : "/d/noden/nodania/monster/cat" ]) );
	ob->reset();
}
