// File: /d/noden/nodania/tower1.c
// Generated by Roommaker Mon Dec  4 20:13:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔楼底层");
	ob->set_long( @LONG_DESCRIPTION
你现在正站在一座塔楼的底层，西边有一道楼梯通往二楼，从北边的窗户
可以看到诺达尼亚北方的森林，墙角有几个木箱(boxes)堆在一起，往南是一
条幽暗的回廊，伊莉亚皇后的储藏室就在你的东方。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/collection", 
		"south" : "/d/noden/nodania/sealroom", 
		"up" : "/d/noden/nodania/tower2" ]) );
	ob->set( "item_desc", ([ 
		"boxes" : @LONG_TEXT
这几个木箱看起来像是在这里堆了有几个世纪之久，上面所积的灰尘厚得
令你不敢大口吐气，不过其中一个木箱上面印了一个圆形的痕迹，也许是
烛台、杯子....只有天知道。
LONG_TEXT
 ]) );
	ob->reset();
}
