// File: /d/noden/nodania/upstair_1.c
// Generated by Roommaker Mon Dec  4 20:14:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长廊");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫二楼的一处长廊，平日只有国王和他的家人才会在这里
出现，你可以看到许多精致的壁画与浮雕装饰著两边的墙壁，地板是用白色的大
里石铺成的，往南是一座种著许多花卉的空中花园，往西是长廊的另一端。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/e_throne", 
		"south" : "/d/noden/nodania/hgarden", 
		"west" : "/d/noden/nodania/upstair_2" ]) );
	ob->reset();
}
