// File: /d/noden/nodania/upstair_3.c
// Generated by Roommaker Mon Dec  4 20:15:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长廊转角");
	ob->set_long( @LONG_DESCRIPTION
这里是王宫二楼长廊的一处转角，西边是公主的卧室，长廊通往东边与南
边，在墙角有一座耶拉曼六世的半身像(bust)，看起来威风凛凛。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/upstair_2", 
		"south" : "/d/noden/nodania/upstair_4" ]) );
	ob->set( "objects", ([ 
		"artist" : "/d/noden/nodania/monster/artist" ]) );
	ob->reset();
}
