// File: /d/noden/nodania/upstair_4.c
// Generated by Roommaker Mon Dec  4 20:15:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长廊");
	ob->set_long( @LONG_DESCRIPTION
这里是长廊的尽头，国王和皇后的卧室在你的南方，在你的西边有一个
窗户可以望见国王的马场，两边的墙壁都装饰著精美的壁画，卧室的门口有
一对纯金的烛台，这是皇后依莉雅上次到东方大国旅行所带回来的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/noden/nodania/upstair_3" ]) );
	ob->reset();
}
