// File: /d/noden/nodania/upstair_2.c
// Generated by Roommaker Mon Dec  4 20:14:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长廊");
	ob->set_long( @LONG_DESCRIPTION
这里是诺达尼亚王宫的一处长廊，白色大理石铺成的地板将两边墙壁的
精致浮雕点缀得富丽堂皇，从这里你可以沿著长廊往东或往西。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/upstair_1", 
		"west" : "/d/noden/nodania/upstair_3" ]) );
	ob->reset();
}
