// File: /d/noden/nodania/w_path2.c
// Generated by Roommaker Mon Dec  4 20:16:18 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板小径");
	ob->set_long( @LONG_DESCRIPTION
你现在走在一条石板铺成的小径，两旁生著疏疏落落的灌木丛。小径在
一丛玫瑰花(rose)树前转往北边，你从这里可以看到一间相当大的马房，里
面饲养著国王专用的战马。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/w_path", 
		"north" : "/d/noden/nodania/stable" ]) );
	ob->set( "item_desc", ([ 
		"$1" : @LONG_TEXT
一丛鲜红色的玫瑰花，上面长满了尖刺，这种玫瑰花诺达尼亚人为她取
了个有趣的名字叫做「仇人的妻子」。
LONG_TEXT
, 
		"rose" : @LONG_TEXT
一丛鲜红色的玫瑰花，枝干上长满了尖尖的小刺，诺达尼亚人为这种玫
瑰花取了个有趣的名字叫做「仇人的妻子」。
LONG_TEXT
 ]) );
	ob->reset();
}
