// File: /d/noden/nodania/yard1.c
// Generated by Roommaker Mon Dec  4 20:16:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("武器教练场");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一个铺满砂子的圆形教练场，旁边有许\多放置武器的架子，一些
骑士们常在这里操练武器技能，如果你对自己有信心的话，不妨和他们较量看看
，往南是一列整齐的军营。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/nodania/barrack" ]) );
	ob->set( "objects", ([ 
		"horse" : "/d/noden/nodania/monster/horse", 
		"soldier#3" : "/d/noden/nodania/monster/soldier", 
		"soldier#2" : "/d/noden/nodania/monster/soldier", 
		"soldier#1" : "/d/noden/nodania/monster/soldier", 
		"dalifore" : "/d/noden/nodania/monster/master" ]) );
	ob->reset();
}
