// File: /d/noden/nodania/nodania_r1.c
// Generated by Roommaker Tue Nov 30 15:57:15 1993
// translation done 2-22-94 - Elon  (fix desc and add item desc)

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("诺达尼亚路");
	set_long( @C_LONG_DESCRIPTION
你现在走在诺达尼亚路上，两行整齐的橄榄树种植在宽阔的街道两旁，路
上的行人都穿著相当体面的服饰。你注意到你的西边有一家规模颇大的商店，
如果不是门口那块醒目的招牌(sign)，你也许会把这家商店误认为是一间神殿
或博物馆。往东是一条看起来阴森森的小巷子，冷冷清清的和这里的繁华热闹
成为强烈的对比。
C_LONG_DESCRIPTION
	);

	set_outside( "nodania" );
	set( "c_item_desc", ([ 
		"sign" : "「王记商行」\n" ]) );
    set( "item_desc", ([
        "sign" : "[The Shop of Wang]\n" ]) );
    set( "exits", ([ 
		"west" : "/d/noden/nodania/shop", 
		"north" : "/d/noden/nodania/square", 
		"south" : "/d/noden/6,8.noden", 
		"east" : "/d/noden/nodania/alley1" ]) );
	reset();
#include <replace_room.h>
}
