// File: /d/noden/nodania/tower4.c
// Generated by Roommaker Fri Sep  2 16:15:43 1994

#include <mudlib.h>

inherit ROOM;
int inwar;

void create()
{
	::create();
	set_short("塔楼顶楼");
	set_long( @C_LONG_DESCRIPTION
你现在来到一座塔楼的楼顶，从这里可以远眺诺达尼亚四周的景物，北方
是一片蓊郁的森林，东北方环绕著黑色山谷的大山给人一种莫名的压迫感，这
里也是诺达尼亚军队的了望台，一旦有敌人来袭，这里的卫兵就会马上去报告
守军将领。
C_LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"down" : "/d/noden/nodania/tower3" ]) );
	set( "objects", ([ 
		"guard" : "/d/noden/nodania/monster/tower_guard" ]) );
	reset();
}

void init()
{
   add_action( "do_brandish", "brandish" );
}

void reset()
{
   ::reset();
   inwar = 0;
}

int do_brandish(string arg)
{
   object guard, sword;

   if( !arg || (arg!="sword of markara" && arg!="markara"
        && arg!="sword") ) return 0;
   if( !present("sword of markara",this_player()) )
        return notify_fail("你用力地挥舞著双手。\n" );
   if( this_player()->query_level()<5 )
     return notify_fail("你举起玛卡拉之剑，向天空挥舞著, 但是没人注意你。\n" );
   if( inwar ) return notify_fail("默尔斯大军已经进攻了, 不需要再挥剑了!\n");

   guard = present("tower guard",environment(this_player()));
   sword = present("sword of markara",this_player());

   tell_object( this_player(),"你举起玛卡拉之剑，向天空挥舞著。\n" );
   tell_room( environment(this_player()), 
sprintf( "%s举起玛卡拉之剑朝著天空挥舞。\n",this_player()->query("c_name")), this_player() );
   sword->remove();
   this_player()->add( "alignment", -1000 );
   this_player()->set_temp( "war_spy", 1 );
   find_object_or_load("/adm/daemons/event/moorth")->start_war();
   inwar = 1;

   if( present("tower guard",environment(this_player())) ) {
     tell_room(environment(this_player()),
        "\n看守塔楼的卫兵怒道: 可恶的间谍! 下地狱吧!!\n\n" );
     guard->kill_ob(this_player());
     this_player()->kill_ob(guard);
     return 1;
     }
   return 1;
}
