// File: /d/thief/hall/thief_trainroom.c
// Generated by Roommaker Sat Nov 11 11:55:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小偷训练中心");
	ob->set_long( @LONG_DESCRIPTION
这里是小偷的训练中心。小偷们到各地磨练各种技能, 到一定程度後, 
常常会遇到瓶颈。因此毕克林老爹找了一些经验丰富的神偷帮助小偷们
提升技巧。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/thief/hall/thief_guild" ]) );
	ob->set( "objects", ([ 
		"taylers" : "/d/thief/hall/monsters/taylers" ]) );
	ob->reset();
}
