// File: /d/deathland/city/c3.c
// Generated by Roommaker Sat Nov 11 12:09:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人国度的主要道路,道路的两旁有火把照亮著,由於矮人高超的建筑技术,
这道路修筑的非常笔直,很难相信你是处在地底下数十里的地方.
南方是矮人的墓场,埋藏著一些英勇战死的士兵的骨骸,如果他没被巨人吃掉的话.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/c4", 
		"south" : "/d/deathland/city/g1", 
		"west" : "/d/deathland/city/c2" ]) );
	ob->reset();
}
