// File: /d/deathland/city/c4.c
// Generated by Roommaker Sat Nov 11 12:12:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人国度的主要道路,道路的两旁有火把照亮著,由於矮人高超的建筑技术,
这道路修筑的非常笔直,很难相信你是处在地底下数十里的地方.
北边是一座教堂,不知矮人族是祭拜那个神明,而南边好像是一座市场,只见一群
矮人们聚集著,明显的你已经到了矮人国度了.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/c5", 
		"south" : "/d/deathland/city/m1", 
		"north" : "/d/deathland/city/church", 
		"west" : "/d/deathland/city/c3" ]) );
	ob->reset();
}
