// File: /d/deathland/city/c6.c
// Generated by Roommaker Sat Nov 11 12:15:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人国度的主要道路,道路的两旁有火把照亮著,由於矮人高超的建筑技术,
这道路修筑的非常笔直,很难相信你是处在地底下数十里的地方.往南有一条小
径,通往矮人的矿坑.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/c7", 
		"south" : "/d/deathland/mine/mine_01", 
		"west" : "/d/deathland/city/c5" ]) );
	ob->reset();
}
