// File: /d/deathland/city/c7.c
// Generated by Roommaker Sat Nov 11 12:17:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人国度的主要道路,道路的两旁有火把照亮著,由於矮人高超的建筑技术,
这道路修筑的非常笔直 , 很难相信你是处在地底下数十里的地方 .道路的东方
有一个拱门 , 由拱门过去就是矮人国度的皇宫了 .往北方则是通往矮人的村落
的小路.为了保护老弱妇孺.在到达矮人的村落时你会经过矮人的军营.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_01", 
		"north" : "/d/deathland/dwarf/village_01", 
		"west" : "/d/deathland/city/c6" ]) );
	ob->reset();
}
