// File: /d/deathland/city/church.c
// Generated by Roommaker Sat Nov 11 15:06:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的教堂");
	ob->set_long( @LONG_DESCRIPTION
一股祥和的气氛笼罩著整个地方,教堂里到处都是虔诚的信徒,在这麽多年
的战乱之中, 矮人们期望他们的大神能够解救他们脱离苦海, 因此建造了这座
雄伟的大教堂.教堂内\的\摆\设除了一座非常巨大的神像 (statue) 外,神像前有
一个祭坛(altar),此外数张长椅被整齐排列著,好让信徒们能专心的祈祷.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"altar" : "一个奇怪的祭坛,上面空无一物.\n", 
		"statue" : "@@look_statue" ]) );
	ob->set( "exits", ([ 
		"south" : "/d/deathland/city/c4" ]) );
	ob->set( "objects", ([ 
		"priest" : "/d/deathland/monster/priest", 
		"believer#2" : "/d/deathland/monster/believer", 
		"believer#4" : "/d/deathland/monster/believer", 
		"believer#1" : "/d/deathland/monster/believer", 
		"believer#3" : "/d/deathland/monster/believer" ]) );
	ob->reset();
}
