// File: /d/deathland/city/g1.c
// Generated by Roommaker Sat Nov 11 15:14:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的墓场");
	ob->set_long( @LONG_DESCRIPTION
这里是矮人国度的墓场的入口,墓场里埋藏著一些英勇战死的士兵的骨骸.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/city/g2", 
		"north" : "/d/deathland/city/c3" ]) );
	ob->reset();
}
