// File: /d/deathland/city/g7.c
// Generated by Roommaker Sat Nov 11 15:20:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("英雄墓场");
	ob->set_long( @LONG_DESCRIPTION
这里是矮人英雄的墓场,墓场里埋藏著一位纵横沙场的英雄.这一座墓碑的碑铭上
写著: 一位令人敬仰的无敌英雄.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/g6", 
		"north" : "/d/deathland/city/gb", 
		"west" : "/d/deathland/city/g8" ]) );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard05" ]) );
	ob->set( "pre_exit_func", ([ 
		"north" : "to_north" ]) );
	ob->reset();
}
