// File: /d/deathland/city/g9.c
// Generated by Roommaker Sat Nov 11 15:24:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("英雄墓场");
	ob->set_long( @LONG_DESCRIPTION
这里是矮人英雄的墓场,墓场里埋藏著一个悲天悯人的医生.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/city/ga", 
		"south" : "/d/deathland/city/g8" ]) );
	ob->reset();
}
