// File: /d/deathland/city/m3.c
// Generated by Roommaker Sat Nov 11 15:33:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人国度的市场");
	ob->set_long( @LONG_DESCRIPTION
一群矮人聚集於此,这里是矮人国度的市场,矮人在此买卖一些日常用品,以及
一些奇奇怪怪的东西. 小贩的叫卖声不绝於耳,你期望能在此买到什麽有用的物品
吗?或\许\纪\念品是最好的选择,其他的东西只是浪费你的金钱吧了.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/city/m2" ]) );
	ob->set( "objects", ([ 
		"merchant" : "/d/deathland/monster/merchant02" ]) );
	ob->reset();
}
