// File: /d/deathland/village/v01.c
// Generated by Roommaker Thu Nov 23 21:03:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的入口");
	ob->set_long( @LONG_DESCRIPTION
西边就是矮人的村庄.而南边就是保护矮人的迷宫.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/village/v02", 
		"south" : "/d/deathland/dwarf/darkroom" ]) );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard01" ]) );
	ob->reset();
}
