// File: /d/deathland/village/v12.c
// Generated by Roommaker Thu Nov 23 21:09:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村庄的环庄道路上,这里有著非常和平安详的气氛,恍佛是一个世
外桃源.这里已经多年没有战争了,矮人们的童年几乎在此渡过 .西边似乎是一间被废弃
的建筑物,从外表来看应该是座监牢.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/village/v11", 
		"north" : "/d/deathland/village/v13", 
		"west" : "/d/deathland/village/vr8" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/deathland/monster/older" ]) );
	ob->reset();
}
