// File: /d/deathland/village/v25.c
// Generated by Roommaker Thu Nov 23 21:08:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村庄的环庄道路上,这里有著非常和平安详的气氛,恍佛是一个世
外桃源.这里已经多年没有战争了,矮人们的童年几乎在此渡过.北边是一间医院,上面的
招牌上写著:安琪拉(angelina)诊所.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v35", 
		"north" : "/d/deathland/village/vr6", 
		"west" : "/d/deathland/village/v15" ]) );
	ob->reset();
}
