// File: /d/deathland/village/v41.c
// Generated by Roommaker Thu Nov 23 21:05:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村庄的环庄道路上,这里有著非常和平安详的气氛,恍佛是一个世
外桃源.这里已经多年没有战争了,矮人们的童年几乎在此渡过.南边是一栋很大的教堂,
祭祀著矮人的神,邪恶之神 <Yang>.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v51", 
		"south" : "/d/deathland/village/vr2", 
		"west" : "/d/deathland/village/v31" ]) );
	ob->set( "objects", ([ 
		"child" : "/d/deathland/monster/child", 
		"older" : "/d/deathland/monster/older" ]) );
	ob->reset();
}
