// File: /d/deathland/village/v43.c
// Generated by Roommaker Thu Nov 23 21:10:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的广场");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村庄的大广场上,这里有著非常和平安详的气氛,矮人们经常在此地
游玩及嬉戏.西边有一个很大的水塘(pool),是矮人饮用水的来源 ,在水塘的中央有一个飘
浮的房子(house),你不能想像为何它能浮在空中而不掉下来.
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"house" : @LONG_TEXT
一间飘浮的房子,它有著奇怪的力量,当你注视著它的时候,你发现有一
奇异的光线从里面射了出来.
LONG_TEXT
, 
		"pool" : "一个大水塘,由於矮人的饮用水取於此地,所以此水塘禁止游泳.\n" ]) );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v53", 
		"north" : "/d/deathland/village/v44", 
		"south" : "/d/deathland/village/v42" ]) );
	ob->set( "objects", ([ 
		"child" : "/d/deathland/monster/child02" ]) );
	ob->reset();
}
