// File: /d/deathland/village/v52.c
// Generated by Roommaker Thu Nov 23 21:06:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村庄的环庄道路上,这里有著非常和平安详的气氛,恍佛是一个世
外桃源.这里已经多年没有战争了 ,矮人们的童年几乎在此渡过.东边是矮人族开会的地
方,但是似乎已经很久没有使用了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/vr3", 
		"south" : "/d/deathland/village/v51", 
		"north" : "/d/deathland/village/v53" ]) );
	ob->set( "objects", ([ 
		"poet" : "/d/deathland/monster/writer" ]) );
	ob->reset();
}
