// File: /d/deathland/village/vr6.c
// Generated by Roommaker Thu Nov 23 21:14:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("安琪拉诊所");
	ob->set_long( @LONG_DESCRIPTION
这里躺著很多受伤的矮人士兵及战士,充斥著药水味及消毒剂的呛鼻味道.而这里的
设备似乎十分齐全,在这里的大夫医治之下,受伤的士兵应该很快地能回到战场上.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/village/v25" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/deathland/monster/doctor", 
		"soldier#3" : "/d/deathland/monster/soldier05", 
		"soldier#2" : "/d/deathland/monster/soldier05", 
		"soldier#1" : "/d/deathland/monster/soldier05" ]) );
	ob->reset();
}
