// File: /d/deathland/village/vr8.c
// Generated by Roommaker Thu Nov 23 21:09:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("荒废的牢狱");
	ob->set_long( @LONG_DESCRIPTION
这里是一座荒废已久的牢狱,瓦砾堆积著整个地方.仔细一看有一个门通往地下,但
是那个门已经完完全全被封死了
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"door" : "除了瓦砾堆积在上面外,似乎有一股魔力封住这道门\n" ]) );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v12" ]) );
	ob->reset();
}
