// File: /d/deathland/village/vr9.c
// Generated by Roommaker Thu Nov 23 21:15:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("安洛的休息室");
	ob->set_long( @LONG_DESCRIPTION
长老安洛的休息室,四周空无一物,而且一尘不染,是个静心休行的好地方.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/deathland/village/v33" ]) );
	ob->set( "objects", ([ 
		"annow" : "/d/deathland/monster/annow" ]) );
	ob->reset();
}
