// File: /d/eastland/mumar/kitchen.c
// Generated by Roommaker Sat Nov 25 13:52:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("伙房");
	ob->set_long( @LONG_DESCRIPTION
这里是牧马关的伙房，每天供应全关官兵营养丰富的食物，以保持体力巅峰。
这儿的墙上挂满了锅碗瓢盆之类的烹调器具，油腻的调理台上则是一些用大桶子装
的调味品。鼓风炉上的大锅子大的吓人，不过闻起来味道还真不错。这儿的东边还
有一间库房，西边的门外则是教场。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/vault03", 
		"west" : "/d/eastland/mumar/square06" ]) );
	ob->set( "objects", ([ 
		"cookie#2" : "/d/eastland/mumar/monster/cook_soldier", 
		"cookie#1" : "/d/eastland/mumar/monster/cook_soldier" ]) );
	ob->reset();
}
