// File: /d/eastland/mumar/ladder01.c
// Generated by Roommaker Sat Nov 25 13:50:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石梯");
	ob->set_long( @LONG_DESCRIPTION
这里是城墙函洞下的一座石梯，墙上的火把正嘶嘶地烧著。一道粗糙的石梯从这
儿往上通到城墙上的走廊，东边则可以回到城楼通道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/road1", 
		"up" : "/d/eastland/mumar/wall01" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
