// File: /d/eastland/mumar/m_kitchen.c
// Generated by Roommaker Sat Nov 25 13:55:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("镜中的伙房");
	ob->set_long( @LONG_DESCRIPTION
这里是镜中的牧马关的伙房。原本该挂在墙上的烹调器具们散落在地上的各个
角落，除此之外，地面上都是一些东倒西歪的空桶子。四周的墙壁和调理台上全是
一些啃□过和抓过的痕迹，看来这里是某个贪吃的野兽的家。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/m_square" ]) );
	ob->set( "objects", ([ 
		"rat" : "/d/eastland/mumar/monster/rat" ]) );
	ob->reset();
}
