// File: /d/eastland/mumar/m_square.c
// Generated by Roommaker Sat Nov 25 13:55:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("镜中的牧马关教场");
	ob->set_long( @LONG_DESCRIPTION
你走进了一片很大的广场，不过，和镜外不同的是，这儿是一片死寂，一点生气
都没有，静得连掉下一支针都听得见。南北的关门都是紧闭，东边的库房门也是锁得
死死的。黑暗的关内，只有西边的厨房里有一丝淡黄色的光线透出。
教场上回汤。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/mumar/m_kitchen", 
		"up" : "/d/eastland/mumar/m_stage" ]) );
	ob->reset();
}
