// File: /d/eastland/mumar/square04.c
// Generated by Roommaker Sat Nov 25 13:53:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧马关教场");
	ob->set_long( @LONG_DESCRIPTION
你走进了牧马关的士兵教场，这里是正规士兵每日操课的地点。广大的教场上，
这群为保国卫民而努力的战士们，从未懈怠，不断地练习著各种战技和阵法变换，期
望自己能在战场上大显身手。士兵操练的杀声加上城墙反射回来的回音，震耳欲聋，
听不惯的人还真难在这待太久。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/square05", 
		"west" : "/d/eastland/mumar/vault02", 
		"south" : "/d/eastland/mumar/square01" ]) );
	ob->set( "objects", ([ 
		"soldier#2" : "/d/eastland/mumar/monster/soldier", 
		"soldier#1" : "/d/eastland/mumar/monster/soldier" ]) );
	ob->reset();
}
