// File: /d/eastland/mumar/square02.c
// Generated by Roommaker Sat Nov 25 13:52:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧马关教场");
	ob->set_long( @LONG_DESCRIPTION
这里是一片很大的广场，牧马关的官兵就在此地接受日夜不停的严格训练，广场
四周是高耸的牧马关城墙，使得杀气弥漫在整个教场上。不远的北边，可以看到牧马
关的北门城楼，南边则是南城门。你耳里听到的全是教头和士兵们的嘶喊声，在整个
教场上回汤。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/square03", 
		"west" : "/d/eastland/mumar/square01", 
		"north" : "/d/eastland/mumar/square05", 
		"south" : "/d/eastland/mumar/road1" ]) );
	ob->reset();
}
