// File: /d/eastland/mumar/square03.c
// Generated by Roommaker Sat Nov 25 13:54:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧马关教场");
	ob->set_long( @LONG_DESCRIPTION
你走进牧马关教场的东南角，这儿是牧马关的新兵教场，所有刚调到牧马关的士
兵都必须在这里接受三天的入营训练，来适应这里的作息和气候；凡是无法完成三天
训练的人，都将分送到别的基地。由於能在牧马关保卫□土，是东方大国人民的光荣
，所以你所看到的每个新兵都卯上全力，期望能成为一个牧马关战士。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/mumar/square02", 
		"north" : "/d/eastland/mumar/square06", 
		"southeast" : "/d/eastland/mumar/stable" ]) );
	ob->set( "objects", ([ 
		"soldier#3" : "/d/eastland/mumar/monster/new_soldier", 
		"soldier#2" : "/d/eastland/mumar/monster/new_soldier", 
		"master" : "/d/eastland/mumar/monster/master", 
		"soldier#1" : "/d/eastland/mumar/monster/new_soldier" ]) );
	ob->reset();
}
