// File: /d/eastland/mumar/square05.c
// Generated by Roommaker Sat Nov 25 13:53:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧马关教场");
	ob->set_long( @LONG_DESCRIPTION
这里是一片很大的广场，牧马关的官兵就在此地接受日夜不停的严格训练，广场
四周是高耸的牧马关城墙，使得杀气弥漫在整个教场上。北边就是牧马关的北门，南
边则可以通往南门。你耳里听到的全是教头和士兵们的嘶喊声，在整个教场上回汤。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/square06", 
		"west" : "/d/eastland/mumar/square04", 
		"north" : "/d/eastland/mumar/north_gate", 
		"south" : "/d/eastland/mumar/square02" ]) );
	ob->reset();
}
