// File: /d/eastland/mumar/stage02.c
// Generated by Roommaker Sat Nov 25 13:51:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("御风楼");
	ob->set_long( @LONG_DESCRIPTION
你走到这儿，看到一座雄伟壮硕的城楼，城楼上有一块扁额，用挺拔的字体写著
「御风楼」。楼角的飞檐上各雕著一只栩栩如生的麒麟。楼门前的四只大铜柱上各以
一只石鼋为基，柱上盘著四条青龙，各自追逐著红、蓝、绿、黄四颗火球。这儿的磅
薄气势像个大户人家，反倒不像是个军事重镇。进了门就是一道上楼的大梯，往北则
可以回到城墙的通道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/mumar/stage06", 
		"north" : "/d/eastland/mumar/wall05" ]) );
	ob->reset();
}
