// File: /d/abyss/entrance/start.c
// Generated by Roommaker Tue Oct 18 16:47:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "仙境");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你现在来到一处风景优美的山坡，放眼四周是一大片绿草如茵的草地，被一
层薄雾覆盖著，你站在山坡顶上，面前是几棵高大的老树环绕著一个小池塘，树
下还有磨得光滑圆亮的石头当作座椅。
C_LONG_DESCRIPTION
	);
            set("exits",([
            "north":"/d/abyss/hell/bridge"]));
	reset();
}
