// File: /d/deathland/mine/d03.c
// Generated by Roommaker Thu Nov 23 20:21:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人矿坑的大洞穴");
	ob->set_long( @LONG_DESCRIPTION
一个很黑很暗的大洞穴,曾经是个含量丰富的矿坑,但是自从传出这里出现怪物後
就没有什麽人敢来了.越往西走,就觉得似乎有人在窥探你的样子.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/mine/d02", 
		"west" : "/d/deathland/mine/d04" ]) );
	ob->reset();
}
