// File: /d/deathland/mine/m52.c
// Generated by Roommaker Thu Nov 23 20:30:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人矿坑");
	ob->set_long( @LONG_DESCRIPTION
这里是矿坑的深处.你能看到的是一个周围的岩壁充满著被挖掘的痕迹以及
用木头架设著以免塌陷的岩洞.在地上有铁轨铺设著.专供运矿车通行使用.你能
看到\许\多运矿车来来往往.
LONG_DESCRIPTION
	);

	ob->set( "direction", "south" );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/mine/m46", 
		"south" : "/d/deathland/mine/m62" ]) );
	ob->reset();
}
