// File: /d/eastland/easta/east_malley.c
// Generated by Roommaker Sat Nov 25 17:09:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("东大街");
	ob->set_long( @LONG_DESCRIPTION
你现在正位於若岚城的东大街上，整齐的街道上铺著青石砖，若岚城的街道
素有整洁美观的好评，你最好别任意制造脏乱，以免受人耻笑。在你的北边是一
家叫做「聚宝斋」的商店，往南则是金蟾钱庄。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_ent", 
		"north" : "/d/eastland/easta/shop", 
		"west" : "/d/eastland/easta/palace_e", 
		"south" : "/d/eastland/easta/bank" ]) );
	ob->reset();
}
