// File: /d/eastland/easta/east_ent.c
// Generated by Roommaker Sat Nov 25 17:02:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("东大街路口");
	ob->set_long( @LONG_DESCRIPTION
你现在来到若岚城东门内的大街，若岚城以若岚宫为中心，东西东北环绕著
四条大街，东大街向来以「吃」闻名，东大街北胡同还因为多得数不尽的餐\馆与
小吃摊，博得「百味巷」的别称，往西是东大街的主要街道，通往若岚宫的青龙
门，东边则是往城外的东门。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/eastgate", 
		"north" : "/d/eastland/easta/east_nlane", 
		"south" : "/d/eastland/easta/east_slane", 
		"west" : "/d/eastland/easta/east_malley" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/obj/vendor" ]) );
	ob->reset();
}
