// File: /d/eastland/easta/north_malley.c
// Generated by Roommaker Sat Nov 25 17:10:10 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("北大街");
	ob->set_long( @LONG_DESCRIPTION
你现在正位於若岚城的北大街上，整齐的街道上铺著青石砖，若岚城的街道
素有整洁美观的好评，你最好别任意制造脏乱，以免受人耻笑。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/easta/palace_n", 
		"north" : "/d/eastland/easta/north_ent", 
		"west" : "/d/scholar/scholar/scholar_guild" ]) );
	ob->reset();
}
