// File: /d/eastland/easta/north_ent.c
// Generated by Roommaker Sat Nov 25 17:03:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("北大街路口");
	ob->set_long( @LONG_DESCRIPTION
你现在来到若岚城北门内的大街，若岚城以若岚宫为中心，东西东北环绕著
四条大街，北大街文风鼎盛，许\多书院画坊都开在这条街上，以养士著名的「赛
孟尝」卞大夫所出资兴建的「舞墨轩」也在这条街上，北边则是往城外的北门。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/north_elane", 
		"south" : "/d/eastland/easta/north_malley", 
		"north" : "/d/eastland/easta/northgate", 
		"west" : "/d/eastland/easta/north_wlane" ]) );
	ob->reset();
}
