// File: /d/eastland/easta/palace_ne.c
// Generated by Roommaker Sat Nov 25 17:02:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("飞鸿楼");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了若岚宫东北角，飞鸿楼前的广场，据说每年二月刮起东北风的时
候，东北风吹过飞鸿楼屋檐下的风管时，发出的声音就如大鸿飞翔时的叫声，不少
外地来的人都特地赶来这里聆听「鸿鸣」，从广场向北是一条热闹的胡同，往东则
是有「百味巷」之称的东大街北胡同。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_nalley", 
		"north" : "/d/eastland/easta/north_ealley", 
		"south" : "/d/eastland/easta/palace_e", 
		"west" : "/d/eastland/easta/palace_n" ]) );
	ob->set( "objects", ([ 
		"vistor2" : "/d/eastland/easta/monster/vistor", 
		"vistor1" : "/d/eastland/easta/monster/vistor" ]) );
	ob->reset();
}
