// File: /d/eastland/easta/palace_w.c
// Generated by Roommaker Sat Nov 25 17:11:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若岚宫白虎门");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了若岚宫西边的玄武门，高大的宫门上面装饰著七排拳头大的铜
环，紧闭的宫门和高大的宫墙透出一股宫廷深深的气氛，若岚宫中数不进的珍奇
宝物都被严密地守护著。往西是宽敞的西大街，从这里可以远远地望见若岚城的
西门，沿著宫墙的青石板路往北方和南方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/easta/palace_sw", 
		"north" : "/d/eastland/easta/palace_nw", 
		"west" : "/d/eastland/easta/west_malley" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
