// File: /d/eastland/easta/palace_e.c
// Generated by Roommaker Sat Nov 25 17:10:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若岚宫青龙门");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了若岚宫东边的青龙门，高大的宫门上面装饰著七排拳头大的铜
环，紧闭的宫门和高大的宫墙透出一股宫廷深深的气氛，若岚宫中数不进的珍奇
宝物都被严密地守护著。往东是宽敞的东大街，从这里可以远远地望见若岚城的
东门，沿著宫墙的青石板路往北方和南方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_malley", 
		"south" : "/d/eastland/easta/palace_se", 
		"north" : "/d/eastland/easta/palace_ne" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
