// File: /d/eastland/easta/palace_sw.c
// Generated by Roommaker Sat Nov 25 17:05:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灵猿楼");
	ob->set_long( @LONG_DESCRIPTION
你现在正位於若岚宫西南角，灵猿楼前的广场，若岚宫高大的宫墙往东方与
北方延伸，沿著宫墙种著一排美丽的凤凰木，街道上铺著整齐的青石板，广场南
边与西边各有一条胡同，通往环绕若岚城的大街。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/palace_s", 
		"south" : "/d/eastland/easta/south_walley", 
		"north" : "/d/eastland/easta/palace_w", 
		"west" : "/d/eastland/easta/west_salley" ]) );
	ob->set( "objects", ([ 
		"vistor2" : "/d/eastland/easta/monster/vistor", 
		"vistor1" : "/d/eastland/easta/monster/vistor" ]) );
	ob->reset();
}
