// File: /d/eastland/easta/palace_n.c
// Generated by Roommaker Sat Nov 25 17:11:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若岚宫玄武门");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了若岚宫北边的玄武门，高大的宫门上面装饰著七排拳头大的铜
环，紧闭的宫门和高大的宫墙透出一股宫廷深深的气氛，若岚宫中数不进的珍奇
宝物都被严密地守护著。往北是宽敞的北大街，从这里可以远远地望见若岚城的
北门，沿著宫墙的青石板路往东方和西方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/palace_ne", 
		"north" : "/d/eastland/easta/north_malley", 
		"west" : "/d/eastland/easta/palace_nw" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
