// File: /d/eastland/easta/south_ent.c
// Generated by Roommaker Sat Nov 25 17:06:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("南大街路口");
	ob->set_long( @LONG_DESCRIPTION
你现在来到若岚城南门内的大街，若岚城以若岚宫为中心，东西东北环绕著
四条大街，南大街由於正对著若岚宫的正门朱雀门，因此有许\多权贵显要都居住
在这条街上，你的北边不远处是相国府，更北一点是穆将军府，南大街的东西两
条胡同中也住著不少大官与士绅，南边则是往城外的南门。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/south_elane", 
		"west" : "/d/eastland/easta/south_wlane", 
		"south" : "/d/eastland/easta/southgate", 
		"north" : "/d/eastland/easta/south_malley" ]) );
	ob->reset();
}
