// File: /d/eastland/easta/westgate.c
// Generated by Roommaker Sat Nov 25 17:04:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若岚城西门");
	ob->set_long( @LONG_DESCRIPTION
这里是若岚城的西门，高耸的城墙和布满青苔的基石，古雅的城楼烘托出一股
庄严肃穆的气氛，城楼上刻著「若岚古风」四个篆字，从这里你可以远远望见城中
整齐宽敞的街道，若岚城是东方大国的首都，皇上所住的若岚宫就位於城中心，宛
如一座小型的城市。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/west_ent", 
		"west" : "/d/eastland/8,5.east" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"guard#2" : "/d/eastland/easta/monster/cityguard", 
		"guard#1" : "/d/eastland/easta/monster/cityguard" ]) );
	ob->reset();
}
