// File: /d/eastland/easta/herb_shop.c
// Generated by Roommaker Thu Jan 27 11:07:31 1994

#include <mudlib.h>

inherit SELLER;
inherit ROOM;

void create()
{
	::create();
	set_short("老桐阁药铺");
	set_long( @C_LONG_DESCRIPTION
你一走进这家药铺，就闻到一股浓郁的檀香，这里是若岚城历史最老的一家药
铺，从寻常的刀伤药膏，到难得一见的千年老□，这里都有，这家药铺还有一种祖
传的刀伤药配方叫做「天香断续膏」，治外伤灵验无比，这里所卖的药材与价钱都
写在一张挂在壁上的画轴(paper)上，往东走则是南大街的东胡同。
C_LONG_DESCRIPTION
	);

	set( "item_func", ([
		"paper" : "show_menu"
	]) );
	set( "light", 1 );
	set( "exits", ([
		"east" : "/d/eastland/easta/south_ealley" ]) );
	set_inventory( ({
		({ "/obj/bandage",60,60 }),
                ({ "/d/eastland/easta/obj/plaster1", 40, 40 }),
                ({ "/d/eastland/easta/obj/white_plaster1", 40, 40 }),
		({ "/d/eastland/easta/obj/spicy_plaster", 30, 30 }),
		({ "/d/eastland/easta/obj/green_pill", 40, 40 }),
		({ "/d/eastland/easta/obj/small_pill", 30, 30 }),
		({ "/d/eastland/easta/obj/large_pill", 20, 20 }),
	}) );
	reset();
}
void reset()
{
	room::reset();
	seller::reset();
}
