// File: /d/eastland/easta/palace_nw.c
// Generated by Roommaker Sun Jan 30 05:47:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("黄鹤楼");
	set_long( @C_LONG_DESCRIPTION
你现在来到了若岚宫西北角，黄鹤楼前的广场，据说曾经有仙人乘著黄鹤来到
这座完全用大理石建成的塔楼吟诗弹琴，这里同时也是许\多文人雅士常常流连忘返
的一处名胜，黄鹤楼云白色的形影趁著後方大红色的若岚宫宫墙，形成文人口中的
「若岚红雪」奇景。
C_LONG_DESCRIPTION
	);

	set_outside( "eastland" );
	set( "light", 1 );
	set( "exits", ([ 
		"west" : "/d/eastland/easta/west_nalley", 
		"north" : "/d/eastland/easta/north_walley", 
		"south" : "/d/eastland/easta/palace_w", 
		"east" : "/d/eastland/easta/palace_n" ]) );
	set( "objects", ([ 
		"vistor1" : "/d/eastland/easta/monster/vistor", 
		"vistor2" : "/d/eastland/easta/monster/vistor" ]) );
	reset();
#include <replace_room.h>
}
void init()
{
        if( this_player() ) this_player()->set_explore( "eastland#6" );
}
