// File: /d/eastland/easta/shop.c
// Generated by Roommaker Thu Jan 27 09:58:01 1994

#include <mudlib.h>

inherit SHOP;

void create()
{
	::create();
	set_short("聚宝斋");
	set_long( @C_LONG_DESCRIPTION
你现在走进了一家大型的商店，一块乌黑的檀木屏风隔开入口处的两道台阶，屏
风上三个金漆大字写著「聚宝斋」，店里是一个方形的卖场，两个长相斯文的先生正
分别在左右两个长柜後忙著招呼客人，你可以在这里随意浏览货物，看得中意只要向
两位先生招呼一声，他们就会过来，往南则是东大街的主要街道。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"south" : "/d/eastland/easta/east_malley" ]) );
	set( "objects", ([
		"trashcan" : "/obj/trashcan" ]) );
	storeroom()->set( "objects", ([
		"torch#0" : "/obj/torch",
		"bandage#0" : "/obj/bandage",
		"bag#0" : "/obj/bag",
	]) );
		
	reset();
#include <replace_shop.h>
}
