// File: /d/eastland/beggar/area/church.c
// Generated by Roommaker Thu Mar 21 18:08:50 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("祠堂");
	ob->set_long( @LONG_DESCRIPTION
这是一间老旧的祠堂,因为年老未修缉, 所以看起来好像要□塌的样子。一眼
看过去桌上有很多架子,架上供奉的多是历代帮主和一些精忠报国之士的神主牌 。
檀香袅袅,诵经之声不断,顿时让你想詹仰先人的风范, 因而不禁严肃了起来,或许
是忠义心人人有之使得你有所感触吧。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/beggar/area/east7.c" ]) );
	ob->set( "objects", ([ 
		"old" : "/d/eastland/beggar/monster/old_garden.c", 
		"enforcer3" : "/d/eastland/beggar/monster/enforcer.c", 
		"enforcer2" : "/d/eastland/beggar/monster/enforcer.c", 
		"enforcer1" : "/d/eastland/beggar/monster/enforcer.c" ]) );
	ob->reset();
}
