// File: /d/eastland/beggar/area/cross.c
// Generated by Roommaker Mon Jul 22 17:57:56 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆村』入口处");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了『薪胆村』的入口处，在路边有一块长满青苔的石埤 ( stone )
，虽然上面的字迹有点模糊，但仍旧可以辨认，对於初到此地的你或许是一个很好
的指引也说不定。东、西和北边都是村路，而南边则是『薪胆村』的广场，西南边
有面山墙，墙有洞，是村的出口。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"stone" : @LONG_TEXT
这是一块长满青苔的埤,上面写著:
                玩 ES 不要玩过火哟,小心你的功\课。 
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/east1.c", 
		"out" : "/d/eastland/beggar/area/mroad5.c", 
		"north" : "/d/eastland/beggar/area/north1.c", 
		"south" : "/d/eastland/beggar/area/south1.c", 
		"west" : "/d/eastland/beggar/area/west1.c" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/d/eastland/beggar/monster/vendor.c", 
		"fifth2" : "/d/eastland/beggar/monster/fifth.c", 
		"seventh" : "/d/eastland/beggar/monster/seventh.c" ]) );
	ob->reset();
}
