// File: /d/eastland/beggar/area/east8.c
// Generated by Roommaker Thu Mar 21 18:09:22 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阴暗房间");
	ob->set_long( @LONG_DESCRIPTION
你来到了一个阴暗的房间,因为这里长久欠缺阳光的照射,所以总有股挥之不去
的发霉味道。这里没什麽摆设,空洞洞的,墙壁上只有几根快烧完的火把, 地上也没
什脚印之类的东西,毕竟这里很少人来。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/beggar/area/east9.c" ]) );
	ob->reset();
}
