// File: /d/eastland/beggar/area/forest5.c
// Generated by Roommaker Mon Jul 22 17:59:12 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("竹林");
	ob->set_long( @LONG_DESCRIPTION
你身处在一片绿油油的竹林里,这里很安静,用来读书的好地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exit_suppress", ({ 
		"northwest", 
		"east" }) );
	ob->set( "exits", ([ 
		"northwest" : "/d/eastland/beggar/area/forest6", 
		"east" : "/d/eastland/beggar/area/forest7", 
		"north" : "/d/eastland/beggar/area/forest4" ]) );
	ob->set( "objects", ([ 
		"mantis1" : "/d/eastland/beggar/monster/mantis.c" ]) );
	ob->reset();
}
