// File: /d/eastland/beggar/area/forest7.c
// Generated by Roommaker Fri Mar 22 01:42:20 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("竹林");
	ob->set_long( @LONG_DESCRIPTION
你身处在一片绿油油的竹林里,这里很安静,用来读书的好地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/beggar/area/forest5" ]) );
	ob->set( "objects", ([ 
		"boar1" : "/d/eastland/beggar/monster/boar.c", 
		"boar2" : "/d/eastland/beggar/monster/boar.c", 
		"boar4" : "/d/eastland/beggar/monster/ch_boar.c" ]) );
	ob->reset();
}
