// File: /d/eastland/beggar/area/jail2.c
// Generated by Roommaker Thu Mar 21 18:10:09 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆村』监牢");
	ob->set_long( @LONG_DESCRIPTION
你现在来到了监牢的地底下一层。这里满地都是白森森的□骨, 角落里有一张
钉在墙壁上的木板床。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"bed" : "一张简简单单的木床。\n", 
		"bone" : "几根死人的骨头。\n" ]) );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/beggar/area/jail1.c" ]) );
	ob->set( "objects", ([ 
		"prisoner" : "/d/eastland/beggar/monster/prisoner" ]) );
	ob->reset();
}
