// File: /d/eastland/beggar/area/master_roome.c
// Generated by Roommaker Thu Mar 21 18:11:45 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("¡ºÉÍÉÆ·£¶ñÌü¡»");
	ob->set_long( @LONG_DESCRIPTION
ÕâÀïÊÇ¡ºÉÍÉÆ·£¶ñÌü¡»µÄÓÒ±ßÆ«·¿,±ÚÉÏ¹ÒÖøÒ»·ù»­»æĞÎÒ»¸öÈËĞÎ¡£
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"icons" : "Ò»·ùÆÄ¾ÉµÄ»­¡£\n" ]) );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/beggar/area/master_room.c" ]) );
	ob->reset();
}
