// File: /d/eastland/beggar/area/north1.c
// Generated by Roommaker Thu Mar 21 18:10:15 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("村路");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条颇为宽大的村路上,约可容纳两匹马并行。村路向南、北方
向延伸。这条村路整理得蛮乾净的,路旁的植物修缉的很整齐,花儿欣欣向荣,比起
广场那片光秃秃的景像自是不可而语。毕竟这条是连接几个较大铺子,可说是村内
最繁华的道路。虽是如此, 却看不出任何人工刻意留下来的痕迹,这一定是出自於
某位名匠之手。在你的东边是『吉祥』赌坊,而西边则是一间药铺。    
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/game_room.c", 
		"west" : "/d/eastland/beggar/area/hospital.c", 
		"north" : "/d/eastland/beggar/area/north2.c", 
		"south" : "/d/eastland/beggar/area/cross.c" ]) );
	ob->reset();
}
