// File: /d/eastland/beggar/area/s1w1.c
// Generated by Roommaker Thu Mar 21 18:07:11 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆村』广场");
	ob->set_long( @LONG_DESCRIPTION
这是一大片黄砂广场, 因为『丐帮』弟子常在此处练武功,所以地面显得光秃
秃的一根杂草也没有。有时候风刮的很大挟带著漫天的灰尘,尤其是每当南边的高
山吹著『落山风』,真叫人眼睛睁不开。於是『丐帮』拟定做一些水土保持的工作
, 但是村里缺乏另一大片空地可以供弟子们练习,所以每次提出做值地皮的工作就
会遭人反对, 於是乎人们还是得继续忍受下去。东、西和南边是广场的继续延申,
北边是道路。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/south1.c", 
		"north" : "/d/eastland/beggar/area/west1.c", 
		"south" : "/d/eastland/beggar/area/s4w1.c", 
		"west" : "/d/eastland/beggar/area/s1w2.c" ]) );
	ob->reset();
}
