// File: /d/eastland/beggar/area/s4e1.c
// Generated by Roommaker Mon Jul 22 18:00:38 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆村』广场");
	ob->set_long( @LONG_DESCRIPTION
这是一大片黄砂广场,因为『丐帮』弟子常在此处练武功, 所以地面显得光秃
秃的一根杂草也没有。有时候风刮的很大挟带著漫天的灰尘,尤其是每当南边的高
山吹著『落山风』,真叫人眼睛睁不开。於是『丐帮』拟定做一些水土保持的工作
,但是村里缺乏另一大片空地可以供弟子们练习, 所以每次提出做植地皮的工作就
会遭人反对,於是乎人们还是得继续忍受下去。东、西和北边都是广场的继续延申
。南边则是山坡。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/s4e2.c", 
		"north" : "/d/eastland/beggar/area/s1e1.c", 
		"west" : "/d/eastland/beggar/area/south4.c" ]) );
	ob->set( "objects", ([ 
		"sixth1" : "/d/eastland/beggar/monster/sixth.c", 
		"master" : "/d/eastland/beggar/monster/gonfu_master.c" ]) );
	ob->reset();
}
