// File: /d/eastland/beggar/area/tree1.c
// Generated by Roommaker Mon Jul 22 18:05:13 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("树枝");
	ob->set_long( @LONG_DESCRIPTION
你现在身处一堆浓密的树丛里,由於树枝遮住了太阳,所以你觉得在这里有些阴
冷,或许你该下去透透气。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/eastland/beggar/area/s4w1" ]) );
	ob->set( "objects", ([ 
		"beetle2" : "/d/eastland/beggar/monster/beetle", 
		"swordman" : "/d/eastland/beggar/monster/occult_swordman", 
		"beetle1" : "/d/eastland/beggar/monster/beetle" ]) );
	ob->reset();
}
