// File: /d/eastland/beggar/area/wine_shop.c
// Generated by Roommaker Thu Mar 21 18:10:54 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆』客栈");
	ob->set_long( @LONG_DESCRIPTION
这里是『薪胆村』唯一的一间客栈,往来的旅客都常常在这里休憩。在这里,你
或许可以打听到各地的消息和传言,尤其是地处偏僻的『薪胆村』,这里就显得更为
重要了。店小二正在忙著招呼著客人。墙右角有一个楼梯,可以上到二楼。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/beggar/area/north3.c", 
		"up" : "/d/eastland/beggar/area/wine_shop1.c" ]) );
	ob->set( "objects", ([ 
		"waiter" : "/d/eastland/beggar/monster/waiter.c" ]) );
	ob->reset();
}
