// File: /d/eastland/beggar/area/wine_shop1.c
// Generated by Roommaker Thu Mar 21 18:11:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪胆』客栈二楼");
	ob->set_long( @LONG_DESCRIPTION
这里是『薪胆客栈』的二楼上座, 是属较高价位的地方, 喜欢热闹和出手阔绰
的人都喜欢在这里喝酒聊天。墙右角有一个楼梯可以通往一楼和三楼。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/beggar/area/wine_shop.c", 
		"up" : "/d/eastland/beggar/area/wine_shop2.c" ]) );
	ob->set( "objects", ([ 
		"waiter" : "/d/eastland/beggar/monster/waiter.c", 
		"chan_master" : "/d/eastland/beggar/monster/chan_master.c" ]) );
	ob->reset();
}
