// File: /d/deathland/dwarf/muse54.c
// Generated by Roommaker Thu Nov 23 20:04:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一处宁静的地方");
	ob->set_long( @LONG_DESCRIPTION
在这里, 你只有听到水的滴答声, 安安静静的让你有一种舒适的感觉, 好像来到
了世外桃源一样.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/dwarf/muse53", 
		"north" : "/d/deathland/dwarf/muse55" ]) );
	ob->reset();
}
