// File: /d/deathland/dwarf/muse31.c
// Generated by Roommaker Thu Nov 23 20:05:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一处宁静的地方");
	ob->set_long( @LONG_DESCRIPTION
在这里, 你只有听到水的滴答声, 安安静静的让你有一种舒适的感觉, 好像来到
了世外桃源一样.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/deathland/island/stair07", 
		"north" : "/d/deathland/dwarf/muse32" ]) );
	ob->reset();
}
