// File: /d/deathland/dwarf/squire.c
// Generated by Roommaker Thu Nov 23 19:33:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("训练场");
	ob->set_long( @LONG_DESCRIPTION
这里是一片很大的空地.矮人士兵正在此地接受严格的战场模拟训练
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/dwarf/village_03" ]) );
	ob->set( "objects", ([ 
		"bsoldier" : "/d/deathland/monster/soldier04", 
		"soldier" : "/d/deathland/monster/soldier02", 
		"asoldier" : "/d/deathland/monster/soldier" ]) );
	ob->reset();
}
