// File: /d/deathland/dwarf/village_01.c
// Generated by Roommaker Thu Nov 23 19:29:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往矮人的村落的小路");
	ob->set_long( @LONG_DESCRIPTION
这小路是通往矮人的村落的唯一途径,但是似乎北方有一个很大的军营.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/dwarf/village_02", 
		"south" : "/d/deathland/city/c7" ]) );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard01" ]) );
	ob->reset();
}
