// File: /d/deathland/dwarf/village_02.c
// Generated by Roommaker Thu Nov 23 19:13:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往矮人的村落的小路");
	ob->set_long( @LONG_DESCRIPTION
这小路是通往矮人的村落的唯一途径,但是北方有一个很大的军营.你听到\许
多的矮人士兵正在训练的声音.希望你没有在矮人国度没有作任何的坏事,否则最
好不要继续前进.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/dwarf/village_03", 
		"south" : "/d/deathland/dwarf/village_01" ]) );
	ob->reset();
}
