// File: /d/deathland/dwarf/village_05.c
// Generated by Roommaker Thu Nov 23 19:34:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往矮人的村落的小路");
	ob->set_long( @LONG_DESCRIPTION
这小路是通往矮人的村落的唯一途径,而南方有一个很大的军营.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/dwarf/village_06", 
		"south" : "/d/deathland/dwarf/village_04" ]) );
	ob->reset();
}
