// File: /d/noden/hawk/crack6.c
// Generated by Roommaker Mon Dec  4 21:10:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一个狭窄的洞穴之中，洞穴的地面似乎有人工凿过的痕迹，不过年代
已经相当久远了，你无法确定这些痕迹是天然或人工所造成的，洞穴中的空气相当乾
燥，一股微风从洞穴深处吹了出来。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/noden/hawk/cave", 
		"up" : "/d/noden/hawk/crack5" ]) );
	ob->reset();
}
