// File: /d/noden/hawk/path3.c
// Generated by Roommaker Mon Dec  4 21:10:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石阶坡道");
	ob->set_long( @LONG_DESCRIPTION
你现在正走在一条简陋的石阶坡道上，几块大型的石块被堆置在坡道的两旁，以
免行人失足跌入山谷，在你西南不远处好像有几间茅屋，山中不时传来不知名野兽的
啼叫声。
LONG_DESCRIPTION
	);

	ob->set_outside( "hawk" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/path4", 
		"northeast" : "/d/noden/hawk/path2" ]) );
	ob->reset();
}
