// File: /d/noden/hawk/altar2.c
// Generated by Roommaker Sun Jan  9 07:54:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	object pontiff;

	::create();
	set_short("圆形祭坛");
	set_long( @C_LONG_DESCRIPTION
你现在来到了一个圆形的大祭坛，祭坛中央有一个圆形的洞穴(pit)，在洞穴四周
散布著六个石桌(table)，最大的一个石桌上放著一个三角锥(prymaid)，环绕著祭坛总
共有二十四根白色石柱(pillars)，祭坛的东、北、西三个方向都被极高的悬崖峭壁所
绕，往南是一片空地。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "item_desc", ([ 
		"table" : "这些石桌有大有小，全部都是圆形，似乎是某种魔法阵的装置。\n", 
		"prymaid" : @LONG_TEXT
这个三角锥是透明的，但又不是水晶或玻璃做的，它的一个平面正对著东方
太阳升起的地方，祭坛四周二十四根石柱的影子映在三角锥内部，似乎排列
成什麽符号 ....
LONG_TEXT
, 
		"pillars" : @LONG_TEXT
这些石柱都是大理石做成的，有高有低，有粗有细，不知道当初建造这些石柱
的人为什麽要把它们做成这样，难道有什麽机关 ....
LONG_TEXT
, 
		"pit" : @LONG_TEXT
这个洞穴深不见底，跳(jump)下去不知道会有什麽後果？你似乎隐约听到洞穴
底部传来一阵女人哭泣的呜咽声。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "/d/noden/hawk/altar1" ]) );

	// pontiff is unique, one reboot one pontiff
	pontiff = new("/d/noden/hawk/monster/pontiff");
	pontiff->move(this_object());

	set( "objects", ([
		"guard#1": "/d/noden/hawk/monster/altar_guard",
		"guard#2": "/d/noden/hawk/monster/altar_guard",
		"guard#3": "/d/noden/hawk/monster/altar_guard" ]) );

	reset();
}

int clean_up()
{
	// The pontiff is unique, so don't clean up this room.
	return 0;
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#23");
}
