// File: /d/noden/hawk/cave.c
// Generated by Roommaker Sun Jan  9 04:00:07 1994

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("洞穴尽头");
	set_long( @C_LONG_DESCRIPTION
你现在来到了洞穴最底部的尽头，在你面前的是一张石头制成的桌子(table)和
几块用来当作椅子的石头(rock)，一扇生锈的铁门在你的西边不远处，洞穴中的风
似乎就是从门後吹出来的。
C_LONG_DESCRIPTION
	);

	set( "item_desc", ([ 
		"table" : "石桌上放著几个圆形的铁片(card)，除此之外别无他物。\n", 
		"rock" : "这些石头大小适中，正好可以当椅子坐。\n", 
		"card" : @LONG_TEXT
铁片一共有六片，每片大小不一，最大的一片上面刻著一个三角形，其他的铁
片则是空白的。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"west" : "/d/noden/hawk/altar1", 
		"up" : "/d/noden/hawk/crack6" ]) );
	create_door( "west", "east", ([
		"keyword" : ({ "rusty iron door", "iron door", "door" }),
		"name" : "rusty iron door",
		"c_name" : "生锈铁门",
		"c_desc" : "一扇厚重的生锈铁门",
		"status" : "locked",
		"lock" : "HAWK_ALTAR_ENTRANCE"
	]) );
	reset();
}
