// File: /d/noden/hawk/path4.c
// Generated by Roommaker Thu Jan  6 10:55:53 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("半山腰");
	set_long( @C_LONG_DESCRIPTION
你现在来到半山腰的一处平地，这里虽然地势较为平坦，但是草木仍然长得并不
很高，大概是土壤贫瘠的关系，南边的平地上有几间猎人用的小屋，东北边一条狭窄
的石阶坡道通往山下。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "exits", ([ 
		"northeast" : "/d/noden/hawk/path3", 
		"south" : "/d/noden/hawk/clearing" ]) );
	reset();
#include <replace_room.h>
}
