// File: /d/noden/tomb/tomb8.c
// Generated by Roommaker Mon Dec  4 19:34:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓室");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一间狭小的墓室，四周的墙壁都是用粗糙的岩石砌成的，地上
还散落著几堆凌乱的骨头(bones)，只有中央一具骷髅(skeleton)是完整的，
墓室的顶部似乎有一些裂缝(crack)，透出一些微光，西边的墙上有一个出口
通往外面。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"bones" : "这些骨头的形状看起来像是人类，不过大部分都被打散了。\n", 
		"crack" : "这些裂缝太窄了，而且上面布满了青苔，连攀登都有困难。\n", 
		"skeleton" : @LONG_TEXT
这个骷髅正躺在地板上，胸前插著一把短剑(sword)，被他的两只手握著，也
许是自杀死的。
LONG_TEXT
, 
		"sword" : "这是一把长满铁锈的短剑，插在骷髅心脏的部位。\n" ]) );
	ob->set( "exits", ([ 
		"west" : "/d/noden/tomb/tomb7" ]) );
	ob->set( "objects", ([ 
		"girl" : "/d/noden/tomb/monster/pink_girl" ]) );
	ob->reset();
}
