// File: /d/noden/tomb/tomb5.c
// Generated by Roommaker Mon Dec  4 19:33:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓中密室");
	ob->set_long( @LONG_DESCRIPTION
你现在站在一间圆形的石室中，石室的中央摆著一个石棺(coffin)，四周都是
一些陶罐(pot)、铁箱(box)，从地上灰尘的厚度看起来，这里至少有几百年没有人
来过了。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"box" : @LONG_TEXT
这些铁箱中装满了衣服、香料和一些日用品，由於年代久远，早已腐烂成一堆
乱七八糟的东西了。
LONG_TEXT
, 
		"coffin" : @LONG_TEXT
这个石棺约有三公尺长，一公尺宽，造形像一艘独木舟，上面画满了许多人物
与野兽的图案，盖子和石棺之间不知道用什麽东西密封著，看来是不可能打开这
个石棺了。
LONG_TEXT
, 
		"pot" : "造型古朴的陶罐，上面有一圈一圈的纹路和狩猎的图案。\n" ]) );
	ob->set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb6" ]) );
	ob->set( "objects", ([ 
		"mummy" : "/d/noden/tomb/monster/mummy" ]) );
	ob->reset();
}
