// File: /d/noden/tomb/tomb9.c
// Generated by Roommaker Mon Dec  4 19:35:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓室");
	ob->set_long( @LONG_DESCRIPTION
你现在来到一间幽暗的墓室，在你的正上方有一个开口，像是天井的洞，不
过望出去是黑黝黝的一片，不知道上面是什麽，这里的空气有点潮湿，还带著一
股动物粪便的味道，你有一种奇异的感觉，好像地板下有许多小虫在爬行。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/tomb/tomb2", 
		"north" : "/d/noden/tomb/tomb10" ]) );
	ob->reset();
}
