// File: /d/noden/tomb/tomb11.c
// Generated by Roommaker Tue Oct  4 10:25:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("洞穴");
	set_long( @LONG_DESCRIPTION
这是一个巨大的地底洞穴，和南边的墓室比起来，很明显地可以看出这里
似乎不是人工建造出来的，石壁上满是利爪抓出来的痕迹，也许有什麽凶猛的
地底野兽常在这里打架。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb10" ]) );
   set( "objects", ([
        "centipede2" : "/d/noden/tomb/monster/small_centipede",
        "centipede" : "/d/noden/tomb/monster/centipede",
        "centipede3" : "/d/noden/tomb/monster/small_centipede",
   ]) );
	reset();
}
