// File: /d/noden/tomb/tomb4.c
// Generated by Roommaker Sun Dec 19 21:37:18 1993

#include <mudlib.h>

inherit ROOM;
int mark = 0;

void create()
{
	::create();
   set_short("墓中密室");
	set_long( @LONG_DESCRIPTION
你现在终於明白为什麽刚才那个箱子没有被人打开，因为从前试著打开它的人
现在正坐在你的四周——五具白骨，他们身上的衣服早已腐烂，但是你从散落在白
骨旁边的铲子、铁钩、绳索、等各种工具可以断定这些人是盗墓贼。不过现在你没
空去研究这些骷髅(skeleton)，因为看目前的情形，你不久也要加入他们了。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"skeleton" : @LONG_TEXT
这些骷髅或坐或躺，显然是饿死在这里的，他们所带的背包上有不少齿痕，大概
是饿得头昏眼花的时候拿起来乱啃的。
LONG_TEXT
,
		"corner" : @LONG_TEXT
角落里坐著一个骷髅\，你发现他的手上似乎抓著一张字条(note)。
LONG_TEXT
,
		"note" : "「...	蜘蛛记号是贝塔尔人的传送法术标记，只要用手触摸(touch)...」\n",
		"wall" : "这里的墙壁又冷又硬，没有办法往上爬回刚才的墓室....\n" ]) );
	set( "search_desc", ([ 
		"wall" : @LONG_TEXT
你不死心地继续搜索墙壁上任何可疑的地方，但是什麽麽也没有发现，不...
慢著....你觉得西南边的墙角(corner)泥土好像比较松软，也许可以挖出一条
通道逃出去！
LONG_TEXT
, 
		"here" : @LONG_TEXT
你在四周的石壁上仔细地找了一遍，并没有发现任何密门或是按钮，不过你
可以听到东边的墙壁(wall)传来阵阵水声，不知道是否有出路....
LONG_TEXT
 ]) );
	set( "item_func", ([
		"mark" : "look_mark",
		"dirt" : "look_dirt" ]) );
	set( "objects", ([
		"dagger" : "/d/noden/tomb/obj/dagger" ]) );
	reset();
}

void init()
{
	add_action( "do_dig", "dig" );
	add_action( "do_touch", "touch" );
}

int do_dig(string arg)
{
    if( !arg || arg!="corner" ) write(
            "你用手在脚下的泥土上乱挖，不久就碰到坚硬的石头。\n" );
	else {
            write( 
"你向墙角松软的泥土(dirt)挖掘下去，「啪」一声不知道触动了什麽开关....。\n" );
		mark = 1;
	}
    tell_room( this_object(),
    this_player()->query("c_name") + "在地上到处乱挖,企图找出出口。\n",
		this_player() );
	return 1;
}

void look_dirt()
{
    if( !mark ) write(
            "这些泥土潮湿中带著一故臭味....\n" );
    else write(
             "你看到挖开泥土旁的一块石砖上面有一个蜘蛛的记号(mark)。\n" );
}

void look_mark()
{
    if( !mark ) write( 
             "你想看什麽？\n" );
    else write(
         "一个蜘蛛形状的记号，不知道用来干什麽，如果这些盗墓贼还活著的话\n"
         "也许会知道....\n" );
}

int do_touch(string arg)
{
	if( !arg || !mark || arg!="mark" )
            return notify_fail( "触摸什麽？\n" );
   write(
		"你用手触摸蜘蛛标志，一阵奇异的感觉从标志上传来，等你定下神来，发现\n"
            "周围的景物已经变了！\n" );
	this_player()->move_player("/d/noden/tomb/tomb5", "SNEAK");
   this_player()->set_explore("noden#22");
	return 1;
}
