// File: /d/noden/tomb/tomb2.c
// Generated by Roommaker Wed Jan 11 11:40:52 1995

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("墓穴");
	set_long( @LONG_DESCRIPTION
你现在来到一处较为宽敞的方形石室，墙壁上有几个斑驳锈蚀的铁架，上面
插著几根早已熄灭的火把(torch)，地上积满了厚重的灰尘，这里的蜘蛛网(web)
几乎盖满了天花板与墙角，往北是一座往下的石阶，东边和西边原来好像有通道
，但是现在都被蜘蛛网盖满了，看起来充满危险。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"web" : @LONG_TEXT
一堆灰白色、挂满灰尘的蜘蛛网，和你平常所见的蜘蛛网相比，这些蜘蛛网显
然要大得多了，如果你有一把锋利的斧头，也许能砍(hack)出一条通路。
LONG_TEXT
, 
		"torch" : @LONG_TEXT
这些火把不知道已经熄灭了几百年，上面不但积满灰尘，还有许多蛀虫的孔动
，你发现其中一根火把上的灰尘上隐隐有一个手印，难道....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb3", 
            "south" : "/d/noden/tomb/tomb1" ]) );
	set( "objects", ([ 
		"spider#3" : "/d/noden/tomb/monster/huge_spider", 
		"spider#1" : "/d/noden/tomb/monster/black_spider", 
		"spider#2" : "/d/noden/tomb/monster/black_spider" ]) );
	reset();
}

void init()
{
   add_action( "do_pull", "pull" );
   add_action( "do_hack", "hack" );
}

int do_pull(string arg)
{
   if( !arg || arg!="torch" )
   return notify_fail( "拉什麽?\n" );
   if ( !query("exits/west") ) {
      tell_object( this_player(),
     "你听到隆的一声, 西边突然出现一个出口!\n" );
      set( "exits/west", "/d/noden/tomb/tomb9" );
      return 1;
   }
   tell_object( this_player(),
      "你听到隆的一声, 西边的出口关上了!\n" );
   delete( "exits/west", "/d/noden/tomb/tomb9" );
   return 1;
}

int do_hack(string arg)
{
   if( !arg || arg!="web" )
   return notify_fail( "砍什麽?\n" );
   if( !present("axe", this_player()) )
   return notify_fail( "你没有斧头来砍。\n" );
   if( present("axe",this_player()) ) {
   tell_object( this_player(),
      "你拿起斧头劈开蜘蛛网, 东边的通道被你打开了!\n" );
   set( "exits/east", "/d/noden/tomb/tomb7" );
   this_player()->set_explore("noden#21");
   return 1;
   }
}

void reset()
{
        delete("exits/east");
        delete("exits/west");
        ::reset();
}
