// File: /d/noden/tomb/tomb1.c
// Generated by Roommaker Sun Dec 19 23:26:37 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("地下石穴");
	set_long( @LONG_DESCRIPTION
你现在来到一个狭窄的地下石穴，四周的墙壁是用一些石砖砌成的，地上布满
灰尘，角落里一大堆蜘蛛网，你的第六感告诉你这曾经是一个墓穴，但是现在可能
已经被一大群蜘蛛霸占为巢穴了。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb2", 
		"up" : "/d/noden/13,8.noden" ]) );
	set( "objects", ([ 
		"spider#1" : "/d/noden/tomb/monster/huge_spider", 
		"spider#2" : "/d/noden/tomb/monster/huge_spider" ]) );
	reset();
#include <replace_room.h>
}

