// File: /d/noden/tomb/tomb3.c
// Generated by Roommaker Sun Dec 19 20:58:59 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
  set_short("墓穴");
	set_long( @LONG_DESCRIPTION
这里似乎是放置陪葬品的地方，不过别高兴，你看到一堆箱子罐子全都翻倒
在地上，显然这里已经被盗墓贼搜括过了....四周的墙壁刻著不少动物、仆人以
及房舍，这里埋葬的大概是位有钱人，中央的地板上有一个箱子(chest)似乎没有
被开过，这些粗心的盗墓贼竟然忘了这个箱子....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"chest" : @LONG_TEXT
这个箱子是关著的，箱子上的锁早已因年代久远而锈蚀了，应该可以轻易打开。
LONG_TEXT
 ]) );
 	set( "search_desc", ([
 		"chest" : "它是关著的。\n" ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb2" ]) );
	set( "objects", ([
		"skeleton": "/d/noden/tomb/monster/skeleton" ]) );
	reset();
}

void init()
{
	add_action( "do_open", "open" );
}

int do_open(string arg)
{
	if( !arg || arg!="chest" )
            return notify_fail( "打开什麽？\n" );
   write(
 "你快步走向那个箱子，突然，脚底下「喀拉」一声轻响，你脚下的地板陷了下去！\n" );
    tell_room( this_object(),
 "你听到「喀拉」一声，一回头，"+this_player()->query("c_cap_name")+"已经不见了踪影....\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb4", "SNEAK" );
    tell_room( "/d/noden/tomb/tomb4",
 "你听到"+this_player()->query("c_cap_name")+"像小孩子一般地尖叫著——从上面掉了下来。\n",
		this_player() );
	return 1;
}

