// File: /d/noden/tomb/tomb6.c
// Generated by Roommaker Sun Dec 19 22:55:09 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("墓中密室");
	set_long( @LONG_DESCRIPTION
这间石室比北边的房间略小，但是布置著许多石制的家俱(furniture)，要不
是这里是个墓穴，这样的布置可算是应有尽有，十分舒适的住所了。你注意到石室
中央的地毯(carpet)中间向下凹，可能有些古怪....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"furniture" : "这些家俱虽然年代久远，但是上面都刻满精细的花纹，看起来质地相当昂贵。\n" ]) );
	set( "item_func", ([
		"carpet": "look_carpet" ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb5" ]) );
	set( "objects", ([
		"spider#1": "/d/noden/tomb/monster/red_spider",
		"spider#2": "/d/noden/tomb/monster/red_spider"]) );
	reset();
}

void look_carpet()
{
   write(
		"这张地毯上面绣著两个并肩而行的猎人，手上提著....你一脚踩上地毯，却踩了个\n"
            "空，这张地毯是个幻影！\n" );
    tell_room( this_object(),
        "你听到"+this_player()->query("c_cap_name") + "一声惊叫，转过头去人已经不见了。\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb2", "SNEAK" );
   this_player()->set_explore("noden#20");
    tell_room( "/d/noden/tomb/tomb2",
             "你听到有人大声惊叫，然後一个影子掉下来，差一点压到你....\n",
		this_player() );
}
