// File: /d/noden/forest/1n1w.c
// Generated by Roommaker Mon Dec  4 21:15:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
这里是阴森的黑森林。如它的名字一般, 在这里的树木枝叶异常地茂
密, 即使是正午猛烈的阳光也丝毫无法照射到这里的地面。据传说, 这是
由於受到魔族邪恶魔法的影响, 以致於森林中的一草一木、小动物们都变
成邪恶的黑暗生物。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"east" }) );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/forest/2n2w", 
		"east" : "/d/noden/forest/1n" ]) );
	ob->reset();
}
