// File: /d/noden/forest/1n1e.c
// Generated by Roommaker Mon Dec  4 21:15:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
你走在阴森的黑森林中, 一股无法忽视的邪恶气息让你的神经异常地
紧绷。在这里到处都可能充满著危险, 注意你的四周! 小心不要成了黑暗
生物们的点心。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"east", 
		"west" }) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/1n2e", 
		"west" : "/d/noden/forest/1n", 
		"north" : "/d/noden/forest/2n1e" ]) );
	ob->reset();
}
