// File: /d/noden/forest/1n2e.c
// Generated by Roommaker Mon Dec  4 21:15:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林深处");
	ob->set_long( @LONG_DESCRIPTION
依然是枝叶茂密的树木, 与不知道底有多厚的腐叶。这里是黑森林的
深处, 一股危险的气氛正笼罩著你的四周。
    你感觉在杂密的树木後面, 有某些东西正在注视著你。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"west" }) );
	ob->set( "exits", ([ 
		"west" : "/d/noden/forest/1n1e" ]) );
	ob->set( "objects", ([ 
		"goblin2" : "/d/noden/forest/monster/goblin", 
		"goblin1" : "/d/noden/forest/monster/goblin" ]) );
	ob->reset();
}
