// File: /d/noden/forest/2n.c
// Generated by Roommaker Mon Dec  4 21:16:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
你走在黑森林中, 四周一片幽暗, 强大而邪恶的魔法紧紧地束缚著此
地的空气。这种气息使你觉得非常, 非常地不安, 深怕在此停留稍久, 也
会遭到魔力所害, 被同化为森林中邪恶生物们的一员。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"northwest" }) );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/forest/3n1w", 
		"south" : "/d/noden/forest/1n" ]) );
	ob->reset();
}
