// File: /d/noden/forest/2n1e.c
// Generated by Roommaker Mon Dec  4 21:16:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
这里是阴森的黑森林。如它的名字一般, 这个森林的树木异常地茂密
, 使得无论多麽强烈的阳光都完全无法穿透进来。据传说, 这是受到魔族
邪恶魔法的影响, 森林中的一草一木、小动物们都变成邪恶的黑暗生物。
    此外, 许\多传言指出此地有著前往魔族古帝国的秘密通道。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"south" }) );
	ob->set( "exits", ([ 
		"south" : "/d/noden/forest/1n1e", 
		"northeast" : "/d/noden/forest/3n2e" ]) );
	ob->reset();
}
