// File: /d/noden/forest/2n2w.c
// Generated by Roommaker Mon Dec  4 21:16:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
这里是邪恶的黑森林, 黑暗无声无息地笼罩著你的四周, 不祥的强大
魔力正在树荫下的空气中汤漾著。恐怖、不悦的气氛无时无刻不在, 强烈
地刺激著你的神经。在你的附近, 有些残馀物零零落落地散成一堆, 看来
格外地恶心。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"southeast" }) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/3n2w", 
		"southeast" : "/d/noden/forest/1n1w" ]) );
	ob->set( "objects", ([ 
		"ammunt" : "/d/noden/forest/monster/ammunt" ]) );
	ob->reset();
}
