// File: /d/noden/forest/3n2e.c
// Generated by Roommaker Mon Dec  4 21:17:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中空地");
	ob->set_long( @LONG_DESCRIPTION
很难得地, 这边竟然有一块空地, 那些带有邪气的树木完全不敢将他
们的枝叶伸进这空地一步。不过这好像不是什麽值得高兴的事, 因为在空
地的中心, 长了一棵很高, 很老, 很邪恶的树。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"southwest" }) );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/forest/2n1e" ]) );
	ob->set( "item_desc", ([ 
		"tree" : "这棵树上下充满著邪气, 使你不由得担心它什麽时候会突然向你发动\n攻击。\n" ]) );
	ob->set( "objects", ([ 
		"reaper2" : "/d/noden/forest/monster/reaper", 
		"reaper1" : "/d/noden/forest/monster/reaper" ]) );
	ob->reset();
}
