// File: /d/noden/elf/elf/elf32.c
// Generated by Roommaker Mon Dec  4 21:50:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("树洞");
	ob->set_long( @LONG_DESCRIPTION
  这里是一个树洞房间，有一张大桌子摆\在房子的中间，几张椅子
  整齐的排放著，墙上有几只大火把，使整个房间明亮如昼。北边有一
  间漂亮的洞中屋。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/noden/elf/elf/elf31", 
		"north" : "/d/noden/elf/elf/elf33" ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/noden/elf/monster/guard", 
		"guard1" : "/d/noden/elf/monster/guard" ]) );
	ob->reset();
}
