// File: /d/noden/elf/elf/elf25.c
// Generated by Roommaker Mon Dec  4 21:46:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
这里是一望无际的大草原(plain)，呈现在你面前的是一个大池塘，池边
长著无数的芦苇草，同时几株野莲正疏落有致地散落池面，附近有很多动物
杂乱的脚印，你想此处必是动物取水的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "elf_hamlet" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/elf/elf/elf26", 
		"east" : "/d/noden/elf/elf/elf24", 
		"west" : "/d/noden/elf/elf/elf27" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
这里长满著青翠的小草，几丛灌木孤独地耸立著，虽然此处看起来
十分平静，但是据说附近常有野兽出没，故而此处是精灵们的狩
猎场。
LONG_TEXT
 ]) );
	ob->reset();
}
