// File: /d/noden/elf/elf/elf17.c
// Generated by Roommaker Mon Dec  4 21:45:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("木精灵工作室");
	ob->set_long( @LONG_DESCRIPTION
"这是一个充满木屑和雕像的房间，可能是为了通风方便，四面墙上都有巨大
的落地窗，房子的正中央放了一张很大的工作桌，桌上放著几件未完成的作品
，左侧角落放著几支散落的酒瓶，由房子架设的情况看来，此屋子的主人必定
是一位有酒瘾的工作狂。"
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/elf/elf/elf7" ]) );
	ob->set( "objects", ([ 
		"icers" : "/d/noden/elf/monster/wind" ]) );
	ob->reset();
}
