// File: /d/noden/elf/elf/elf6.c
// Generated by Roommaker Mon Dec  4 21:59:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
这里是一望无际的大草原(plain)，有无数的动物生长在这里，南方有一座
小山丘，西方一眼望去尽是连绵的草原，同时此地偶而传来狼嚎声，你想附近必
定有狼的巢穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/elf/elf/elf14.c", 
		"west" : "/d/noden/elf/elf/elf12.c", 
		"north" : "/d/noden/elf/elf/elf3.c", 
		"south" : "/d/noden/elf/elf/elf13.c" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
这里长满著青翠的小草，几丛灌木孤独地耸立著，虽然此处看起来
十分平静，但是据说附近常有野兽出没，故而此处是精灵们的狩
猎场。
LONG_TEXT
 ]) );
	ob->reset();
}
