// File: /d/noden/elf/elf/elf40.c
// Generated by Roommaker Mon Dec  4 21:52:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
 此处是一个原始迷宫，当前次魔族入侵时，精灵们曾引诱一些魔族战士进入此
 迷宫，从此以後每逢月圆之夜，迷宫中总是传来阵阵凄厉的吼叫声，精灵族人
 把此处画为禁地，严禁族人进入，经过多年时光的演变，此处已变成无人的死
 域。      
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/elf/elf/elf38", 
		"west" : "/d/noden/elf/elf/elf40", 
		"north" : "/d/noden/elf/elf/elf43", 
		"south" : "/d/noden/elf/elf/elf36" ]) );
	ob->reset();
}
