// File: /d/noden/elf/elf/elf20.c
// Generated by Roommaker Mon Dec  4 21:45:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("长老之屋");
	ob->set_long( @LONG_DESCRIPTION
这里是精灵小屋在屋子的北方有一张用杉木制成的书桌，及一张用
石头做的椅子，东边是一面挂满图画的墙，西面有一个大书架(bookshelf)
，同时你也看见在架子旁有几个大木箱，南面有一张铺著绣有精灵族图案被
子的床，南方有一个大窗户，从窗户望出去是一片翠绿的草原，从微风轻送
来的空气中，传来一股似有似无的香味，使你精神一振。

LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf18" ]) );
	ob->set( "objects", ([ 
		"elf elder" : "/d/noden/elf/monster/elder" ]) );
	ob->reset();
}
