// File: /d/noden/elf/elf/elf26.c
// Generated by Roommaker Mon Dec  4 21:47:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
这里是一望无际的大草原(plain)，你的眼前有一些草丛(bushes)肃立著，
有无数野牛脚印散落地面，遍地的青草有被撕咬过的痕迹，而草丛中时而传
来阵阵牛鸣声，你想这附近大概有野牛的巢穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elf_hamlet" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/elf/elf/elf29", 
		"south" : "/d/noden/elf/elf/elf28", 
		"northeast" : "/d/noden/elf/elf/elf25" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
这里长满著青翠的小草，几丛灌木孤独地耸立著，虽然此处看起来
十分平静，但是据说附近常有野兽出没，故而此处是精灵们的狩
猎场。
LONG_TEXT
, 
		"bushes" : "这些草丛长满荆棘你应该不能通过(pass)它\n" ]) );
	ob->set( "objects", ([ 
		"buffalo" : "/d/noden/elf/monster/buffalo" ]) );
	ob->reset();
}
