// File: /d/noden/elf/elf/elf8.c
// Generated by Roommaker Mon Dec  4 21:59:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精灵屋");
	ob->set_long( @LONG_DESCRIPTION
这里是精灵小屋在屋子的北方有一张用杉木制成的书桌，及一
张用石头做的椅子，西边是一面挂满图画南面有一张铺著绣有精灵
族图案被子的床，南方有一个大窗户，从窗户望出去是一片翠绿的
草原，从微风轻送来的空气中，传来一股似有似无的香味，使你精
神一振。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf5" ]) );
	ob->set( "objects", ([ 
		"lady1" : "/d/noden/elf/monster/lady", 
		"lady2" : "/d/noden/elf/monster/lady" ]) );
	ob->reset();
}
