// File: /u/l/layuter/elf/elf18.c
// Generated by Roommaker Thu Nov 18 13:33:19 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("石板路");
	set_long( @LONG_DESCRIPTION
这是一条用石板铺成的路，路的两旁是精灵屋及绿意盎然的植
道树，石板上刻著精灵族的标帜(mark)，很有规律地向前延伸。在
此刻你正走到路的尽头，在你眼前有一棵巨大的树(tree)，高耸的
向天际拔升，在树旁有一个竖立的招牌。
LONG_DESCRIPTION
	);
    set("item_desc",([
        "mark" : "这标志是一个带著桂花冠的天马\n",
        "tree" : @TREE
  这是一棵高耸入天的树，你注意到它有一些树枝(branch)低垂，
  你好像可以爬上这些树枝。
TREE
]));            
	set( "light", 1 );
	set( "exits", ([
		"south" : LELF"elf20",
		"north" : LELF"elf19",
		"east" : LELF"elf11"
	]) );
}

void init()
{
    add_action("do_climb","climb");
 }
 
int do_climb(string arg)
{ 
 if (!arg || arg!="branch") return 0;
 this_player()->move_player(LELF"elf31","SNEAK");
 tell_room(this_object(), this_player()->query("c_name")+"爬上树枝\n",this_player());
 return 1;
 }

