// File: /u/l/layuter/elf/elf2.c
// Generated by Roommaker Thu Nov 11 16:10:41 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
        ::create();
        set_short("A empty room", "精灵村广场");
        set_long( @LONG_DESCRIPTION
，这是一个用大理石沏成的广场，广场中央是一个喷水池(fountain)
，池旁是一坐巨大的雕像(statue)，天空中有几只和平鸽(dove)在盘旋著
，有几棵百年老树(tree)高大地遮蔽过往的行人。
LONG_DESCRIPTION
        );
        
    set("c_item_desc",([
       "fountain" : "这水池的水既清澈又冰凉，是精灵们的主要水源。\n",
       "dove" : "这是一种白色的鸟类，看起来十分的温驯。\n",
       "tree" : "这树看起来十分的高大，以你的能力似乎无法爬上去(climb)。\n",
       "statue": @STATUE
 这雕像是一座巨大的女神像，在神像的下方有一个告示版(board)，
 当你注视此神像时，你发现神像的右手好像特别乾净。      
STATUE
,
       "hand" : "这手的位置太高，你仅能勉强的拉动它。\n",
       "board" : @BOARD
这是精灵村守护神`希纳斯'的神像，她曾经帮助精灵们抵抗魔族的侵略，
因此他成为了此村的守护神。希纳斯的神性是爱与和平，故而在她的感化
之下，精灵村的精灵们都有著善良的习性与好客的脾气。
BOARD
       ]));
    set("objects",([
        "little1" : "/d/noden/elf/monster/child",
        "little2" : "/d/noden/elf/monster/child",
        "dove" : "/d/noden/elf/monster/dove",
        ]));   
        set( "light", 1 );
   set( "exits", ([
        "east" : "/d/noden/elf/elf/elf1",
        "south" : "/d/noden/elf/elf/elf3",
        "north" : "/d/noden/elf/elf/elf4",
        "west" : "/d/noden/elf/elf/elf5",
     ]) );
        reset();
}

void init()
{
    add_action("do_pull","pull");
}

int do_pull(string arg)
{  
    if( !arg || arg != "hand" ) return 0;
    tell_room(this_object(),"地板上突然出现一个地洞,"+
        this_player()->query("c_name")+"掉入洞中，而地板却立刻恢复原状。\n",
        this_player());
   this_player()->set_explore("noden#31");
   this_player()->move_player("/d/noden/elf/elf/elf35","SNEAK");
    return 1;
}
