// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("地洞");
	set_long( @LONG_DESCRIPTION
 此处是一个原始迷宫，当前次魔族入侵时，精灵们曾引诱一些魔族战士进入此
 迷宫，从此以後每逢月圆之夜，迷宫中总是传来阵阵凄厉的吼叫声，精灵族人
 把此处画为禁地，严禁族人进入，经过多年时光的演变，此处已变成无人的死
 域。      
LONG_DESCRIPTION
	);	
	set("objects",([
	    "fighter":LMONSTER"fighter",
	    "fighter1":LMONSTER"fighter" ]));
	set( "light", 0);
	set("exits",([
	    "south" : LELF"elf38",
	    "north" : LELF"elf40",
	    "east" : LELF"elf41",
	    "west" : LELF"elf40"]));
	    reset();
}
