// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("草原");
	set_long( @LONG_DESCRIPTION
这里是一望无际的大草原(plain)，有无数的动物生长在这里，你的眼前
有一些草丛(bushes)肃立著。此地有一些小灌木生长著，同时地上还有数十个
小地洞(cellar)。
LONG_DESCRIPTION
	);
    set("item_desc",([
     "cellar" : "这些地洞很小，像是土拨鼠的巢穴。\n",
     "bushes" : "这些草丛长满杂草你应该能通过(pass)它\n",
     "plain" : @Plain
这里长满著青翠的小草，几丛灌木孤独地耸立著，虽然此处看起来
十分平静，但是据说附近常有野兽出没，故而此处是精灵们的狩
猎场。
Plain
      ]));
	set("exits",([
	      "north" : LELF"elf24"
	      ]));
    set_outside("elfhamlat");
	set("objects",([
          "marmot1" : LMONSTER"marmot",         
          "marmot2" : LMONSTER"marmot",
          "marmot3" : LMONSTER"marmot",
          "marmot4" : LMONSTER"marmot",
          "marmot5" : LMONSTER"marmot"
	     ]));
	reset();
}

void init()
{
  add_action("do_pass","pass");
  }
  
int do_pass(string arg)
{
   if (!arg || arg!="bushes") return 0;
   this_player()->move_player(LELF"elf45","SNEAK");
   this_player()->set_explore("noden#30");
   tell_room(this_object(),
	this_player()->query("c_name")+"进入草丛中。\n"
      ,this_player());
   return 1;
 }
