// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("树枝");
	set_long( @LONG_DESCRIPTION
你现在是位於浓密的树丛中，从树丛的隙缝中，你发现一个大树洞(hole)
，好像有一些火光从其中透出。
LONG_DESCRIPTION
	);	
	set("item_desc",([
	    "hole" : "这是一个大树洞，看起来应该有足够的空间可以进入(enter)它。\n"]));
	set( "light", 0);
	set("exits",([
	    "down" : LELF"elf18"]));
}
void init()
{
  add_action("do_enter","enter");
  }
 
int do_enter(string arg)
{
    if(!arg || arg!="hole") return 0;
    this_player()->move_player(LELF"elf32","SNEAK");
    tell_room(this_object(),this_player()->query("c_name")+" 进入洞穴中 \n",this_player());
    return 1;
    } 
