// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("草原");
	set_long( @LONG_DESCRIPTION
这里是草原和森林的交界处,眼前是一片郁郁苍苍的密林，林中
时而传来鸟兽的叫声,从此处望去林中是一片翠绿，你有想进入
森林的冲动，可惜你找不到小路可以进入。
LONG_DESCRIPTION
	);
	set("objects",([
	    "unicon" : LMONSTER"unicorn"]));	    
    set_outside("elfhamlat");
	set( "exits", ([
		"leave" : LELF"elf30"
	]) );
	reset();
}
