// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("地洞");
	set_long( @LONG_DESCRIPTION
 此处是一个原始迷宫深处的一个房间，这里的摆设和平常人的一样，有一个大桌子
 ，而有几张小椅子随处散置著，一张木床闲置在角落，但奇怪的是这间房子在四面
 墙上都有一个大窗户，你想屋主一定是个胆小的人。 
LONG_DESCRIPTION
	);	
	set( "light", 0);
	set("exits",([
	    "south" : LELF"elf43"]));
	set("objects",([
	    "thiris" : LMONSTER"steal",
	    "fighter1": LMONSTER"fighter",
	    "fighter2": LMONSTER"fighter"]));
	 reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#32");
}
