// File: /d/noden/tamumu/cave1.c
// Generated by Roommaker Mon Dec  4 19:41:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你进入了一个奇异的洞穴，洞穴西边的出口被一片水幕遮住，水花溅得这里
的地面上积了许多水洼。由於潮湿的水气，岩壁上生满了厚厚的青苔，洞穴往西
似乎隐隐有著火光，什麽样的生物会居住在这个隐密的洞穴中呢？
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/11,5.noden", 
		"west" : "/d/noden/tamumu/cave2" ]) );
	ob->reset();
}
