// File: /d/noden/tamumu/cave2.c
// Generated by Roommaker Mon Dec  4 19:42:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
这里是一个天然的洞穴，也许该说是半天然的，岩壁上并没有任何斧凿的痕迹
或人工的修饰，但是在你面前的是一道石阶，通往西边。石阶旁有一个石刻的奇特
雕像(statue)，看起来似乎是这里唯一的光源。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/tamumu/cave1", 
		"west" : "/d/noden/tamumu/cave3" ]) );
	ob->set( "item_desc", ([ 
		"statue" : @LONG_TEXT
这个雕像有著人类的头颅、狮子的身体、和一双蝙蝠般的翅膀，它的前爪捧
著一个球形的容器，容器里盛满了黄色膏状的东西，一根灯心正在容器中央
燃烧著，发出微弱的光芒。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"tamumu#1" : "/d/noden/tamumu/monster/warrior", 
		"tamumu#2" : "/d/noden/tamumu/monster/warrior" ]) );
	ob->reset();
}
