// File: /d/noden/tamumu/cave4.c
// Generated by Roommaker Mon Dec  4 19:42:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("阶梯");
	ob->set_long( @LONG_DESCRIPTION
你现在走上一个洞穴中的阶梯，上方的岩壁低得几乎要碰到你的头。你发现
西边不远处有一个巨大的洞穴，洞穴的入口处站著两座石雕(statue)，看起来这
里是塔姆姆人的祭坛，建造阶梯的人故意将上方的岩壁留下，使得进入祭坛的人
都必须弯著身子。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/tamumu/cave3", 
		"west" : "/d/noden/tamumu/altar" ]) );
	ob->set( "item_desc", ([ 
		"statue" : @LONG_TEXT
这两座雕像都是人的头颅、狮子的身体、以及一对蝙蝠般的翅膀，左边的雕像
脚底下踩著一只蟒蛇，右边的雕像脚底下踩著一只蜘蛛，看起来有说不出的诡
异。
LONG_TEXT
 ]) );
	ob->reset();
}
