// File: /d/noden/tamumu/cave7.c
// Generated by Roommaker Mon Dec  4 19:44:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你进入了一个狭窄的通道，左右两旁的石壁给人一种不寻常的压迫感，你的
头顶不时传来一阵阵蝙蝠的吱吱叫声，地上不知道为什麽湿漉漉的一片，还长著
许多不知名的青苔，你必须很小心地前进以免滑倒。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/noden/tamumu/cave8", 
		"southeast" : "/d/noden/tamumu/cave6" ]) );
	ob->reset();
}
