// File: /d/noden/tamumu/altar.c
// Generated by Roommaker Wed Dec 15 10:58:47 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("塔姆姆祭坛");
	set_long( @C_LONG_DESCRIPTION
你来到一个巨大的洞穴之中，洞穴顶端不知道有什麽东西盘踞著，你只听到
一阵阵「嗤....嗤....」的声音从上面传来。在你面前是一尊人形石雕(statue)
旁边围绕著数根黑色的石柱(pillar)，石雕前有一个血迹斑斑的平台(plate)，
看起来塔姆姆人一定是有用活人献祭的习惯，你最好趁他们还没有找上你之前离
开这里....。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "item_desc", ([ 
		"symbols" : @LONG_TEXT
这些符号大多扭曲变形，难以辨认，不过你大约可以看出上面有代表狮子、
老鹰、蜘蛛三种生物的图形。
LONG_TEXT
, 
		"statue" : @LONG_TEXT
这个石雕足足有三、四个人高，和前面所见到的雕像恰好相反，这座雕像有著
狮子的头颅和人类的身体，同样的一对蝙蝠般翅膀紧贴在石雕背後，石雕的右
手指向洞穴顶端，左手指著地上的平台，你突然有股冲动想顺著石雕的手臂(
arm)爬上洞穴顶端一探究竟。
LONG_TEXT
, 
		"pillar" : @LONG_TEXT
这些石柱或高或矮，但是清一色都黑得发亮，上面刻满了各种诡异的符号(
symbols)与纹路。
LONG_TEXT
, 
		"plate" : @LONG_TEXT
这个平台上血迹斑斑，连旁边的泥土都沾著不少凝结的血块，你怀疑这个
平台上杀过多少个牺牲者？
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tamumu/cave5", 
		"north" : "/d/noden/tamumu/cave6", 
		"east" : "/d/noden/tamumu/cave4" ]) );
	set( "objects", ([ 
		"monk#1" : "/d/noden/tamumu/monster/monk", 
		"monk#2" : "/d/noden/tamumu/monster/monk", 
		"chieftain" : "/d/noden/tamumu/monster/chieftain" ]) );
	reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#13");
}
