// File: /d/noden/tamumu/cave9.c
// Generated by Roommaker Wed Dec 15 07:15:48 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("洞穴尽头");
	set_long( @C_LONG_DESCRIPTION
这里是这个洞穴的尽头，一张石制的桌子(table)的中央，旁边的地上堆著
几条铁链(chain)，腐臭的味道来自你的北边，往东是一条阴暗狭窄的通道，你
似乎听到有人在说话，但是不知道声音从哪里来。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "item_desc", ([ 
		"table" : "桌上有一盏小小的油灯，正发出微弱的光线，照亮这个洞穴\n", 
		"chain" : @LONG_TEXT
这些铁链上沾满血迹，已经分辨不出它们原来是什麽样子，光是想像这些
铁链的用途就令你不寒而栗。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tamumu/jail1", 
		"east" : "/d/noden/tamumu/cave8" ]) );
	set( "objects", ([
		"jailor": "/d/noden/tamumu/monster/jailor" ]) );
	create_door( "north", "south", ([
		"keyword" : ({"door", "iron door"}),
		"name" : "iron door",
		"c_name" : "铁门",
		"c_desc" : "一扇厚实的铁门，上面有一道凹槽",
		"status" : "locked",
		"lock" : "TAMUMU_JAIL1"
	]) );
	reset();
}
